[mcp_servers.exa]
url = "https://mcp.exa.ai/mcp"

[mcp_servers.inngest]
url = "http://127.0.0.1:8288/mcp"

[mcp_servers.next-devtools]
command = "npx"
args = [
    "-y",
    "next-devtools-mcp@0.3.10",
]

[mcp_servers.lightfast]
url = "https://mcp.lightfast.ai/mcp"
