export const siteConfig = {
  name: "Lightfast",
  url: "https://chat.lightfast.ai",
  ogImage: "https://lightfast.ai/og.jpg",
  description:
    "Real-time AI chat application with Claude 4, GPT-4o, and streaming responses. Built with Next.js and Convex for intelligent conversations.",
  keywords: [
    "AI chat",
    "Claude 4",
    "GPT-4o",
    "real-time chat",
    "AI assistant",
    "streaming chat",
    "GitHub authentication",
    "Convex database",
    "Next.js chat",
    "Claude Sonnet",
    "AI conversation",
    "chat application",
    "Anthropic Claude",
    "OpenAI GPT",
    "Lightfast",
    "machine learning chat",
    "AI messaging",
    "conversational AI",
    "intelligent chat",
    "thread management",
  ] as string[],
  authors: [
    {
      name: "Lightfast",
      url: "https://lightfast.ai",
    },
  ] as Array<{ name: string; url: string }>,
  creator: "Lightfast",
  links: {
    twitter: "https://x.com/lightfastai",
    github: "https://github.com/lightfastai",
    discord: "https://discord.gg/YqPDfcar2C",
    privacy: "https://lightfast.ai/legal/privacy",
    terms: "https://lightfast.ai/legal/terms",
    chat: "https://chat.lightfast.ai",
  },
  location: "3141, Melbourne, VIC, Australia",
} as const
