export enum EarlyAccessErrorType {
  RATE_LIMIT = "RATE_LIMIT",
  INVALID_EMAIL = "INVALID_EMAIL",
  ALREADY_REGISTERED = "ALREADY_REGISTERED",
  SECURITY_CHECK = "SECURITY_CHECK",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export interface NextErrorResponse {
  type: string;
  error: string;
  message: string;
}
