import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const FOOTER_PATTERNS = [
  { name: "circle", a: 1, b: 1, delta: Math.PI / 2 },
  { name: "figure8", a: 1, b: 2, delta: Math.PI / 2 },
  { name: "pretzel", a: 3, b: 2, delta: Math.PI / 2 },
  { name: "bow", a: 2, b: 3, delta: Math.PI / 2 },
  { name: "knot", a: 3, b: 4, delta: Math.PI / 2 },
  { name: "star", a: 5, b: 4, delta: Math.PI / 2 },
  { name: "wave", a: 1, b: 3, delta: Math.PI / 4 },
  { name: "infinity", a: 2, b: 1, delta: Math.PI / 2 },
  { name: "clover", a: 3, b: 1, delta: Math.PI / 2 },
] as const;

function computePath(
  a: number,
  b: number,
  delta: number,
  points = 500,
  padding = 10,
): string {
  const pts: { x: number; y: number }[] = [];
  for (let i = 0; i <= points; i++) {
    const t = (i / points) * 2 * Math.PI;
    pts.push({ x: Math.sin(a * t + delta), y: Math.sin(b * t) });
  }
  const size = 100 - padding * 2;
  const scaled = pts.map((p) => ({
    x: padding + ((p.x + 1) / 2) * size,
    y: padding + ((p.y + 1) / 2) * size,
  }));
  return scaled
    .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`)
    .join(" ");
}

async function main() {
  const outputPath = path.resolve(
    __dirname,
    "../../../apps/www/src/lib/generated/lissajous-paths.ts",
  );
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  const entries = FOOTER_PATTERNS.map(({ name, a, b, delta }) => ({
    name,
    d: computePath(a, b, delta),
  }));

  const lines = [
    "// AUTO-GENERATED by packages/console-remotion/src/render-lissajous.ts",
    "// Do not edit manually. Regenerate with: pnpm --filter @repo/console-remotion render:lissajous",
    "",
    "export const LISSAJOUS_PATHS: ReadonlyArray<{ name: string; d: string }> = [",
    ...entries.map(({ name, d }) => `  { name: "${name}", d: "${d}" },`),
    "] as const;",
    "",
  ];

  await fs.writeFile(outputPath, lines.join("\n"), "utf8");
  console.log(`Lissajous paths written to: ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
