// Re-export common utilities from vendor/db
export {
	createPlanetScaleClient,
	createDatabase,
	drizzle,
	Client,
	FakePrimitiveParam,
	isSQLWrapper,
	StringChunk,
	SQL,
	Name,
	name,
	isDriverValueEncoder,
	noopDecoder,
	noopEncoder,
	noopMapper,
	Param,
	param,
	sql,
	Placeholder,
	placeholder,
	fillPlaceholders,
	View,
	isView,
	getViewName,
	bindIfParam,
	eq,
	ne,
	and,
	or,
	not,
	gt,
	gte,
	lt,
	lte,
	inArray,
	notInArray,
	isNull,
	isNotNull,
	exists,
	notExists,
	between,
	notBetween,
	like,
	notLike,
	ilike,
	notIlike,
	arrayContains,
	arrayContained,
	arrayOverlaps,
	asc,
	desc,
	count,
	countDistinct,
	avg,
	avgDistinct,
	sum,
	sumDistinct,
	max,
	min,
	l2Distance,
	l1Distance,
	innerProduct,
	cosineDistance,
	hammingDistance,
	jaccardDistance,
	alias,
	createSelectSchema,
	createInsertSchema,
	createUpdateSchema,
	createSchemaFactory,
	isColumnType,
	isWithEnum,
	isPgEnum,
	bufferSchema,
	jsonSchema,
	literalSchema,
	createDrizzleConfig,
} from "@vendor/db";
export type {
	DatabaseConfig,
	PlanetScaleDatabase,
	PlanetScaleConfig,
	Chunk,
	BuildQueryConfig,
	QueryTypingsValue,
	Query,
	QueryWithTypings,
	SQLWrapper,
	GetDecoderResult,
	DriverValueDecoder,
	DriverValueEncoder,
	DriverValueMapper,
	SQLChunk,
	ColumnsSelection,
	InferSelectViewModel,
	BinaryOperator,
	GetEnumValuesFromColumn,
	GetBaseColumn,
	GetZodType,
	HandleColumn,
	CreateSelectSchema,
	CreateInsertSchema,
	CreateUpdateSchema,
	CreateSchemaFactoryOptions,
	Conditions,
	BuildRefineColumns,
	BuildRefine,
	BuildSchema,
	NoUnknownKeys,
	Json,
	IsNever,
	ArrayHasAtLeastOneValue,
	ColumnIsGeneratedAlwaysAs,
	RemoveNever,
	GetSelection,
} from "@vendor/db";

// Export chat-specific schema (no client to prevent env var exposure)
export {
	// session
	LightfastChatSession,
	type InsertLightfastChatSession,
	insertLightfastChatSessionSchema,
	selectLightfastChatSessionSchema,
	// message
	LightfastChatMessage,
	type InsertLightfastChatMessage,
	insertLightfastChatMessageSchema,
	selectLightfastChatMessageSchema,
	// message-feedback
	LightfastChatMessageFeedback,
	type InsertLightfastChatMessageFeedback,
	insertLightfastChatMessageFeedbackSchema,
	selectLightfastChatMessageFeedbackSchema,
	// stream
	LightfastChatStream,
	lightfastChatStreamRelations,
	type InsertLightfastChatStream,
	insertLightfastChatStreamSchema,
	selectLightfastChatStreamSchema,
	// artifact
	LightfastChatArtifact,
	type InsertLightfastChatArtifact,
	ARTIFACT_KINDS,
	type ArtifactKind,
	insertLightfastChatArtifactSchema,
	selectLightfastChatArtifactSchema,
	// usage
	LightfastChatUsage,
	type InsertLightfastChatUsage,
	insertLightfastChatUsageSchema,
	selectLightfastChatUsageSchema,
	// quota-reservations
	LightfastChatQuotaReservation,
	type InsertLightfastChatQuotaReservation,
	RESERVATION_STATUS,
	type ReservationStatus,
	insertLightfastChatQuotaReservationSchema,
	selectLightfastChatQuotaReservationSchema,
	// session-share
	LightfastChatSessionShare,
	type InsertLightfastChatSessionShare,
	insertLightfastChatSessionShareSchema,
	selectLightfastChatSessionShareSchema,
	// relations
	lightfastChatSessionRelations,
	lightfastChatMessageRelations,
	lightfastChatArtifactRelations,
	lightfastChatMessageFeedbackRelations,
	lightfastChatSessionShareRelations,
	// attachment
	LightfastChatAttachment,
	type InsertLightfastChatAttachment,
	insertLightfastChatAttachmentSchema,
	selectLightfastChatAttachmentSchema,
} from "./schema";
