packages:
  - "apps/*"
  - "packages/*"
  - "internal/*"
  - "vendor/*"

catalog:
  # Tanstack
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0

  # Misc
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^9.12.0
  prettier: ^3.3.3
  zod: ^3.23.8
  typescript: ^5.6.3
  "@types/node": ^20.16.11
  "@types/eslint": ^8

  # Next
  next: 15.2.5

catalogs:
  react18:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.0
