packages:
  - api/*
  - apps/*
  - core/*
  - db/*
  - packages/*
  - internal/*
  - vendor/*

catalog:
  '@ai-sdk/gateway': 1.0.7
  '@ai-sdk/react': 2.0.15
  '@clerk/backend': 3.2.13
  '@clerk/nextjs': 7.2.3
  '@clerk/shared': 4.8.2
  '@hookform/resolvers': ^5.2.2
  '@lightfastai/dev-core': ^0.1.1
  '@lightfastai/dev-services': ^0.1.5
  '@lightfastai/related-projects': ^0.1.18
  '@neondatabase/serverless': ^1.1.0
  '@noble/ed25519': ^3.1.0
  '@noble/hashes': ^2.2.0
  '@sentry/core': ^10.49.0
  '@sentry/nextjs': ^10.49.0
  '@t3-oss/env-core': ^0.13.11
  '@t3-oss/env-nextjs': ^0.13.11
  '@tanstack/react-query': ^5.99.1
  '@trpc/client': ^11.16.0
  '@trpc/server': ^11.16.0
  '@trpc/tanstack-react-query': ^11.16.0
  '@types/node': ^24.9.1
  '@upstash/redis': ^1.37.0
  '@vercel/related-projects': ^1.0.1
  '@vitest/coverage-v8': ^4.1.4
  '@vitest/expect': ^4.1.4
  ai: 5.0.52
  babel-plugin-react-compiler: ^1.0.0
  clsx: ^2.1.1
  dotenv-cli: ^11.0.0
  drizzle-orm: ^0.45.2
  drizzle-zod: ^0.8.3
  geist: ^1.7.0
  hono: ^4.12.14
  import-in-the-middle: ^3.0.1
  inngest: ^3.54.2
  jose: ^6.2.2
  lucide-react: ^1.8.0
  nanoid: ^5.1.9
  portless: ^0.12.0
  postgres: ^3.4.9
  react-hook-form: ^7.72.1
  require-in-the-middle: ^8.0.1
  superjson: ^2.2.6
  tailwind-merge: ^3.5.0
  typescript: ^5.9.2
  vitest: ^4.1.4
  yaml: ^2.8.3
  zod: ^4.3.6
  zustand: ^5.0.12

catalogs:
  next16:
    next: ^16.2.4
  react19:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.5
    react-dom: ^19.2.5
  tailwind4:
    '@tailwindcss/postcss': 4.2.2
    '@tailwindcss/typography': ^0.5.16
    postcss: 8.5.10
    tailwindcss: 4.2.2

ignoredBuiltDependencies:
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bufferutil
  - core-js
  - core-js-pure
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - protobufjs
  - sharp

packageExtensions:
  '@hookform/resolvers':
    peerDependencies:
      zod: '>=3.24.0'
    peerDependenciesMeta:
      zod:
        optional: true

publicHoistPattern:
  - '*import-in-the-middle*'
  - '*require-in-the-middle*'
