packages:
  - api/*
  - apps/*
  - core/*
  - db/*
  - packages/*
  - internal/*
  - vendor/*
  - examples/*
catalog:
  '@tanstack/react-query': ^5.80.7
  '@trpc/client': ^11.4.0
  '@trpc/tanstack-react-query': ^11.4.0
  '@trpc/server': ^11.4.0
  lucide-react: ^0.451.0
  superjson: ^2.2.1
  '@types/node': ^20.16.11
  '@types/eslint__js': 8.42.3
  zod: ^3.24.0
  eslint: ^9.23.0
  prettier: ^3.5.3
  typescript: ^5.8.2
  typescript-eslint: ^8.46.1
  next: ^15.4.0
  turbo: ^2.5.5
  '@ai-sdk/anthropic': 2.0.4
  '@ai-sdk/gateway': 1.0.7
  '@ai-sdk/provider': 2.0.0
  '@ai-sdk/react': 2.0.15
  ai: 5.0.15
  '@upstash/redis': ^1.35.1
  '@vercel/blob': ^1.1.1
  '@vercel/related-projects': ^1.0.0
  '@vercel/sandbox': ^0.0.13
  redis: ^5.6.0
  braintrust: ^0.2.1
  exa-js: ^1.8.22
  '@browserbasehq/stagehand': ^2.3.1
  '@t3-oss/env-core': ^0.12.0
  '@t3-oss/env-nextjs': ^0.12.0
  resumable-stream: ^2.0.0
  '@clerk/elements': 0.23.63
  '@clerk/nextjs': 6.32.0
  '@clerk/shared': ^3.28.0
  '@clerk/themes': 2.4.19
  '@clerk/types': ^4.52.0
  zustand: ^5.0.7
  geist: ^1.3.1
  neverthrow: ^8.2.0
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  inngest: ^3.35.1
  '@inngest/middleware-sentry': ^0.1.2
  nanoid: ^5.1.5
  drizzle-orm: ^0.43.1
  drizzle-zod: ^0.7.1
  react-hook-form: ^7.61.1
  '@hookform/resolvers': ^3.10.0
catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': 19.1.2
    '@types/react-dom': 19.1.2
  tailwind4:
    tailwindcss: 4.1.11
    postcss: 8.5.6
    '@tailwindcss/postcss': 4.1.11
    '@tailwindcss/typography': ^0.5.16
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@lightfastai/dual'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp
ignoredBuiltDependencies:
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp

linkWorkspacePackages: true

overrides:
  "@types/minimatch": 5.1.2
  # Suppress peer dependency warnings while maintaining compatibility
  # stagehand works fine with dotenv 17.x even though it declares 16.x
  "@browserbasehq/stagehand>dotenv": ^17.2.1
  # zod-to-json-schema works fine with both zod 3.x and 4.x
  "zod-to-json-schema>zod": ^3.24.0

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
  - "*import-in-the-middle*"
  - "*require-in-the-middle*"
