packages:
  - "apps/dahlia/*"
  - "apps/jps0000/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^9.12.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  "@types/node": ^20.16.11
  "@types/eslint": ^8
  zod: ^3.23.8
  next: 14.2.15

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
