packages:
  - "apps/*"
  - "packages/*"
  - "internal/*"
  - "vendor/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  lucide-react: ^0.451.0
  "@types/node": ^20.16.11
  "@types/eslint__js": 8.42.3
  zod: ^3.24.0

  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.2

  next: 15.3.0

catalogs:
  react18:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.2
    "@types/react-dom": 19.1.2
