packages:
  - "apps/*"
  - "packages/*"
  - "internal/*"
  - "vendor/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  lucide-react: ^0.451.0
  "@types/node": ^20.16.11
  "@types/eslint__js": 8.42.3
  zod: ^3.23.8
  next: 14.2.15

  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
