services:
  - type: web
    name: lightfast-media-server
    env: node
    plan: free
    buildCommand: |
      pnpm install
      npm install -g esbuild
      echo "Current directory: $(pwd)"
      echo "Listing media-server directory:"
      ls -la apps/media-server
      echo "Listing media-server/src directory:"
      ls -la apps/media-server/src
      cd apps/media-server
      echo "Running esbuild directly..."
      mkdir -p dist
      npx esbuild src/server.ts --bundle --platform=node --format=esm --outfile=dist/server.js --external:aws-sdk
      echo "Build completed. Checking dist directory:"
      ls -la dist
    startCommand: |
      echo "Current directory: $(pwd)"
      cd apps/media-server
      echo "Media server directory: $(pwd)"
      ls -la dist || echo "dist directory not found or empty"
      if [ -f "dist/server.js" ]; then
        export PORT=10000
        node dist/server.js
      else
        echo "ERROR: dist/server.js file not found after build"
        exit 1
      fi
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      # Add your required environment variables here, or set them in the Render dashboard
