services:
  - type: web
    name: lightfast-media-server
    env: node
    plan: free
    buildCommand: |
      pnpm install
      echo "Creating special build script for media-server..."
      cd apps/media-server
      cat > build.js << 'EOF'
      import { build } from 'esbuild';
      import { fileURLToPath } from 'url';
      import { dirname, join } from 'path';
      import fs from 'fs';

      const __dirname = dirname(fileURLToPath(import.meta.url));

      async function main() {
        try {
          console.log('Starting esbuild...');
          
          // Ensure dist directory exists
          if (!fs.existsSync(join(__dirname, 'dist'))) {
            fs.mkdirSync(join(__dirname, 'dist'), { recursive: true });
          }
          
          // Bundle the server
          const result = await build({
            entryPoints: [join(__dirname, 'src/server.ts')],
            outfile: join(__dirname, 'dist/server.js'),
            bundle: true,
            platform: 'node',
            target: 'node20',
            format: 'esm',
            external: ['aws-sdk'],
            sourcemap: true,
          });
          
          console.log('Build successful:', result);
        } catch (err) {
          console.error('Build failed:', err);
          process.exit(1);
        }
      }

      main();
      EOF

      echo "Installing esbuild..."
      npm install --no-save esbuild

      echo "Running custom build..."
      node build.js

      echo "Built files:"
      ls -la dist
    startCommand: |
      echo "Current directory: $(pwd)"
      cd apps/media-server
      echo "Media server directory: $(pwd)"
      ls -la dist || echo "dist directory not found or empty"
      if [ -f "dist/server.js" ]; then
        node dist/server.js
      else
        echo "ERROR: dist/server.js file not found after build"
        exit 1
      fi
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      # Add your required environment variables here, or set them in the Render dashboard
