services:
  - type: web
    name: lightfast-media-server
    env: node
    plan: free
    buildCommand: pnpm --filter @lightfast/media-server build
    startCommand: pnpm --filter @lightfast/media-server start
    rootDir: apps/media-server
    envVars:
      - key: NODE_ENV
        value: production
      # Add your required environment variables here, or set them in the Render dashboard
