/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CloudflareAuth": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "CloudflareAuthKV": {
      "type": "sst.cloudflare.Kv"
    }
    "POSTGRES_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}