/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpAcceptInvitationRouteImport } from './routes/sign-up_.accept-invitation'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as OauthRevokeRouteImport } from './routes/oauth/revoke'
import { Route as OauthRegisterRouteImport } from './routes/oauth/register'
import { Route as OauthJwksRouteImport } from './routes/oauth/jwks'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as AuthenticatedSlugIndexRouteImport } from './routes/_authenticated/$slug/index'
import { Route as OauthRegisterClientIdRouteImport } from './routes/oauth/register/$clientId'
import { Route as OauthClientStartRouteImport } from './routes/oauth/$client/start'
import { Route as ApiV1SignalsRouteImport } from './routes/api/v1/signals'
import { Route as ApiOauthFinalizeRouteImport } from './routes/api/oauth/finalize'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubSetupRouteImport } from './routes/api/github/setup'
import { Route as ApiDesktopRpcRouteImport } from './routes/api/desktop/rpc'
import { Route as ApiCliRpcRouteImport } from './routes/api/cli/rpc'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account/settings'
import { Route as AuthenticatedAccountMcpRouteImport } from './routes/_authenticated/account/mcp'
import { Route as AuthenticatedSlugTasksRouteImport } from './routes/_authenticated/$slug/tasks'
import { Route as AuthenticatedSlugSkillsRouteImport } from './routes/_authenticated/$slug/skills'
import { Route as AuthenticatedSlugSignalsRouteImport } from './routes/_authenticated/$slug/signals'
import { Route as AuthenticatedSlugSettingsRouteImport } from './routes/_authenticated/$slug/settings'
import { Route as AuthenticatedSlugPeopleRouteImport } from './routes/_authenticated/$slug/people'
import { Route as AuthenticatedSlugDeveloperConnectionsRouteImport } from './routes/_authenticated/$slug/developer-connections'
import { Route as AuthenticatedSlugDecisionsRouteImport } from './routes/_authenticated/$slug/decisions'
import { Route as AuthenticatedSlugConnectorsRouteImport } from './routes/_authenticated/$slug/connectors'
import { Route as AuthenticatedSlugChatRouteImport } from './routes/_authenticated/$slug/chat'
import { Route as AuthenticatedSlugAutomationsRouteImport } from './routes/_authenticated/$slug/automations'
import { Route as AuthenticatedAccountSettingsIndexRouteImport } from './routes/_authenticated/account/settings/index'
import { Route as AuthenticatedSlugTasksIndexRouteImport } from './routes/_authenticated/$slug/tasks/index'
import { Route as AuthenticatedSlugSettingsIndexRouteImport } from './routes/_authenticated/$slug/settings/index'
import { Route as AuthenticatedSlugChatIndexRouteImport } from './routes/_authenticated/$slug/chat/index'
import { Route as AuthenticatedSlugAutomationsIndexRouteImport } from './routes/_authenticated/$slug/automations/index'
import { Route as ApiV1SystemHealthRouteImport } from './routes/api/v1/system/health'
import { Route as ApiV1SignalsIdRouteImport } from './routes/api/v1/signals/$id'
import { Route as ApiSkillsIndexEventsRouteImport } from './routes/api/skills/index/events'
import { Route as ApiOauthDesktopSessionRouteImport } from './routes/api/oauth/desktop/session'
import { Route as ApiOauthClientConfigRouteImport } from './routes/api/oauth/$client/config'
import { Route as ApiInternalMcpSignalsRouteImport } from './routes/api/internal/mcp/signals'
import { Route as ApiInternalMcpAuditRouteImport } from './routes/api/internal/mcp/audit'
import { Route as ApiGithubOauthCallbackRouteImport } from './routes/api/github/oauth/callback'
import { Route as ApiConnectorsXMcpRouteImport } from './routes/api/connectors/x/mcp'
import { Route as ApiChatIdStreamRouteImport } from './routes/api/chat/$id/stream'
import { Route as AuthenticatedAccountsTeamsNewRouteImport } from './routes/_authenticated/accounts/teams/new'
import { Route as AuthenticatedAccountTeamsNewRouteImport } from './routes/_authenticated/account/teams/new'
import { Route as AuthenticatedAccountTasksUsernameRouteImport } from './routes/_authenticated/account/tasks/username'
import { Route as AuthenticatedAccountTasksGithubRouteImport } from './routes/_authenticated/account/tasks/github'
import { Route as AuthenticatedAccountSettingsSourceControlRouteImport } from './routes/_authenticated/account/settings/source-control'
import { Route as AuthenticatedAccountSettingsGeneralRouteImport } from './routes/_authenticated/account/settings/general'
import { Route as AuthenticatedSlugTasksBindRouteImport } from './routes/_authenticated/$slug/tasks/bind'
import { Route as AuthenticatedSlugSettingsSourceControlRouteImport } from './routes/_authenticated/$slug/settings/source-control'
import { Route as AuthenticatedSlugSettingsMembersRouteImport } from './routes/_authenticated/$slug/settings/members'
import { Route as AuthenticatedSlugSettingsMcpRouteImport } from './routes/_authenticated/$slug/settings/mcp'
import { Route as AuthenticatedSlugSettingsGeneralRouteImport } from './routes/_authenticated/$slug/settings/general'
import { Route as AuthenticatedSlugSettingsBillingRouteImport } from './routes/_authenticated/$slug/settings/billing'
import { Route as AuthenticatedSlugSettingsApiKeysRouteImport } from './routes/_authenticated/$slug/settings/api-keys'
import { Route as AuthenticatedSlugChatConversationIdRouteImport } from './routes/_authenticated/$slug/chat/$conversationId'
import { Route as AuthenticatedSlugAutomationsNewRouteImport } from './routes/_authenticated/$slug/automations/new'
import { Route as AuthenticatedSlugAutomationsAutomationRouteImport } from './routes/_authenticated/$slug/automations/$automation'
import { Route as AuthenticatedAccountTasksGithubIndexRouteImport } from './routes/_authenticated/account/tasks/github/index'
import { Route as AuthenticatedSlugTasksBindIndexRouteImport } from './routes/_authenticated/$slug/tasks/bind/index'
import { Route as ApiInternalMcpSignalsGetRouteImport } from './routes/api/internal/mcp/signals/get'
import { Route as ApiInternalMcpProxyFindRouteImport } from './routes/api/internal/mcp/proxy/find'
import { Route as ApiInternalMcpProxyCallRouteImport } from './routes/api/internal/mcp/proxy/call'
import { Route as ApiGithubUserOauthCallbackRouteImport } from './routes/api/github/user/oauth/callback'
import { Route as ApiConnectorsXOauthCallbackRouteImport } from './routes/api/connectors/x/oauth/callback'
import { Route as ApiConnectorsLinearOauthCallbackRouteImport } from './routes/api/connectors/linear/oauth/callback'
import { Route as ApiConnectorsGranolaOauthCallbackRouteImport } from './routes/api/connectors/granola/oauth/callback'
import { Route as AuthenticatedAccountTasksGithubCompleteRouteImport } from './routes/_authenticated/account/tasks/github/complete'
import { Route as AuthenticatedSlugTasksGithubLightfastRepoRouteImport } from './routes/_authenticated/$slug/tasks/github/lightfast-repo'
import { Route as AuthenticatedSlugTasksConnectorsXRouteImport } from './routes/_authenticated/$slug/tasks/connectors/x'
import { Route as AuthenticatedSlugTasksConnectorsXIndexRouteImport } from './routes/_authenticated/$slug/tasks/connectors/x/index'
import { Route as AuthenticatedSlugTasksConnectorsXCompleteRouteImport } from './routes/_authenticated/$slug/tasks/connectors/x/complete'
import { Route as AuthenticatedSlugTasksBindGithubCompleteRouteImport } from './routes/_authenticated/$slug/tasks/bind/github/complete'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpAcceptInvitationRoute = SignUpAcceptInvitationRouteImport.update({
  id: '/sign-up_/accept-invitation',
  path: '/sign-up/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRevokeRoute = OauthRevokeRouteImport.update({
  id: '/oauth/revoke',
  path: '/oauth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRegisterRoute = OauthRegisterRouteImport.update({
  id: '/oauth/register',
  path: '/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthJwksRoute = OauthJwksRouteImport.update({
  id: '/oauth/jwks',
  path: '/oauth/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSlugIndexRoute = AuthenticatedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const OauthRegisterClientIdRoute = OauthRegisterClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => OauthRegisterRoute,
} as any)
const OauthClientStartRoute = OauthClientStartRouteImport.update({
  id: '/oauth/$client/start',
  path: '/oauth/$client/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SignalsRoute = ApiV1SignalsRouteImport.update({
  id: '/api/v1/signals',
  path: '/api/v1/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthFinalizeRoute = ApiOauthFinalizeRouteImport.update({
  id: '/api/oauth/finalize',
  path: '/api/oauth/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopRpcRoute = ApiDesktopRpcRouteImport.update({
  id: '/api/desktop/rpc',
  path: '/api/desktop/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliRpcRoute = ApiCliRpcRouteImport.update({
  id: '/api/cli/rpc',
  path: '/api/cli/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountMcpRoute = AuthenticatedAccountMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedAccountRoute,
} as any)
const AuthenticatedSlugTasksRoute = AuthenticatedSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugSkillsRoute = AuthenticatedSlugSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugSignalsRoute =
  AuthenticatedSlugSignalsRouteImport.update({
    id: '/signals',
    path: '/signals',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsRoute =
  AuthenticatedSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugPeopleRoute = AuthenticatedSlugPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugDeveloperConnectionsRoute =
  AuthenticatedSlugDeveloperConnectionsRouteImport.update({
    id: '/developer-connections',
    path: '/developer-connections',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDecisionsRoute =
  AuthenticatedSlugDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugConnectorsRoute =
  AuthenticatedSlugConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugChatRoute = AuthenticatedSlugChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugAutomationsRoute =
  AuthenticatedSlugAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedAccountSettingsIndexRoute =
  AuthenticatedAccountSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountSettingsRoute,
  } as any)
const AuthenticatedSlugTasksIndexRoute =
  AuthenticatedSlugTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugTasksRoute,
  } as any)
const AuthenticatedSlugSettingsIndexRoute =
  AuthenticatedSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugSettingsRoute,
  } as any)
const AuthenticatedSlugChatIndexRoute =
  AuthenticatedSlugChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugChatRoute,
  } as any)
const AuthenticatedSlugAutomationsIndexRoute =
  AuthenticatedSlugAutomationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugAutomationsRoute,
  } as any)
const ApiV1SystemHealthRoute = ApiV1SystemHealthRouteImport.update({
  id: '/api/v1/system/health',
  path: '/api/v1/system/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SignalsIdRoute = ApiV1SignalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1SignalsRoute,
} as any)
const ApiSkillsIndexEventsRoute = ApiSkillsIndexEventsRouteImport.update({
  id: '/api/skills/index/events',
  path: '/api/skills/index/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthDesktopSessionRoute = ApiOauthDesktopSessionRouteImport.update({
  id: '/api/oauth/desktop/session',
  path: '/api/oauth/desktop/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthClientConfigRoute = ApiOauthClientConfigRouteImport.update({
  id: '/api/oauth/$client/config',
  path: '/api/oauth/$client/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMcpSignalsRoute = ApiInternalMcpSignalsRouteImport.update({
  id: '/api/internal/mcp/signals',
  path: '/api/internal/mcp/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMcpAuditRoute = ApiInternalMcpAuditRouteImport.update({
  id: '/api/internal/mcp/audit',
  path: '/api/internal/mcp/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubOauthCallbackRoute = ApiGithubOauthCallbackRouteImport.update({
  id: '/api/github/oauth/callback',
  path: '/api/github/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsXMcpRoute = ApiConnectorsXMcpRouteImport.update({
  id: '/api/connectors/x/mcp',
  path: '/api/connectors/x/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIdStreamRoute = ApiChatIdStreamRouteImport.update({
  id: '/$id/stream',
  path: '/$id/stream',
  getParentRoute: () => ApiChatRoute,
} as any)
const AuthenticatedAccountsTeamsNewRoute =
  AuthenticatedAccountsTeamsNewRouteImport.update({
    id: '/accounts/teams/new',
    path: '/accounts/teams/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountTeamsNewRoute =
  AuthenticatedAccountTeamsNewRouteImport.update({
    id: '/teams/new',
    path: '/teams/new',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountTasksUsernameRoute =
  AuthenticatedAccountTasksUsernameRouteImport.update({
    id: '/tasks/username',
    path: '/tasks/username',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountTasksGithubRoute =
  AuthenticatedAccountTasksGithubRouteImport.update({
    id: '/tasks/github',
    path: '/tasks/github',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountSettingsSourceControlRoute =
  AuthenticatedAccountSettingsSourceControlRouteImport.update({
    id: '/source-control',
    path: '/source-control',
    getParentRoute: () => AuthenticatedAccountSettingsRoute,
  } as any)
const AuthenticatedAccountSettingsGeneralRoute =
  AuthenticatedAccountSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedAccountSettingsRoute,
  } as any)
const AuthenticatedSlugTasksBindRoute =
  AuthenticatedSlugTasksBindRouteImport.update({
    id: '/bind',
    path: '/bind',
    getParentRoute: () => AuthenticatedSlugTasksRoute,
  } as any)
const AuthenticatedSlugSettingsSourceControlRoute =
  AuthenticatedSlugSettingsSourceControlRouteImport.update({
    id: '/source-control',
    path: '/source-control',
    getParentRoute: () => AuthenticatedSlugSettingsRoute,
  } as any)
const AuthenticatedSlugSettingsMembersRoute =
  AuthenticatedSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSlugSettingsRoute,
  } as any)
const AuthenticatedSlugSettingsMcpRoute =
  AuthenticatedSlugSettingsMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => AuthenticatedSlugSettingsRoute,
  } as any)
const AuthenticatedSlugSettingsGeneralRoute =
  AuthenticatedSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSlugSettingsRoute,
  } as any)
const AuthenticatedSlugSettingsBillingRoute =
  AuthenticatedSlugSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSlugSettingsRoute,
  } as any)
const AuthenticatedSlugSettingsApiKeysRoute =
  AuthenticatedSlugSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSlugSettingsRoute,
  } as any)
const AuthenticatedSlugChatConversationIdRoute =
  AuthenticatedSlugChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedSlugChatRoute,
  } as any)
const AuthenticatedSlugAutomationsNewRoute =
  AuthenticatedSlugAutomationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugAutomationsRoute,
  } as any)
const AuthenticatedSlugAutomationsAutomationRoute =
  AuthenticatedSlugAutomationsAutomationRouteImport.update({
    id: '/$automation',
    path: '/$automation',
    getParentRoute: () => AuthenticatedSlugAutomationsRoute,
  } as any)
const AuthenticatedAccountTasksGithubIndexRoute =
  AuthenticatedAccountTasksGithubIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountTasksGithubRoute,
  } as any)
const AuthenticatedSlugTasksBindIndexRoute =
  AuthenticatedSlugTasksBindIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugTasksBindRoute,
  } as any)
const ApiInternalMcpSignalsGetRoute =
  ApiInternalMcpSignalsGetRouteImport.update({
    id: '/get',
    path: '/get',
    getParentRoute: () => ApiInternalMcpSignalsRoute,
  } as any)
const ApiInternalMcpProxyFindRoute = ApiInternalMcpProxyFindRouteImport.update({
  id: '/api/internal/mcp/proxy/find',
  path: '/api/internal/mcp/proxy/find',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMcpProxyCallRoute = ApiInternalMcpProxyCallRouteImport.update({
  id: '/api/internal/mcp/proxy/call',
  path: '/api/internal/mcp/proxy/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubUserOauthCallbackRoute =
  ApiGithubUserOauthCallbackRouteImport.update({
    id: '/api/github/user/oauth/callback',
    path: '/api/github/user/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectorsXOauthCallbackRoute =
  ApiConnectorsXOauthCallbackRouteImport.update({
    id: '/api/connectors/x/oauth/callback',
    path: '/api/connectors/x/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectorsLinearOauthCallbackRoute =
  ApiConnectorsLinearOauthCallbackRouteImport.update({
    id: '/api/connectors/linear/oauth/callback',
    path: '/api/connectors/linear/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectorsGranolaOauthCallbackRoute =
  ApiConnectorsGranolaOauthCallbackRouteImport.update({
    id: '/api/connectors/granola/oauth/callback',
    path: '/api/connectors/granola/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountTasksGithubCompleteRoute =
  AuthenticatedAccountTasksGithubCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AuthenticatedAccountTasksGithubRoute,
  } as any)
const AuthenticatedSlugTasksGithubLightfastRepoRoute =
  AuthenticatedSlugTasksGithubLightfastRepoRouteImport.update({
    id: '/github/lightfast-repo',
    path: '/github/lightfast-repo',
    getParentRoute: () => AuthenticatedSlugTasksRoute,
  } as any)
const AuthenticatedSlugTasksConnectorsXRoute =
  AuthenticatedSlugTasksConnectorsXRouteImport.update({
    id: '/connectors/x',
    path: '/connectors/x',
    getParentRoute: () => AuthenticatedSlugTasksRoute,
  } as any)
const AuthenticatedSlugTasksConnectorsXIndexRoute =
  AuthenticatedSlugTasksConnectorsXIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugTasksConnectorsXRoute,
  } as any)
const AuthenticatedSlugTasksConnectorsXCompleteRoute =
  AuthenticatedSlugTasksConnectorsXCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AuthenticatedSlugTasksConnectorsXRoute,
  } as any)
const AuthenticatedSlugTasksBindGithubCompleteRoute =
  AuthenticatedSlugTasksBindGithubCompleteRouteImport.update({
    id: '/github/complete',
    path: '/github/complete',
    getParentRoute: () => AuthenticatedSlugTasksBindRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/inngest': typeof ApiInngestRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/register': typeof OauthRegisterRouteWithChildren
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/sign-up/accept-invitation': typeof SignUpAcceptInvitationRoute
  '/$slug/automations': typeof AuthenticatedSlugAutomationsRouteWithChildren
  '/$slug/chat': typeof AuthenticatedSlugChatRouteWithChildren
  '/$slug/connectors': typeof AuthenticatedSlugConnectorsRoute
  '/$slug/decisions': typeof AuthenticatedSlugDecisionsRoute
  '/$slug/developer-connections': typeof AuthenticatedSlugDeveloperConnectionsRoute
  '/$slug/people': typeof AuthenticatedSlugPeopleRoute
  '/$slug/settings': typeof AuthenticatedSlugSettingsRouteWithChildren
  '/$slug/signals': typeof AuthenticatedSlugSignalsRoute
  '/$slug/skills': typeof AuthenticatedSlugSkillsRoute
  '/$slug/tasks': typeof AuthenticatedSlugTasksRouteWithChildren
  '/account/mcp': typeof AuthenticatedAccountMcpRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRouteWithChildren
  '/api/cli/rpc': typeof ApiCliRpcRoute
  '/api/desktop/rpc': typeof ApiDesktopRpcRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/finalize': typeof ApiOauthFinalizeRoute
  '/api/v1/signals': typeof ApiV1SignalsRouteWithChildren
  '/oauth/$client/start': typeof OauthClientStartRoute
  '/oauth/register/$clientId': typeof OauthRegisterClientIdRoute
  '/$slug/': typeof AuthenticatedSlugIndexRoute
  '/$slug/automations/$automation': typeof AuthenticatedSlugAutomationsAutomationRoute
  '/$slug/automations/new': typeof AuthenticatedSlugAutomationsNewRoute
  '/$slug/chat/$conversationId': typeof AuthenticatedSlugChatConversationIdRoute
  '/$slug/settings/api-keys': typeof AuthenticatedSlugSettingsApiKeysRoute
  '/$slug/settings/billing': typeof AuthenticatedSlugSettingsBillingRoute
  '/$slug/settings/general': typeof AuthenticatedSlugSettingsGeneralRoute
  '/$slug/settings/mcp': typeof AuthenticatedSlugSettingsMcpRoute
  '/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/$slug/settings/source-control': typeof AuthenticatedSlugSettingsSourceControlRoute
  '/$slug/tasks/bind': typeof AuthenticatedSlugTasksBindRouteWithChildren
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRoute
  '/account/settings/source-control': typeof AuthenticatedAccountSettingsSourceControlRoute
  '/account/tasks/github': typeof AuthenticatedAccountTasksGithubRouteWithChildren
  '/account/tasks/username': typeof AuthenticatedAccountTasksUsernameRoute
  '/account/teams/new': typeof AuthenticatedAccountTeamsNewRoute
  '/accounts/teams/new': typeof AuthenticatedAccountsTeamsNewRoute
  '/api/chat/$id/stream': typeof ApiChatIdStreamRoute
  '/api/connectors/x/mcp': typeof ApiConnectorsXMcpRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/api/internal/mcp/audit': typeof ApiInternalMcpAuditRoute
  '/api/internal/mcp/signals': typeof ApiInternalMcpSignalsRouteWithChildren
  '/api/oauth/$client/config': typeof ApiOauthClientConfigRoute
  '/api/oauth/desktop/session': typeof ApiOauthDesktopSessionRoute
  '/api/skills/index/events': typeof ApiSkillsIndexEventsRoute
  '/api/v1/signals/$id': typeof ApiV1SignalsIdRoute
  '/api/v1/system/health': typeof ApiV1SystemHealthRoute
  '/$slug/automations/': typeof AuthenticatedSlugAutomationsIndexRoute
  '/$slug/chat/': typeof AuthenticatedSlugChatIndexRoute
  '/$slug/settings/': typeof AuthenticatedSlugSettingsIndexRoute
  '/$slug/tasks/': typeof AuthenticatedSlugTasksIndexRoute
  '/account/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/$slug/tasks/connectors/x': typeof AuthenticatedSlugTasksConnectorsXRouteWithChildren
  '/$slug/tasks/github/lightfast-repo': typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
  '/account/tasks/github/complete': typeof AuthenticatedAccountTasksGithubCompleteRoute
  '/api/connectors/granola/oauth/callback': typeof ApiConnectorsGranolaOauthCallbackRoute
  '/api/connectors/linear/oauth/callback': typeof ApiConnectorsLinearOauthCallbackRoute
  '/api/connectors/x/oauth/callback': typeof ApiConnectorsXOauthCallbackRoute
  '/api/github/user/oauth/callback': typeof ApiGithubUserOauthCallbackRoute
  '/api/internal/mcp/proxy/call': typeof ApiInternalMcpProxyCallRoute
  '/api/internal/mcp/proxy/find': typeof ApiInternalMcpProxyFindRoute
  '/api/internal/mcp/signals/get': typeof ApiInternalMcpSignalsGetRoute
  '/$slug/tasks/bind/': typeof AuthenticatedSlugTasksBindIndexRoute
  '/account/tasks/github/': typeof AuthenticatedAccountTasksGithubIndexRoute
  '/$slug/tasks/bind/github/complete': typeof AuthenticatedSlugTasksBindGithubCompleteRoute
  '/$slug/tasks/connectors/x/complete': typeof AuthenticatedSlugTasksConnectorsXCompleteRoute
  '/$slug/tasks/connectors/x/': typeof AuthenticatedSlugTasksConnectorsXIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/inngest': typeof ApiInngestRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/register': typeof OauthRegisterRouteWithChildren
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/sign-up/accept-invitation': typeof SignUpAcceptInvitationRoute
  '/$slug/connectors': typeof AuthenticatedSlugConnectorsRoute
  '/$slug/decisions': typeof AuthenticatedSlugDecisionsRoute
  '/$slug/developer-connections': typeof AuthenticatedSlugDeveloperConnectionsRoute
  '/$slug/people': typeof AuthenticatedSlugPeopleRoute
  '/$slug/signals': typeof AuthenticatedSlugSignalsRoute
  '/$slug/skills': typeof AuthenticatedSlugSkillsRoute
  '/account/mcp': typeof AuthenticatedAccountMcpRoute
  '/api/cli/rpc': typeof ApiCliRpcRoute
  '/api/desktop/rpc': typeof ApiDesktopRpcRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/finalize': typeof ApiOauthFinalizeRoute
  '/api/v1/signals': typeof ApiV1SignalsRouteWithChildren
  '/oauth/$client/start': typeof OauthClientStartRoute
  '/oauth/register/$clientId': typeof OauthRegisterClientIdRoute
  '/$slug': typeof AuthenticatedSlugIndexRoute
  '/$slug/automations/$automation': typeof AuthenticatedSlugAutomationsAutomationRoute
  '/$slug/automations/new': typeof AuthenticatedSlugAutomationsNewRoute
  '/$slug/chat/$conversationId': typeof AuthenticatedSlugChatConversationIdRoute
  '/$slug/settings/api-keys': typeof AuthenticatedSlugSettingsApiKeysRoute
  '/$slug/settings/billing': typeof AuthenticatedSlugSettingsBillingRoute
  '/$slug/settings/general': typeof AuthenticatedSlugSettingsGeneralRoute
  '/$slug/settings/mcp': typeof AuthenticatedSlugSettingsMcpRoute
  '/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/$slug/settings/source-control': typeof AuthenticatedSlugSettingsSourceControlRoute
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRoute
  '/account/settings/source-control': typeof AuthenticatedAccountSettingsSourceControlRoute
  '/account/tasks/username': typeof AuthenticatedAccountTasksUsernameRoute
  '/account/teams/new': typeof AuthenticatedAccountTeamsNewRoute
  '/accounts/teams/new': typeof AuthenticatedAccountsTeamsNewRoute
  '/api/chat/$id/stream': typeof ApiChatIdStreamRoute
  '/api/connectors/x/mcp': typeof ApiConnectorsXMcpRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/api/internal/mcp/audit': typeof ApiInternalMcpAuditRoute
  '/api/internal/mcp/signals': typeof ApiInternalMcpSignalsRouteWithChildren
  '/api/oauth/$client/config': typeof ApiOauthClientConfigRoute
  '/api/oauth/desktop/session': typeof ApiOauthDesktopSessionRoute
  '/api/skills/index/events': typeof ApiSkillsIndexEventsRoute
  '/api/v1/signals/$id': typeof ApiV1SignalsIdRoute
  '/api/v1/system/health': typeof ApiV1SystemHealthRoute
  '/$slug/automations': typeof AuthenticatedSlugAutomationsIndexRoute
  '/$slug/chat': typeof AuthenticatedSlugChatIndexRoute
  '/$slug/settings': typeof AuthenticatedSlugSettingsIndexRoute
  '/$slug/tasks': typeof AuthenticatedSlugTasksIndexRoute
  '/account/settings': typeof AuthenticatedAccountSettingsIndexRoute
  '/$slug/tasks/github/lightfast-repo': typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
  '/account/tasks/github/complete': typeof AuthenticatedAccountTasksGithubCompleteRoute
  '/api/connectors/granola/oauth/callback': typeof ApiConnectorsGranolaOauthCallbackRoute
  '/api/connectors/linear/oauth/callback': typeof ApiConnectorsLinearOauthCallbackRoute
  '/api/connectors/x/oauth/callback': typeof ApiConnectorsXOauthCallbackRoute
  '/api/github/user/oauth/callback': typeof ApiGithubUserOauthCallbackRoute
  '/api/internal/mcp/proxy/call': typeof ApiInternalMcpProxyCallRoute
  '/api/internal/mcp/proxy/find': typeof ApiInternalMcpProxyFindRoute
  '/api/internal/mcp/signals/get': typeof ApiInternalMcpSignalsGetRoute
  '/$slug/tasks/bind': typeof AuthenticatedSlugTasksBindIndexRoute
  '/account/tasks/github': typeof AuthenticatedAccountTasksGithubIndexRoute
  '/$slug/tasks/bind/github/complete': typeof AuthenticatedSlugTasksBindGithubCompleteRoute
  '/$slug/tasks/connectors/x/complete': typeof AuthenticatedSlugTasksConnectorsXCompleteRoute
  '/$slug/tasks/connectors/x': typeof AuthenticatedSlugTasksConnectorsXIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/inngest': typeof ApiInngestRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/register': typeof OauthRegisterRouteWithChildren
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/sign-up_/accept-invitation': typeof SignUpAcceptInvitationRoute
  '/_authenticated/$slug/automations': typeof AuthenticatedSlugAutomationsRouteWithChildren
  '/_authenticated/$slug/chat': typeof AuthenticatedSlugChatRouteWithChildren
  '/_authenticated/$slug/connectors': typeof AuthenticatedSlugConnectorsRoute
  '/_authenticated/$slug/decisions': typeof AuthenticatedSlugDecisionsRoute
  '/_authenticated/$slug/developer-connections': typeof AuthenticatedSlugDeveloperConnectionsRoute
  '/_authenticated/$slug/people': typeof AuthenticatedSlugPeopleRoute
  '/_authenticated/$slug/settings': typeof AuthenticatedSlugSettingsRouteWithChildren
  '/_authenticated/$slug/signals': typeof AuthenticatedSlugSignalsRoute
  '/_authenticated/$slug/skills': typeof AuthenticatedSlugSkillsRoute
  '/_authenticated/$slug/tasks': typeof AuthenticatedSlugTasksRouteWithChildren
  '/_authenticated/account/mcp': typeof AuthenticatedAccountMcpRoute
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRouteWithChildren
  '/api/cli/rpc': typeof ApiCliRpcRoute
  '/api/desktop/rpc': typeof ApiDesktopRpcRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/finalize': typeof ApiOauthFinalizeRoute
  '/api/v1/signals': typeof ApiV1SignalsRouteWithChildren
  '/oauth/$client/start': typeof OauthClientStartRoute
  '/oauth/register/$clientId': typeof OauthRegisterClientIdRoute
  '/_authenticated/$slug/': typeof AuthenticatedSlugIndexRoute
  '/_authenticated/$slug/automations/$automation': typeof AuthenticatedSlugAutomationsAutomationRoute
  '/_authenticated/$slug/automations/new': typeof AuthenticatedSlugAutomationsNewRoute
  '/_authenticated/$slug/chat/$conversationId': typeof AuthenticatedSlugChatConversationIdRoute
  '/_authenticated/$slug/settings/api-keys': typeof AuthenticatedSlugSettingsApiKeysRoute
  '/_authenticated/$slug/settings/billing': typeof AuthenticatedSlugSettingsBillingRoute
  '/_authenticated/$slug/settings/general': typeof AuthenticatedSlugSettingsGeneralRoute
  '/_authenticated/$slug/settings/mcp': typeof AuthenticatedSlugSettingsMcpRoute
  '/_authenticated/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/_authenticated/$slug/settings/source-control': typeof AuthenticatedSlugSettingsSourceControlRoute
  '/_authenticated/$slug/tasks/bind': typeof AuthenticatedSlugTasksBindRouteWithChildren
  '/_authenticated/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRoute
  '/_authenticated/account/settings/source-control': typeof AuthenticatedAccountSettingsSourceControlRoute
  '/_authenticated/account/tasks/github': typeof AuthenticatedAccountTasksGithubRouteWithChildren
  '/_authenticated/account/tasks/username': typeof AuthenticatedAccountTasksUsernameRoute
  '/_authenticated/account/teams/new': typeof AuthenticatedAccountTeamsNewRoute
  '/_authenticated/accounts/teams/new': typeof AuthenticatedAccountsTeamsNewRoute
  '/api/chat/$id/stream': typeof ApiChatIdStreamRoute
  '/api/connectors/x/mcp': typeof ApiConnectorsXMcpRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/api/internal/mcp/audit': typeof ApiInternalMcpAuditRoute
  '/api/internal/mcp/signals': typeof ApiInternalMcpSignalsRouteWithChildren
  '/api/oauth/$client/config': typeof ApiOauthClientConfigRoute
  '/api/oauth/desktop/session': typeof ApiOauthDesktopSessionRoute
  '/api/skills/index/events': typeof ApiSkillsIndexEventsRoute
  '/api/v1/signals/$id': typeof ApiV1SignalsIdRoute
  '/api/v1/system/health': typeof ApiV1SystemHealthRoute
  '/_authenticated/$slug/automations/': typeof AuthenticatedSlugAutomationsIndexRoute
  '/_authenticated/$slug/chat/': typeof AuthenticatedSlugChatIndexRoute
  '/_authenticated/$slug/settings/': typeof AuthenticatedSlugSettingsIndexRoute
  '/_authenticated/$slug/tasks/': typeof AuthenticatedSlugTasksIndexRoute
  '/_authenticated/account/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/_authenticated/$slug/tasks/connectors/x': typeof AuthenticatedSlugTasksConnectorsXRouteWithChildren
  '/_authenticated/$slug/tasks/github/lightfast-repo': typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
  '/_authenticated/account/tasks/github/complete': typeof AuthenticatedAccountTasksGithubCompleteRoute
  '/api/connectors/granola/oauth/callback': typeof ApiConnectorsGranolaOauthCallbackRoute
  '/api/connectors/linear/oauth/callback': typeof ApiConnectorsLinearOauthCallbackRoute
  '/api/connectors/x/oauth/callback': typeof ApiConnectorsXOauthCallbackRoute
  '/api/github/user/oauth/callback': typeof ApiGithubUserOauthCallbackRoute
  '/api/internal/mcp/proxy/call': typeof ApiInternalMcpProxyCallRoute
  '/api/internal/mcp/proxy/find': typeof ApiInternalMcpProxyFindRoute
  '/api/internal/mcp/signals/get': typeof ApiInternalMcpSignalsGetRoute
  '/_authenticated/$slug/tasks/bind/': typeof AuthenticatedSlugTasksBindIndexRoute
  '/_authenticated/account/tasks/github/': typeof AuthenticatedAccountTasksGithubIndexRoute
  '/_authenticated/$slug/tasks/bind/github/complete': typeof AuthenticatedSlugTasksBindGithubCompleteRoute
  '/_authenticated/$slug/tasks/connectors/x/complete': typeof AuthenticatedSlugTasksConnectorsXCompleteRoute
  '/_authenticated/$slug/tasks/connectors/x/': typeof AuthenticatedSlugTasksConnectorsXIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/.well-known/oauth-authorization-server'
    | '/$slug'
    | '/account'
    | '/api/chat'
    | '/api/health'
    | '/api/inngest'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/register'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/sign-up/accept-invitation'
    | '/$slug/automations'
    | '/$slug/chat'
    | '/$slug/connectors'
    | '/$slug/decisions'
    | '/$slug/developer-connections'
    | '/$slug/people'
    | '/$slug/settings'
    | '/$slug/signals'
    | '/$slug/skills'
    | '/$slug/tasks'
    | '/account/mcp'
    | '/account/settings'
    | '/api/cli/rpc'
    | '/api/desktop/rpc'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/oauth/finalize'
    | '/api/v1/signals'
    | '/oauth/$client/start'
    | '/oauth/register/$clientId'
    | '/$slug/'
    | '/$slug/automations/$automation'
    | '/$slug/automations/new'
    | '/$slug/chat/$conversationId'
    | '/$slug/settings/api-keys'
    | '/$slug/settings/billing'
    | '/$slug/settings/general'
    | '/$slug/settings/mcp'
    | '/$slug/settings/members'
    | '/$slug/settings/source-control'
    | '/$slug/tasks/bind'
    | '/account/settings/general'
    | '/account/settings/source-control'
    | '/account/tasks/github'
    | '/account/tasks/username'
    | '/account/teams/new'
    | '/accounts/teams/new'
    | '/api/chat/$id/stream'
    | '/api/connectors/x/mcp'
    | '/api/github/oauth/callback'
    | '/api/internal/mcp/audit'
    | '/api/internal/mcp/signals'
    | '/api/oauth/$client/config'
    | '/api/oauth/desktop/session'
    | '/api/skills/index/events'
    | '/api/v1/signals/$id'
    | '/api/v1/system/health'
    | '/$slug/automations/'
    | '/$slug/chat/'
    | '/$slug/settings/'
    | '/$slug/tasks/'
    | '/account/settings/'
    | '/$slug/tasks/connectors/x'
    | '/$slug/tasks/github/lightfast-repo'
    | '/account/tasks/github/complete'
    | '/api/connectors/granola/oauth/callback'
    | '/api/connectors/linear/oauth/callback'
    | '/api/connectors/x/oauth/callback'
    | '/api/github/user/oauth/callback'
    | '/api/internal/mcp/proxy/call'
    | '/api/internal/mcp/proxy/find'
    | '/api/internal/mcp/signals/get'
    | '/$slug/tasks/bind/'
    | '/account/tasks/github/'
    | '/$slug/tasks/bind/github/complete'
    | '/$slug/tasks/connectors/x/complete'
    | '/$slug/tasks/connectors/x/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/.well-known/oauth-authorization-server'
    | '/account'
    | '/api/chat'
    | '/api/health'
    | '/api/inngest'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/register'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/sign-up/accept-invitation'
    | '/$slug/connectors'
    | '/$slug/decisions'
    | '/$slug/developer-connections'
    | '/$slug/people'
    | '/$slug/signals'
    | '/$slug/skills'
    | '/account/mcp'
    | '/api/cli/rpc'
    | '/api/desktop/rpc'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/oauth/finalize'
    | '/api/v1/signals'
    | '/oauth/$client/start'
    | '/oauth/register/$clientId'
    | '/$slug'
    | '/$slug/automations/$automation'
    | '/$slug/automations/new'
    | '/$slug/chat/$conversationId'
    | '/$slug/settings/api-keys'
    | '/$slug/settings/billing'
    | '/$slug/settings/general'
    | '/$slug/settings/mcp'
    | '/$slug/settings/members'
    | '/$slug/settings/source-control'
    | '/account/settings/general'
    | '/account/settings/source-control'
    | '/account/tasks/username'
    | '/account/teams/new'
    | '/accounts/teams/new'
    | '/api/chat/$id/stream'
    | '/api/connectors/x/mcp'
    | '/api/github/oauth/callback'
    | '/api/internal/mcp/audit'
    | '/api/internal/mcp/signals'
    | '/api/oauth/$client/config'
    | '/api/oauth/desktop/session'
    | '/api/skills/index/events'
    | '/api/v1/signals/$id'
    | '/api/v1/system/health'
    | '/$slug/automations'
    | '/$slug/chat'
    | '/$slug/settings'
    | '/$slug/tasks'
    | '/account/settings'
    | '/$slug/tasks/github/lightfast-repo'
    | '/account/tasks/github/complete'
    | '/api/connectors/granola/oauth/callback'
    | '/api/connectors/linear/oauth/callback'
    | '/api/connectors/x/oauth/callback'
    | '/api/github/user/oauth/callback'
    | '/api/internal/mcp/proxy/call'
    | '/api/internal/mcp/proxy/find'
    | '/api/internal/mcp/signals/get'
    | '/$slug/tasks/bind'
    | '/account/tasks/github'
    | '/$slug/tasks/bind/github/complete'
    | '/$slug/tasks/connectors/x/complete'
    | '/$slug/tasks/connectors/x'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/.well-known/oauth-authorization-server'
    | '/_authenticated/$slug'
    | '/_authenticated/account'
    | '/api/chat'
    | '/api/health'
    | '/api/inngest'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/register'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/sign-up_/accept-invitation'
    | '/_authenticated/$slug/automations'
    | '/_authenticated/$slug/chat'
    | '/_authenticated/$slug/connectors'
    | '/_authenticated/$slug/decisions'
    | '/_authenticated/$slug/developer-connections'
    | '/_authenticated/$slug/people'
    | '/_authenticated/$slug/settings'
    | '/_authenticated/$slug/signals'
    | '/_authenticated/$slug/skills'
    | '/_authenticated/$slug/tasks'
    | '/_authenticated/account/mcp'
    | '/_authenticated/account/settings'
    | '/api/cli/rpc'
    | '/api/desktop/rpc'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/oauth/finalize'
    | '/api/v1/signals'
    | '/oauth/$client/start'
    | '/oauth/register/$clientId'
    | '/_authenticated/$slug/'
    | '/_authenticated/$slug/automations/$automation'
    | '/_authenticated/$slug/automations/new'
    | '/_authenticated/$slug/chat/$conversationId'
    | '/_authenticated/$slug/settings/api-keys'
    | '/_authenticated/$slug/settings/billing'
    | '/_authenticated/$slug/settings/general'
    | '/_authenticated/$slug/settings/mcp'
    | '/_authenticated/$slug/settings/members'
    | '/_authenticated/$slug/settings/source-control'
    | '/_authenticated/$slug/tasks/bind'
    | '/_authenticated/account/settings/general'
    | '/_authenticated/account/settings/source-control'
    | '/_authenticated/account/tasks/github'
    | '/_authenticated/account/tasks/username'
    | '/_authenticated/account/teams/new'
    | '/_authenticated/accounts/teams/new'
    | '/api/chat/$id/stream'
    | '/api/connectors/x/mcp'
    | '/api/github/oauth/callback'
    | '/api/internal/mcp/audit'
    | '/api/internal/mcp/signals'
    | '/api/oauth/$client/config'
    | '/api/oauth/desktop/session'
    | '/api/skills/index/events'
    | '/api/v1/signals/$id'
    | '/api/v1/system/health'
    | '/_authenticated/$slug/automations/'
    | '/_authenticated/$slug/chat/'
    | '/_authenticated/$slug/settings/'
    | '/_authenticated/$slug/tasks/'
    | '/_authenticated/account/settings/'
    | '/_authenticated/$slug/tasks/connectors/x'
    | '/_authenticated/$slug/tasks/github/lightfast-repo'
    | '/_authenticated/account/tasks/github/complete'
    | '/api/connectors/granola/oauth/callback'
    | '/api/connectors/linear/oauth/callback'
    | '/api/connectors/x/oauth/callback'
    | '/api/github/user/oauth/callback'
    | '/api/internal/mcp/proxy/call'
    | '/api/internal/mcp/proxy/find'
    | '/api/internal/mcp/signals/get'
    | '/_authenticated/$slug/tasks/bind/'
    | '/_authenticated/account/tasks/github/'
    | '/_authenticated/$slug/tasks/bind/github/complete'
    | '/_authenticated/$slug/tasks/connectors/x/complete'
    | '/_authenticated/$slug/tasks/connectors/x/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInngestRoute: typeof ApiInngestRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthJwksRoute: typeof OauthJwksRoute
  OauthRegisterRoute: typeof OauthRegisterRouteWithChildren
  OauthRevokeRoute: typeof OauthRevokeRoute
  OauthTokenRoute: typeof OauthTokenRoute
  SignUpAcceptInvitationRoute: typeof SignUpAcceptInvitationRoute
  ApiCliRpcRoute: typeof ApiCliRpcRoute
  ApiDesktopRpcRoute: typeof ApiDesktopRpcRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiOauthFinalizeRoute: typeof ApiOauthFinalizeRoute
  ApiV1SignalsRoute: typeof ApiV1SignalsRouteWithChildren
  OauthClientStartRoute: typeof OauthClientStartRoute
  ApiConnectorsXMcpRoute: typeof ApiConnectorsXMcpRoute
  ApiGithubOauthCallbackRoute: typeof ApiGithubOauthCallbackRoute
  ApiInternalMcpAuditRoute: typeof ApiInternalMcpAuditRoute
  ApiInternalMcpSignalsRoute: typeof ApiInternalMcpSignalsRouteWithChildren
  ApiOauthClientConfigRoute: typeof ApiOauthClientConfigRoute
  ApiOauthDesktopSessionRoute: typeof ApiOauthDesktopSessionRoute
  ApiSkillsIndexEventsRoute: typeof ApiSkillsIndexEventsRoute
  ApiV1SystemHealthRoute: typeof ApiV1SystemHealthRoute
  ApiConnectorsGranolaOauthCallbackRoute: typeof ApiConnectorsGranolaOauthCallbackRoute
  ApiConnectorsLinearOauthCallbackRoute: typeof ApiConnectorsLinearOauthCallbackRoute
  ApiConnectorsXOauthCallbackRoute: typeof ApiConnectorsXOauthCallbackRoute
  ApiGithubUserOauthCallbackRoute: typeof ApiGithubUserOauthCallbackRoute
  ApiInternalMcpProxyCallRoute: typeof ApiInternalMcpProxyCallRoute
  ApiInternalMcpProxyFindRoute: typeof ApiInternalMcpProxyFindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up_/accept-invitation': {
      id: '/sign-up_/accept-invitation'
      path: '/sign-up/accept-invitation'
      fullPath: '/sign-up/accept-invitation'
      preLoaderRoute: typeof SignUpAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/revoke': {
      id: '/oauth/revoke'
      path: '/oauth/revoke'
      fullPath: '/oauth/revoke'
      preLoaderRoute: typeof OauthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/register': {
      id: '/oauth/register'
      path: '/oauth/register'
      fullPath: '/oauth/register'
      preLoaderRoute: typeof OauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/jwks': {
      id: '/oauth/jwks'
      path: '/oauth/jwks'
      fullPath: '/oauth/jwks'
      preLoaderRoute: typeof OauthJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug/': {
      id: '/_authenticated/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthenticatedSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/oauth/register/$clientId': {
      id: '/oauth/register/$clientId'
      path: '/$clientId'
      fullPath: '/oauth/register/$clientId'
      preLoaderRoute: typeof OauthRegisterClientIdRouteImport
      parentRoute: typeof OauthRegisterRoute
    }
    '/oauth/$client/start': {
      id: '/oauth/$client/start'
      path: '/oauth/$client/start'
      fullPath: '/oauth/$client/start'
      preLoaderRoute: typeof OauthClientStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/signals': {
      id: '/api/v1/signals'
      path: '/api/v1/signals'
      fullPath: '/api/v1/signals'
      preLoaderRoute: typeof ApiV1SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/finalize': {
      id: '/api/oauth/finalize'
      path: '/api/oauth/finalize'
      fullPath: '/api/oauth/finalize'
      preLoaderRoute: typeof ApiOauthFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop/rpc': {
      id: '/api/desktop/rpc'
      path: '/api/desktop/rpc'
      fullPath: '/api/desktop/rpc'
      preLoaderRoute: typeof ApiDesktopRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/rpc': {
      id: '/api/cli/rpc'
      path: '/api/cli/rpc'
      fullPath: '/api/cli/rpc'
      preLoaderRoute: typeof ApiCliRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/mcp': {
      id: '/_authenticated/account/mcp'
      path: '/mcp'
      fullPath: '/account/mcp'
      preLoaderRoute: typeof AuthenticatedAccountMcpRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/$slug/tasks': {
      id: '/_authenticated/$slug/tasks'
      path: '/tasks'
      fullPath: '/$slug/tasks'
      preLoaderRoute: typeof AuthenticatedSlugTasksRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/skills': {
      id: '/_authenticated/$slug/skills'
      path: '/skills'
      fullPath: '/$slug/skills'
      preLoaderRoute: typeof AuthenticatedSlugSkillsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/signals': {
      id: '/_authenticated/$slug/signals'
      path: '/signals'
      fullPath: '/$slug/signals'
      preLoaderRoute: typeof AuthenticatedSlugSignalsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings': {
      id: '/_authenticated/$slug/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof AuthenticatedSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/people': {
      id: '/_authenticated/$slug/people'
      path: '/people'
      fullPath: '/$slug/people'
      preLoaderRoute: typeof AuthenticatedSlugPeopleRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/developer-connections': {
      id: '/_authenticated/$slug/developer-connections'
      path: '/developer-connections'
      fullPath: '/$slug/developer-connections'
      preLoaderRoute: typeof AuthenticatedSlugDeveloperConnectionsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/decisions': {
      id: '/_authenticated/$slug/decisions'
      path: '/decisions'
      fullPath: '/$slug/decisions'
      preLoaderRoute: typeof AuthenticatedSlugDecisionsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/connectors': {
      id: '/_authenticated/$slug/connectors'
      path: '/connectors'
      fullPath: '/$slug/connectors'
      preLoaderRoute: typeof AuthenticatedSlugConnectorsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/chat': {
      id: '/_authenticated/$slug/chat'
      path: '/chat'
      fullPath: '/$slug/chat'
      preLoaderRoute: typeof AuthenticatedSlugChatRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/automations': {
      id: '/_authenticated/$slug/automations'
      path: '/automations'
      fullPath: '/$slug/automations'
      preLoaderRoute: typeof AuthenticatedSlugAutomationsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/account/settings/': {
      id: '/_authenticated/account/settings/'
      path: '/'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AuthenticatedAccountSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRoute
    }
    '/_authenticated/$slug/tasks/': {
      id: '/_authenticated/$slug/tasks/'
      path: '/'
      fullPath: '/$slug/tasks/'
      preLoaderRoute: typeof AuthenticatedSlugTasksIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTasksRoute
    }
    '/_authenticated/$slug/settings/': {
      id: '/_authenticated/$slug/settings/'
      path: '/'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof AuthenticatedSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsRoute
    }
    '/_authenticated/$slug/chat/': {
      id: '/_authenticated/$slug/chat/'
      path: '/'
      fullPath: '/$slug/chat/'
      preLoaderRoute: typeof AuthenticatedSlugChatIndexRouteImport
      parentRoute: typeof AuthenticatedSlugChatRoute
    }
    '/_authenticated/$slug/automations/': {
      id: '/_authenticated/$slug/automations/'
      path: '/'
      fullPath: '/$slug/automations/'
      preLoaderRoute: typeof AuthenticatedSlugAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugAutomationsRoute
    }
    '/api/v1/system/health': {
      id: '/api/v1/system/health'
      path: '/api/v1/system/health'
      fullPath: '/api/v1/system/health'
      preLoaderRoute: typeof ApiV1SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/signals/$id': {
      id: '/api/v1/signals/$id'
      path: '/$id'
      fullPath: '/api/v1/signals/$id'
      preLoaderRoute: typeof ApiV1SignalsIdRouteImport
      parentRoute: typeof ApiV1SignalsRoute
    }
    '/api/skills/index/events': {
      id: '/api/skills/index/events'
      path: '/api/skills/index/events'
      fullPath: '/api/skills/index/events'
      preLoaderRoute: typeof ApiSkillsIndexEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/desktop/session': {
      id: '/api/oauth/desktop/session'
      path: '/api/oauth/desktop/session'
      fullPath: '/api/oauth/desktop/session'
      preLoaderRoute: typeof ApiOauthDesktopSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/$client/config': {
      id: '/api/oauth/$client/config'
      path: '/api/oauth/$client/config'
      fullPath: '/api/oauth/$client/config'
      preLoaderRoute: typeof ApiOauthClientConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/mcp/signals': {
      id: '/api/internal/mcp/signals'
      path: '/api/internal/mcp/signals'
      fullPath: '/api/internal/mcp/signals'
      preLoaderRoute: typeof ApiInternalMcpSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/mcp/audit': {
      id: '/api/internal/mcp/audit'
      path: '/api/internal/mcp/audit'
      fullPath: '/api/internal/mcp/audit'
      preLoaderRoute: typeof ApiInternalMcpAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/oauth/callback': {
      id: '/api/github/oauth/callback'
      path: '/api/github/oauth/callback'
      fullPath: '/api/github/oauth/callback'
      preLoaderRoute: typeof ApiGithubOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/x/mcp': {
      id: '/api/connectors/x/mcp'
      path: '/api/connectors/x/mcp'
      fullPath: '/api/connectors/x/mcp'
      preLoaderRoute: typeof ApiConnectorsXMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$id/stream': {
      id: '/api/chat/$id/stream'
      path: '/$id/stream'
      fullPath: '/api/chat/$id/stream'
      preLoaderRoute: typeof ApiChatIdStreamRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/_authenticated/accounts/teams/new': {
      id: '/_authenticated/accounts/teams/new'
      path: '/accounts/teams/new'
      fullPath: '/accounts/teams/new'
      preLoaderRoute: typeof AuthenticatedAccountsTeamsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/teams/new': {
      id: '/_authenticated/account/teams/new'
      path: '/teams/new'
      fullPath: '/account/teams/new'
      preLoaderRoute: typeof AuthenticatedAccountTeamsNewRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/tasks/username': {
      id: '/_authenticated/account/tasks/username'
      path: '/tasks/username'
      fullPath: '/account/tasks/username'
      preLoaderRoute: typeof AuthenticatedAccountTasksUsernameRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/tasks/github': {
      id: '/_authenticated/account/tasks/github'
      path: '/tasks/github'
      fullPath: '/account/tasks/github'
      preLoaderRoute: typeof AuthenticatedAccountTasksGithubRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/settings/source-control': {
      id: '/_authenticated/account/settings/source-control'
      path: '/source-control'
      fullPath: '/account/settings/source-control'
      preLoaderRoute: typeof AuthenticatedAccountSettingsSourceControlRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRoute
    }
    '/_authenticated/account/settings/general': {
      id: '/_authenticated/account/settings/general'
      path: '/general'
      fullPath: '/account/settings/general'
      preLoaderRoute: typeof AuthenticatedAccountSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRoute
    }
    '/_authenticated/$slug/tasks/bind': {
      id: '/_authenticated/$slug/tasks/bind'
      path: '/bind'
      fullPath: '/$slug/tasks/bind'
      preLoaderRoute: typeof AuthenticatedSlugTasksBindRouteImport
      parentRoute: typeof AuthenticatedSlugTasksRoute
    }
    '/_authenticated/$slug/settings/source-control': {
      id: '/_authenticated/$slug/settings/source-control'
      path: '/source-control'
      fullPath: '/$slug/settings/source-control'
      preLoaderRoute: typeof AuthenticatedSlugSettingsSourceControlRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsRoute
    }
    '/_authenticated/$slug/settings/members': {
      id: '/_authenticated/$slug/settings/members'
      path: '/members'
      fullPath: '/$slug/settings/members'
      preLoaderRoute: typeof AuthenticatedSlugSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsRoute
    }
    '/_authenticated/$slug/settings/mcp': {
      id: '/_authenticated/$slug/settings/mcp'
      path: '/mcp'
      fullPath: '/$slug/settings/mcp'
      preLoaderRoute: typeof AuthenticatedSlugSettingsMcpRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsRoute
    }
    '/_authenticated/$slug/settings/general': {
      id: '/_authenticated/$slug/settings/general'
      path: '/general'
      fullPath: '/$slug/settings/general'
      preLoaderRoute: typeof AuthenticatedSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsRoute
    }
    '/_authenticated/$slug/settings/billing': {
      id: '/_authenticated/$slug/settings/billing'
      path: '/billing'
      fullPath: '/$slug/settings/billing'
      preLoaderRoute: typeof AuthenticatedSlugSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsRoute
    }
    '/_authenticated/$slug/settings/api-keys': {
      id: '/_authenticated/$slug/settings/api-keys'
      path: '/api-keys'
      fullPath: '/$slug/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSlugSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsRoute
    }
    '/_authenticated/$slug/chat/$conversationId': {
      id: '/_authenticated/$slug/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/$slug/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedSlugChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedSlugChatRoute
    }
    '/_authenticated/$slug/automations/new': {
      id: '/_authenticated/$slug/automations/new'
      path: '/new'
      fullPath: '/$slug/automations/new'
      preLoaderRoute: typeof AuthenticatedSlugAutomationsNewRouteImport
      parentRoute: typeof AuthenticatedSlugAutomationsRoute
    }
    '/_authenticated/$slug/automations/$automation': {
      id: '/_authenticated/$slug/automations/$automation'
      path: '/$automation'
      fullPath: '/$slug/automations/$automation'
      preLoaderRoute: typeof AuthenticatedSlugAutomationsAutomationRouteImport
      parentRoute: typeof AuthenticatedSlugAutomationsRoute
    }
    '/_authenticated/account/tasks/github/': {
      id: '/_authenticated/account/tasks/github/'
      path: '/'
      fullPath: '/account/tasks/github/'
      preLoaderRoute: typeof AuthenticatedAccountTasksGithubIndexRouteImport
      parentRoute: typeof AuthenticatedAccountTasksGithubRoute
    }
    '/_authenticated/$slug/tasks/bind/': {
      id: '/_authenticated/$slug/tasks/bind/'
      path: '/'
      fullPath: '/$slug/tasks/bind/'
      preLoaderRoute: typeof AuthenticatedSlugTasksBindIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTasksBindRoute
    }
    '/api/internal/mcp/signals/get': {
      id: '/api/internal/mcp/signals/get'
      path: '/get'
      fullPath: '/api/internal/mcp/signals/get'
      preLoaderRoute: typeof ApiInternalMcpSignalsGetRouteImport
      parentRoute: typeof ApiInternalMcpSignalsRoute
    }
    '/api/internal/mcp/proxy/find': {
      id: '/api/internal/mcp/proxy/find'
      path: '/api/internal/mcp/proxy/find'
      fullPath: '/api/internal/mcp/proxy/find'
      preLoaderRoute: typeof ApiInternalMcpProxyFindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/mcp/proxy/call': {
      id: '/api/internal/mcp/proxy/call'
      path: '/api/internal/mcp/proxy/call'
      fullPath: '/api/internal/mcp/proxy/call'
      preLoaderRoute: typeof ApiInternalMcpProxyCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/user/oauth/callback': {
      id: '/api/github/user/oauth/callback'
      path: '/api/github/user/oauth/callback'
      fullPath: '/api/github/user/oauth/callback'
      preLoaderRoute: typeof ApiGithubUserOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/x/oauth/callback': {
      id: '/api/connectors/x/oauth/callback'
      path: '/api/connectors/x/oauth/callback'
      fullPath: '/api/connectors/x/oauth/callback'
      preLoaderRoute: typeof ApiConnectorsXOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/linear/oauth/callback': {
      id: '/api/connectors/linear/oauth/callback'
      path: '/api/connectors/linear/oauth/callback'
      fullPath: '/api/connectors/linear/oauth/callback'
      preLoaderRoute: typeof ApiConnectorsLinearOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/granola/oauth/callback': {
      id: '/api/connectors/granola/oauth/callback'
      path: '/api/connectors/granola/oauth/callback'
      fullPath: '/api/connectors/granola/oauth/callback'
      preLoaderRoute: typeof ApiConnectorsGranolaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/tasks/github/complete': {
      id: '/_authenticated/account/tasks/github/complete'
      path: '/complete'
      fullPath: '/account/tasks/github/complete'
      preLoaderRoute: typeof AuthenticatedAccountTasksGithubCompleteRouteImport
      parentRoute: typeof AuthenticatedAccountTasksGithubRoute
    }
    '/_authenticated/$slug/tasks/github/lightfast-repo': {
      id: '/_authenticated/$slug/tasks/github/lightfast-repo'
      path: '/github/lightfast-repo'
      fullPath: '/$slug/tasks/github/lightfast-repo'
      preLoaderRoute: typeof AuthenticatedSlugTasksGithubLightfastRepoRouteImport
      parentRoute: typeof AuthenticatedSlugTasksRoute
    }
    '/_authenticated/$slug/tasks/connectors/x': {
      id: '/_authenticated/$slug/tasks/connectors/x'
      path: '/connectors/x'
      fullPath: '/$slug/tasks/connectors/x'
      preLoaderRoute: typeof AuthenticatedSlugTasksConnectorsXRouteImport
      parentRoute: typeof AuthenticatedSlugTasksRoute
    }
    '/_authenticated/$slug/tasks/connectors/x/': {
      id: '/_authenticated/$slug/tasks/connectors/x/'
      path: '/'
      fullPath: '/$slug/tasks/connectors/x/'
      preLoaderRoute: typeof AuthenticatedSlugTasksConnectorsXIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTasksConnectorsXRoute
    }
    '/_authenticated/$slug/tasks/connectors/x/complete': {
      id: '/_authenticated/$slug/tasks/connectors/x/complete'
      path: '/complete'
      fullPath: '/$slug/tasks/connectors/x/complete'
      preLoaderRoute: typeof AuthenticatedSlugTasksConnectorsXCompleteRouteImport
      parentRoute: typeof AuthenticatedSlugTasksConnectorsXRoute
    }
    '/_authenticated/$slug/tasks/bind/github/complete': {
      id: '/_authenticated/$slug/tasks/bind/github/complete'
      path: '/github/complete'
      fullPath: '/$slug/tasks/bind/github/complete'
      preLoaderRoute: typeof AuthenticatedSlugTasksBindGithubCompleteRouteImport
      parentRoute: typeof AuthenticatedSlugTasksBindRoute
    }
  }
}

interface AuthenticatedSlugAutomationsRouteChildren {
  AuthenticatedSlugAutomationsAutomationRoute: typeof AuthenticatedSlugAutomationsAutomationRoute
  AuthenticatedSlugAutomationsNewRoute: typeof AuthenticatedSlugAutomationsNewRoute
  AuthenticatedSlugAutomationsIndexRoute: typeof AuthenticatedSlugAutomationsIndexRoute
}

const AuthenticatedSlugAutomationsRouteChildren: AuthenticatedSlugAutomationsRouteChildren =
  {
    AuthenticatedSlugAutomationsAutomationRoute:
      AuthenticatedSlugAutomationsAutomationRoute,
    AuthenticatedSlugAutomationsNewRoute: AuthenticatedSlugAutomationsNewRoute,
    AuthenticatedSlugAutomationsIndexRoute:
      AuthenticatedSlugAutomationsIndexRoute,
  }

const AuthenticatedSlugAutomationsRouteWithChildren =
  AuthenticatedSlugAutomationsRoute._addFileChildren(
    AuthenticatedSlugAutomationsRouteChildren,
  )

interface AuthenticatedSlugChatRouteChildren {
  AuthenticatedSlugChatConversationIdRoute: typeof AuthenticatedSlugChatConversationIdRoute
  AuthenticatedSlugChatIndexRoute: typeof AuthenticatedSlugChatIndexRoute
}

const AuthenticatedSlugChatRouteChildren: AuthenticatedSlugChatRouteChildren = {
  AuthenticatedSlugChatConversationIdRoute:
    AuthenticatedSlugChatConversationIdRoute,
  AuthenticatedSlugChatIndexRoute: AuthenticatedSlugChatIndexRoute,
}

const AuthenticatedSlugChatRouteWithChildren =
  AuthenticatedSlugChatRoute._addFileChildren(
    AuthenticatedSlugChatRouteChildren,
  )

interface AuthenticatedSlugSettingsRouteChildren {
  AuthenticatedSlugSettingsApiKeysRoute: typeof AuthenticatedSlugSettingsApiKeysRoute
  AuthenticatedSlugSettingsBillingRoute: typeof AuthenticatedSlugSettingsBillingRoute
  AuthenticatedSlugSettingsGeneralRoute: typeof AuthenticatedSlugSettingsGeneralRoute
  AuthenticatedSlugSettingsMcpRoute: typeof AuthenticatedSlugSettingsMcpRoute
  AuthenticatedSlugSettingsMembersRoute: typeof AuthenticatedSlugSettingsMembersRoute
  AuthenticatedSlugSettingsSourceControlRoute: typeof AuthenticatedSlugSettingsSourceControlRoute
  AuthenticatedSlugSettingsIndexRoute: typeof AuthenticatedSlugSettingsIndexRoute
}

const AuthenticatedSlugSettingsRouteChildren: AuthenticatedSlugSettingsRouteChildren =
  {
    AuthenticatedSlugSettingsApiKeysRoute:
      AuthenticatedSlugSettingsApiKeysRoute,
    AuthenticatedSlugSettingsBillingRoute:
      AuthenticatedSlugSettingsBillingRoute,
    AuthenticatedSlugSettingsGeneralRoute:
      AuthenticatedSlugSettingsGeneralRoute,
    AuthenticatedSlugSettingsMcpRoute: AuthenticatedSlugSettingsMcpRoute,
    AuthenticatedSlugSettingsMembersRoute:
      AuthenticatedSlugSettingsMembersRoute,
    AuthenticatedSlugSettingsSourceControlRoute:
      AuthenticatedSlugSettingsSourceControlRoute,
    AuthenticatedSlugSettingsIndexRoute: AuthenticatedSlugSettingsIndexRoute,
  }

const AuthenticatedSlugSettingsRouteWithChildren =
  AuthenticatedSlugSettingsRoute._addFileChildren(
    AuthenticatedSlugSettingsRouteChildren,
  )

interface AuthenticatedSlugTasksBindRouteChildren {
  AuthenticatedSlugTasksBindIndexRoute: typeof AuthenticatedSlugTasksBindIndexRoute
  AuthenticatedSlugTasksBindGithubCompleteRoute: typeof AuthenticatedSlugTasksBindGithubCompleteRoute
}

const AuthenticatedSlugTasksBindRouteChildren: AuthenticatedSlugTasksBindRouteChildren =
  {
    AuthenticatedSlugTasksBindIndexRoute: AuthenticatedSlugTasksBindIndexRoute,
    AuthenticatedSlugTasksBindGithubCompleteRoute:
      AuthenticatedSlugTasksBindGithubCompleteRoute,
  }

const AuthenticatedSlugTasksBindRouteWithChildren =
  AuthenticatedSlugTasksBindRoute._addFileChildren(
    AuthenticatedSlugTasksBindRouteChildren,
  )

interface AuthenticatedSlugTasksConnectorsXRouteChildren {
  AuthenticatedSlugTasksConnectorsXCompleteRoute: typeof AuthenticatedSlugTasksConnectorsXCompleteRoute
  AuthenticatedSlugTasksConnectorsXIndexRoute: typeof AuthenticatedSlugTasksConnectorsXIndexRoute
}

const AuthenticatedSlugTasksConnectorsXRouteChildren: AuthenticatedSlugTasksConnectorsXRouteChildren =
  {
    AuthenticatedSlugTasksConnectorsXCompleteRoute:
      AuthenticatedSlugTasksConnectorsXCompleteRoute,
    AuthenticatedSlugTasksConnectorsXIndexRoute:
      AuthenticatedSlugTasksConnectorsXIndexRoute,
  }

const AuthenticatedSlugTasksConnectorsXRouteWithChildren =
  AuthenticatedSlugTasksConnectorsXRoute._addFileChildren(
    AuthenticatedSlugTasksConnectorsXRouteChildren,
  )

interface AuthenticatedSlugTasksRouteChildren {
  AuthenticatedSlugTasksBindRoute: typeof AuthenticatedSlugTasksBindRouteWithChildren
  AuthenticatedSlugTasksIndexRoute: typeof AuthenticatedSlugTasksIndexRoute
  AuthenticatedSlugTasksConnectorsXRoute: typeof AuthenticatedSlugTasksConnectorsXRouteWithChildren
  AuthenticatedSlugTasksGithubLightfastRepoRoute: typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
}

const AuthenticatedSlugTasksRouteChildren: AuthenticatedSlugTasksRouteChildren =
  {
    AuthenticatedSlugTasksBindRoute:
      AuthenticatedSlugTasksBindRouteWithChildren,
    AuthenticatedSlugTasksIndexRoute: AuthenticatedSlugTasksIndexRoute,
    AuthenticatedSlugTasksConnectorsXRoute:
      AuthenticatedSlugTasksConnectorsXRouteWithChildren,
    AuthenticatedSlugTasksGithubLightfastRepoRoute:
      AuthenticatedSlugTasksGithubLightfastRepoRoute,
  }

const AuthenticatedSlugTasksRouteWithChildren =
  AuthenticatedSlugTasksRoute._addFileChildren(
    AuthenticatedSlugTasksRouteChildren,
  )

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugAutomationsRoute: typeof AuthenticatedSlugAutomationsRouteWithChildren
  AuthenticatedSlugChatRoute: typeof AuthenticatedSlugChatRouteWithChildren
  AuthenticatedSlugConnectorsRoute: typeof AuthenticatedSlugConnectorsRoute
  AuthenticatedSlugDecisionsRoute: typeof AuthenticatedSlugDecisionsRoute
  AuthenticatedSlugDeveloperConnectionsRoute: typeof AuthenticatedSlugDeveloperConnectionsRoute
  AuthenticatedSlugPeopleRoute: typeof AuthenticatedSlugPeopleRoute
  AuthenticatedSlugSettingsRoute: typeof AuthenticatedSlugSettingsRouteWithChildren
  AuthenticatedSlugSignalsRoute: typeof AuthenticatedSlugSignalsRoute
  AuthenticatedSlugSkillsRoute: typeof AuthenticatedSlugSkillsRoute
  AuthenticatedSlugTasksRoute: typeof AuthenticatedSlugTasksRouteWithChildren
  AuthenticatedSlugIndexRoute: typeof AuthenticatedSlugIndexRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugAutomationsRoute:
    AuthenticatedSlugAutomationsRouteWithChildren,
  AuthenticatedSlugChatRoute: AuthenticatedSlugChatRouteWithChildren,
  AuthenticatedSlugConnectorsRoute: AuthenticatedSlugConnectorsRoute,
  AuthenticatedSlugDecisionsRoute: AuthenticatedSlugDecisionsRoute,
  AuthenticatedSlugDeveloperConnectionsRoute:
    AuthenticatedSlugDeveloperConnectionsRoute,
  AuthenticatedSlugPeopleRoute: AuthenticatedSlugPeopleRoute,
  AuthenticatedSlugSettingsRoute: AuthenticatedSlugSettingsRouteWithChildren,
  AuthenticatedSlugSignalsRoute: AuthenticatedSlugSignalsRoute,
  AuthenticatedSlugSkillsRoute: AuthenticatedSlugSkillsRoute,
  AuthenticatedSlugTasksRoute: AuthenticatedSlugTasksRouteWithChildren,
  AuthenticatedSlugIndexRoute: AuthenticatedSlugIndexRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedAccountSettingsRouteChildren {
  AuthenticatedAccountSettingsGeneralRoute: typeof AuthenticatedAccountSettingsGeneralRoute
  AuthenticatedAccountSettingsSourceControlRoute: typeof AuthenticatedAccountSettingsSourceControlRoute
  AuthenticatedAccountSettingsIndexRoute: typeof AuthenticatedAccountSettingsIndexRoute
}

const AuthenticatedAccountSettingsRouteChildren: AuthenticatedAccountSettingsRouteChildren =
  {
    AuthenticatedAccountSettingsGeneralRoute:
      AuthenticatedAccountSettingsGeneralRoute,
    AuthenticatedAccountSettingsSourceControlRoute:
      AuthenticatedAccountSettingsSourceControlRoute,
    AuthenticatedAccountSettingsIndexRoute:
      AuthenticatedAccountSettingsIndexRoute,
  }

const AuthenticatedAccountSettingsRouteWithChildren =
  AuthenticatedAccountSettingsRoute._addFileChildren(
    AuthenticatedAccountSettingsRouteChildren,
  )

interface AuthenticatedAccountTasksGithubRouteChildren {
  AuthenticatedAccountTasksGithubCompleteRoute: typeof AuthenticatedAccountTasksGithubCompleteRoute
  AuthenticatedAccountTasksGithubIndexRoute: typeof AuthenticatedAccountTasksGithubIndexRoute
}

const AuthenticatedAccountTasksGithubRouteChildren: AuthenticatedAccountTasksGithubRouteChildren =
  {
    AuthenticatedAccountTasksGithubCompleteRoute:
      AuthenticatedAccountTasksGithubCompleteRoute,
    AuthenticatedAccountTasksGithubIndexRoute:
      AuthenticatedAccountTasksGithubIndexRoute,
  }

const AuthenticatedAccountTasksGithubRouteWithChildren =
  AuthenticatedAccountTasksGithubRoute._addFileChildren(
    AuthenticatedAccountTasksGithubRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountMcpRoute: typeof AuthenticatedAccountMcpRoute
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRouteWithChildren
  AuthenticatedAccountTasksGithubRoute: typeof AuthenticatedAccountTasksGithubRouteWithChildren
  AuthenticatedAccountTasksUsernameRoute: typeof AuthenticatedAccountTasksUsernameRoute
  AuthenticatedAccountTeamsNewRoute: typeof AuthenticatedAccountTeamsNewRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountMcpRoute: AuthenticatedAccountMcpRoute,
  AuthenticatedAccountSettingsRoute:
    AuthenticatedAccountSettingsRouteWithChildren,
  AuthenticatedAccountTasksGithubRoute:
    AuthenticatedAccountTasksGithubRouteWithChildren,
  AuthenticatedAccountTasksUsernameRoute:
    AuthenticatedAccountTasksUsernameRoute,
  AuthenticatedAccountTeamsNewRoute: AuthenticatedAccountTeamsNewRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAccountsTeamsNewRoute: typeof AuthenticatedAccountsTeamsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAccountsTeamsNewRoute: AuthenticatedAccountsTeamsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiChatRouteChildren {
  ApiChatIdStreamRoute: typeof ApiChatIdStreamRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatIdStreamRoute: ApiChatIdStreamRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

interface OauthRegisterRouteChildren {
  OauthRegisterClientIdRoute: typeof OauthRegisterClientIdRoute
}

const OauthRegisterRouteChildren: OauthRegisterRouteChildren = {
  OauthRegisterClientIdRoute: OauthRegisterClientIdRoute,
}

const OauthRegisterRouteWithChildren = OauthRegisterRoute._addFileChildren(
  OauthRegisterRouteChildren,
)

interface ApiV1SignalsRouteChildren {
  ApiV1SignalsIdRoute: typeof ApiV1SignalsIdRoute
}

const ApiV1SignalsRouteChildren: ApiV1SignalsRouteChildren = {
  ApiV1SignalsIdRoute: ApiV1SignalsIdRoute,
}

const ApiV1SignalsRouteWithChildren = ApiV1SignalsRoute._addFileChildren(
  ApiV1SignalsRouteChildren,
)

interface ApiInternalMcpSignalsRouteChildren {
  ApiInternalMcpSignalsGetRoute: typeof ApiInternalMcpSignalsGetRoute
}

const ApiInternalMcpSignalsRouteChildren: ApiInternalMcpSignalsRouteChildren = {
  ApiInternalMcpSignalsGetRoute: ApiInternalMcpSignalsGetRoute,
}

const ApiInternalMcpSignalsRouteWithChildren =
  ApiInternalMcpSignalsRoute._addFileChildren(
    ApiInternalMcpSignalsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiInngestRoute: ApiInngestRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthJwksRoute: OauthJwksRoute,
  OauthRegisterRoute: OauthRegisterRouteWithChildren,
  OauthRevokeRoute: OauthRevokeRoute,
  OauthTokenRoute: OauthTokenRoute,
  SignUpAcceptInvitationRoute: SignUpAcceptInvitationRoute,
  ApiCliRpcRoute: ApiCliRpcRoute,
  ApiDesktopRpcRoute: ApiDesktopRpcRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiOauthFinalizeRoute: ApiOauthFinalizeRoute,
  ApiV1SignalsRoute: ApiV1SignalsRouteWithChildren,
  OauthClientStartRoute: OauthClientStartRoute,
  ApiConnectorsXMcpRoute: ApiConnectorsXMcpRoute,
  ApiGithubOauthCallbackRoute: ApiGithubOauthCallbackRoute,
  ApiInternalMcpAuditRoute: ApiInternalMcpAuditRoute,
  ApiInternalMcpSignalsRoute: ApiInternalMcpSignalsRouteWithChildren,
  ApiOauthClientConfigRoute: ApiOauthClientConfigRoute,
  ApiOauthDesktopSessionRoute: ApiOauthDesktopSessionRoute,
  ApiSkillsIndexEventsRoute: ApiSkillsIndexEventsRoute,
  ApiV1SystemHealthRoute: ApiV1SystemHealthRoute,
  ApiConnectorsGranolaOauthCallbackRoute:
    ApiConnectorsGranolaOauthCallbackRoute,
  ApiConnectorsLinearOauthCallbackRoute: ApiConnectorsLinearOauthCallbackRoute,
  ApiConnectorsXOauthCallbackRoute: ApiConnectorsXOauthCallbackRoute,
  ApiGithubUserOauthCallbackRoute: ApiGithubUserOauthCallbackRoute,
  ApiInternalMcpProxyCallRoute: ApiInternalMcpProxyCallRoute,
  ApiInternalMcpProxyFindRoute: ApiInternalMcpProxyFindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
