// Table schemas

// Relations for type-safe queries
export {
  gwInstallationsRelations,
  gwResourcesRelations,
  gwTokensRelations,
  orgActorIdentitiesRelations,
  orgWorkspacesRelations,
  workspaceActorProfilesRelations,
  workspaceIntegrationsRelations,
  workspaceKnowledgeDocumentsRelations,
  workspaceKnowledgeVectorChunksRelations,
  workspaceNeuralObservationsRelations,
  workspaceObservationClustersRelations,
  workspaceObservationRelationshipsRelations,
  workspaceTemporalStatesRelations,
  workspaceUserActivitiesRelations,
} from "./relations";

// Re-exported types from tables
export type {
  ActorResolutionTags,
  ClusterAffinityTags,
  ClusterTags,
  DocumentsIndexedTags,
  EntityExtractionTags,
  ErrorTags,
  GitHubSourceMetadata,
  JobDurationTags,
  NeuralObservationTags,
  ObservationActor,
  ObservationMetadata,
  ObservationReference,
  ProfileUpdateTags,
  RelationshipMetadata,
  TemporalEntityType,
  TemporalStateType,
  WorkflowInput,
  WorkflowOutput,
} from "./tables";
export {
  type GwBackfillRun,
  type GwInstallation,
  type GwResource,
  type GwToken,
  type GwWebhookDelivery,
  gwBackfillRuns,
  // Gateway-owned tables
  gwInstallations,
  gwResources,
  gwTokens,
  gwWebhookDeliveries,
  type InsertGwBackfillRun,
  type InsertGwInstallation,
  type InsertGwResource,
  type InsertGwToken,
  type InsertGwWebhookDelivery,
  type InsertOrgActorIdentity,
  type InsertOrgApiKey,
  type InsertOrgWorkspace,
  type InsertWorkspaceActorProfile,
  type InsertWorkspaceEvent,
  type InsertWorkspaceIntegration,
  type InsertWorkspaceKnowledgeDocument,
  type InsertWorkspaceKnowledgeVectorChunk,
  type InsertWorkspaceNeuralEntity,
  type InsertWorkspaceNeuralObservation,
  type InsertWorkspaceObservationCluster,
  type InsertWorkspaceObservationRelationship,
  type InsertWorkspaceOperationMetric,
  type InsertWorkspaceTemporalState,
  type InsertWorkspaceUserActivity,
  type InsertWorkspaceWorkflowRun,
  type OperationMetricTags,
  type OrgActorIdentity,
  type OrgApiKey,
  type OrgWorkspace,
  orgActorIdentities,
  orgApiKeys,
  // Org-scoped tables
  orgWorkspaces,
  type RelationshipType,
  type WorkspaceActorProfile,
  type WorkspaceEvent,
  type WorkspaceIntegration,
  type WorkspaceKnowledgeDocument,
  type WorkspaceKnowledgeVectorChunk,
  type WorkspaceNeuralEntity,
  type WorkspaceNeuralObservation,
  type WorkspaceObservationCluster,
  type WorkspaceObservationRelationship,
  type WorkspaceOperationMetric,
  type WorkspaceTemporalState,
  type WorkspaceUserActivity,
  type WorkspaceWorkflowRun,
  workspaceActorProfiles,
  // Workspace event storage
  workspaceEvents,
  workspaceIntegrations,
  // Workspace-scoped tables
  workspaceKnowledgeDocuments,
  workspaceKnowledgeVectorChunks,
  workspaceNeuralEntities,
  // Neural memory tables
  workspaceNeuralObservations,
  workspaceObservationClusters,
  // Relationship graph tables
  workspaceObservationRelationships,
  workspaceOperationsMetrics,
  workspaceTemporalStates,
  workspaceUserActivities,
  workspaceWorkflowRuns,
} from "./tables";
