// Table schemas

// Relations for type-safe queries
export {
  gwInstallationsRelations,
  gwResourcesRelations,
  gwTokensRelations,
  orgActorIdentitiesRelations,
  orgWorkspacesRelations,
  workspaceActorProfilesRelations,
  workspaceIntegrationsRelations,
  workspaceKnowledgeDocumentsRelations,
  workspaceKnowledgeVectorChunksRelations,
  workspaceNeuralObservationsRelations,
  workspaceObservationClustersRelations,
  workspaceObservationRelationshipsRelations,
  workspaceTemporalStatesRelations,
  workspaceUserActivitiesRelations,
} from "./relations";

// Re-exported types from tables
export type {
  ActorResolutionTags,
  ClusterAffinityTags,
  ClusterTags,
  DocumentsIndexedTags,
  EntityExtractionTags,
  ErrorTags,
  GitHubSourceMetadata,
  JobDurationTags,
  NeuralObservationTags,
  ObservationActor,
  ObservationMetadata,
  ObservationReference,
  ProfileUpdateTags,
  RelationshipMetadata,
  TemporalEntityType,
  TemporalStateType,
  WorkflowInput,
  WorkflowOutput,
} from "./tables";
export {
  type GwInstallation,
  type GwResource,
  type GwToken,
  type GwWebhookDelivery,
  // Gateway-owned tables
  gwInstallations,
  gwResources,
  gwTokens,
  gwWebhookDeliveries,
  type InsertGwInstallation,
  type InsertGwResource,
  type InsertGwToken,
  type InsertGwWebhookDelivery,
  type InsertOrgActorIdentity,
  type InsertOrgApiKey,
  type InsertOrgWorkspace,
  type InsertWorkspaceActorProfile,
  type InsertWorkspaceIngestionPayload,
  type InsertWorkspaceIntegration,
  type InsertWorkspaceKnowledgeDocument,
  type InsertWorkspaceKnowledgeVectorChunk,
  type InsertWorkspaceNeuralEntity,
  type InsertWorkspaceNeuralObservation,
  type InsertWorkspaceObservationCluster,
  type InsertWorkspaceObservationRelationship,
  type InsertWorkspaceOperationMetric,
  type InsertWorkspaceTemporalState,
  type InsertWorkspaceUserActivity,
  type InsertWorkspaceWebhookPayload,
  type InsertWorkspaceWorkflowRun,
  type OperationMetricTags,
  type OrgActorIdentity,
  type OrgApiKey,
  type OrgWorkspace,
  orgActorIdentities,
  orgApiKeys,
  // Org-scoped tables
  orgWorkspaces,
  type RelationshipType,
  type WorkspaceActorProfile,
  type WorkspaceIngestionPayload,
  type WorkspaceIntegration,
  type WorkspaceKnowledgeDocument,
  type WorkspaceKnowledgeVectorChunk,
  type WorkspaceNeuralEntity,
  type WorkspaceNeuralObservation,
  type WorkspaceObservationCluster,
  type WorkspaceObservationRelationship,
  type WorkspaceOperationMetric,
  type WorkspaceTemporalState,
  type WorkspaceUserActivity,
  type WorkspaceWebhookPayload,
  type WorkspaceWorkflowRun,
  workspaceActorProfiles,
  // Ingestion payload storage tables
  workspaceIngestionPayloads,
  workspaceIntegrations,
  // Workspace-scoped tables
  workspaceKnowledgeDocuments,
  workspaceKnowledgeVectorChunks,
  workspaceNeuralEntities,
  // Neural memory tables
  workspaceNeuralObservations,
  workspaceObservationClusters,
  // Relationship graph tables
  workspaceObservationRelationships,
  workspaceOperationsMetrics,
  workspaceTemporalStates,
  workspaceUserActivities,
  workspaceWebhookPayloads,
  workspaceWorkflowRuns,
} from "./tables";
