// Schema exports

// Client
export { db } from "./client";

// Re-exported types from schema
export type {
  ActorResolutionTags,
  ClusterAffinityTags,
  ClusterTags,
  DocumentsIndexedTags,
  EntityExtractionTags,
  ErrorTags,
  GitHubSourceMetadata,
  JobDurationTags,
  NeuralObservationTags,
  ObservationActor,
  ObservationMetadata,
  ObservationReference,
  ProfileUpdateTags,
  RelationshipMetadata,
  TemporalEntityType,
  TemporalStateType,
  WorkflowInput,
  WorkflowOutput,
} from "./schema";
export {
  type GwInstallation,
  type GwResource,
  type GwToken,
  type GwWebhookDelivery,
  // Gateway-owned tables
  gwInstallations,
  // Relations
  gwInstallationsRelations,
  gwResources,
  gwResourcesRelations,
  gwTokens,
  gwTokensRelations,
  gwWebhookDeliveries,
  type InsertGwInstallation,
  type InsertGwResource,
  type InsertGwToken,
  type InsertGwWebhookDelivery,
  type InsertOrgActorIdentity,
  type InsertOrgApiKey,
  type InsertOrgWorkspace,
  type InsertWorkspaceActorProfile,
  type InsertWorkspaceIngestionPayload,
  type InsertWorkspaceIntegration,
  type InsertWorkspaceKnowledgeDocument,
  type InsertWorkspaceKnowledgeVectorChunk,
  type InsertWorkspaceNeuralEntity,
  type InsertWorkspaceNeuralObservation,
  type InsertWorkspaceObservationCluster,
  type InsertWorkspaceObservationRelationship,
  type InsertWorkspaceOperationMetric,
  type InsertWorkspaceTemporalState,
  type InsertWorkspaceUserActivity,
  type InsertWorkspaceWebhookPayload,
  type InsertWorkspaceWorkflowRun,
  type OperationMetricTags,
  type OrgActorIdentity,
  type OrgApiKey,
  type OrgWorkspace,
  orgActorIdentities,
  orgActorIdentitiesRelations,
  orgApiKeys,
  // Org-scoped tables
  orgWorkspaces,
  orgWorkspacesRelations,
  type RelationshipType,
  type WorkspaceActorProfile,
  type WorkspaceIngestionPayload,
  type WorkspaceIntegration,
  type WorkspaceKnowledgeDocument,
  type WorkspaceKnowledgeVectorChunk,
  type WorkspaceNeuralEntity,
  type WorkspaceNeuralObservation,
  type WorkspaceObservationCluster,
  type WorkspaceObservationRelationship,
  type WorkspaceOperationMetric,
  type WorkspaceTemporalState,
  type WorkspaceUserActivity,
  type WorkspaceWebhookPayload,
  type WorkspaceWorkflowRun,
  workspaceActorProfiles,
  workspaceActorProfilesRelations,
  // Ingestion payload storage tables
  workspaceIngestionPayloads,
  workspaceIntegrations,
  workspaceIntegrationsRelations,
  // Workspace-scoped tables
  workspaceKnowledgeDocuments,
  workspaceKnowledgeDocumentsRelations,
  workspaceKnowledgeVectorChunks,
  workspaceKnowledgeVectorChunksRelations,
  workspaceNeuralEntities,
  // Neural memory tables
  workspaceNeuralObservations,
  workspaceNeuralObservationsRelations,
  workspaceObservationClusters,
  workspaceObservationClustersRelations,
  // Relationship graph tables
  workspaceObservationRelationships,
  workspaceObservationRelationshipsRelations,
  workspaceOperationsMetrics,
  workspaceTemporalStates,
  workspaceTemporalStatesRelations,
  workspaceUserActivities,
  workspaceUserActivitiesRelations,
  workspaceWebhookPayloads,
  workspaceWorkflowRuns,
} from "./schema";

// Utilities
export {
  buildWorkspaceNamespace,
  buildWorkspaceSettings,
  createCustomWorkspace,
  getWorkspaceKey,
} from "./utils/workspace";
export {
  generateRandomSlug,
  generateStoreSlug,
  generateWorkspaceName,
  validateStoreSlug,
  validateWorkspaceSlug,
} from "./utils/workspace-names";
