/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { ServerRoute as ApiStreamServerRouteImport } from './routes/api/stream'
import { ServerRoute as ApiAgentsServerRouteImport } from './routes/api/agents'
import { ServerRoute as ApiAgentsAgentIdServerRouteImport } from './routes/api/agents.$agentId'

const rootServerRouteImport = createServerRootRoute()

const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)
const ApiStreamServerRoute = ApiStreamServerRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAgentsServerRoute = ApiAgentsServerRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAgentsAgentIdServerRoute = ApiAgentsAgentIdServerRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => ApiAgentsServerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents' | '/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/agents/$agentId'
  id: '__root__' | '/' | '/agents' | '/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/agents': typeof ApiAgentsServerRouteWithChildren
  '/api/stream': typeof ApiStreamServerRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdServerRoute
}
export interface FileServerRoutesByTo {
  '/api/agents': typeof ApiAgentsServerRouteWithChildren
  '/api/stream': typeof ApiStreamServerRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/agents': typeof ApiAgentsServerRouteWithChildren
  '/api/stream': typeof ApiStreamServerRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/agents' | '/api/stream' | '/api/agents/$agentId'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/agents' | '/api/stream' | '/api/agents/$agentId'
  id: '__root__' | '/api/agents' | '/api/stream' | '/api/agents/$agentId'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAgentsServerRoute: typeof ApiAgentsServerRouteWithChildren
  ApiStreamServerRoute: typeof ApiStreamServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/agents/$agentId': {
      id: '/api/agents/$agentId'
      path: '/$agentId'
      fullPath: '/api/agents/$agentId'
      preLoaderRoute: typeof ApiAgentsAgentIdServerRouteImport
      parentRoute: typeof ApiAgentsServerRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ApiAgentsServerRouteChildren {
  ApiAgentsAgentIdServerRoute: typeof ApiAgentsAgentIdServerRoute
}

const ApiAgentsServerRouteChildren: ApiAgentsServerRouteChildren = {
  ApiAgentsAgentIdServerRoute: ApiAgentsAgentIdServerRoute,
}

const ApiAgentsServerRouteWithChildren = ApiAgentsServerRoute._addFileChildren(
  ApiAgentsServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAgentsServerRoute: ApiAgentsServerRouteWithChildren,
  ApiStreamServerRoute: ApiStreamServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
