[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = [
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm --filter @lightfast/media-server... build"
]

[start]
cmd = "node dist/server.js"