# name is set dynamically in wrangler.branch.toml by the CI workflow
name = 'lightfast-media-server'
main = "src/server.tsx"
compatibility_date = "2025-04-28"
compatibility_flags = ["nodejs_compat"]

# Add resource limits section
[limits]
cpu_ms = 200  # Default is usually 50ms
memory_mb = 512  # Default is usually 128MB

[vars]
# Fill these in with your actual secrets or use Wrangler secrets for sensitive values
R2_ACCESS_KEY_ID = "your-access-key-id"
R2_SECRET_ACCESS_KEY = "your-secret-access-key"
R2_ACCOUNT_ID = "your-account-id"
R2_BUCKET_NAME = "lightfast-media-server-dev"
SUPABASE_URL = "your-supabase-url"
SUPABASE_ANON_KEY = "your-supabase-anon-key"
SUPABASE_PROJECT_ID = "your-supabase-project-id"
OPENAI_API_KEY = "your-openai-api-key"
FAL_KEY = "your-fal-key"
BASE_URL = "https://your-worker-url.workers.dev"
NODE_ENV = "production"
INNGEST_EVENT_KEY = "your-inngest-event-key"
INNGEST_SIGNING_KEY = "your-inngest-signing-key"
# INNGEST_ENV is set dynamically in wrangler.branch.toml by the CI workflow

[[r2_buckets]]
binding = "MY_MEDIA_BUCKET" # This is the variable name you'll use in your Worker
bucket_name = "lightfast-media-server-dev"
preview_bucket_name = "lightfast-media-server-dev"

# Uncomment and edit if you want to use a custom domain
# [triggers]
# routes = ["media.yourdomain.com/*"]