import { ModelConfigSchema } from "../schemas";

/**
 * Active AI Models
 *
 * These are the models currently available and supported.
 * Models with `active: false` are functional but not shown in the UI.
 */
export const ACTIVE_MODELS = {
	// ===== OpenAI Models =====
	"gpt-4o-mini": ModelConfigSchema.parse({
		id: "gpt-4o-mini",
		provider: "openai",
		name: "gpt-4o-mini",
		displayName: "GPT-4o Mini",
		description: "Fast and efficient model for most tasks",
		maxTokens: 128000,
		costPer1KTokens: { input: 0.00015, output: 0.0006 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 20,
	}),
	"gpt-4o": ModelConfigSchema.parse({
		id: "gpt-4o",
		provider: "openai",
		name: "gpt-4o",
		displayName: "GPT-4o",
		description: "Most capable GPT-4 model with vision capabilities",
		maxTokens: 128000,
		costPer1KTokens: { input: 0.0025, output: 0.01 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 15,
	}),
	"gpt-4.1": ModelConfigSchema.parse({
		id: "gpt-4.1",
		provider: "openai",
		name: "gpt-4.1",
		displayName: "GPT-4.1",
		description: "Enhanced GPT-4 with 1M token context for developers",
		maxTokens: 1000000,
		costPer1KTokens: { input: 0.01, output: 0.04 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 12,
	}),
	o3: ModelConfigSchema.parse({
		id: "o3",
		provider: "openai",
		name: "o3",
		displayName: "o3",
		description: "Most powerful reasoning model for complex problem-solving",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.002, output: 0.008 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 10,
	}),
	"gpt-4.1-mini": ModelConfigSchema.parse({
		id: "gpt-4.1-mini",
		provider: "openai",
		name: "gpt-4.1-mini",
		displayName: "GPT-4.1 Mini",
		description: "Efficient GPT-4.1 model for everyday tasks",
		maxTokens: 128000,
		costPer1KTokens: { input: 0.00015, output: 0.0006 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 18,
	}),
	"gpt-4.1-nano": ModelConfigSchema.parse({
		id: "gpt-4.1-nano",
		provider: "openai",
		name: "gpt-4.1-nano",
		displayName: "GPT-4.1 Nano",
		description: "Ultra-efficient model for simple tasks with 1M context",
		maxTokens: 1000000,
		costPer1KTokens: { input: 0.0001, output: 0.0004 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: false,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 25,
	}),
	"o3-mini": ModelConfigSchema.parse({
		id: "o3-mini",
		provider: "openai",
		name: "o3-mini",
		displayName: "o3-mini",
		description: "Fast reasoning model for STEM tasks (deprecated)",
		maxTokens: 128000,
		costPer1KTokens: { input: 0.0011, output: 0.0044 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: false,
		},
		streamingDelay: 22,
	}),
	"o4-mini": ModelConfigSchema.parse({
		id: "o4-mini",
		provider: "openai",
		name: "o4-mini-2025-04-16",
		displayName: "o4-mini",
		description: "Latest fast reasoning model excelling at math & STEM",
		maxTokens: 128000,
		costPer1KTokens: { input: 0.0011, output: 0.0044 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: false,
		},
		streamingDelay: 20,
	}),
	"gpt-3.5-turbo": ModelConfigSchema.parse({
		id: "gpt-3.5-turbo",
		provider: "openai",
		name: "gpt-3.5-turbo",
		displayName: "GPT-3.5 Turbo",
		description: "Fast, reliable model for simple tasks",
		maxTokens: 16385,
		costPer1KTokens: { input: 0.001, output: 0.002 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: false,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 18,
	}),

	// ===== Anthropic Models =====
	"claude-4-opus-20250514": ModelConfigSchema.parse({
		id: "claude-4-opus-20250514",
		provider: "anthropic",
		name: "claude-4-opus-20250514",
		displayName: "Claude 4 Opus",
		description: "Most powerful model for complex tasks",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.015, output: 0.075 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false, // Base model - use -thinking variant for visible reasoning
			pdfSupport: true,
		},
		streamingDelay: 10,
		active: false, // High cost
	}),
	"claude-4-sonnet-20250514": ModelConfigSchema.parse({
		id: "claude-4-sonnet-20250514",
		provider: "anthropic",
		name: "claude-4-sonnet-20250514",
		displayName: "Claude 4 Sonnet",
		description: "Latest generation superior coding and reasoning model",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false, // Base model - use -thinking variant for visible reasoning
			pdfSupport: true,
		},
		streamingDelay: 12,
	}),
	"claude-3-7-sonnet-20250219": ModelConfigSchema.parse({
		id: "claude-3-7-sonnet-20250219",
		provider: "anthropic",
		name: "claude-3-7-sonnet-20250219",
		displayName: "Claude 3.7 Sonnet",
		description: "Enhanced performance model with improved capabilities",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false, // Base model - use -thinking variant for visible reasoning
			pdfSupport: true,
		},
		streamingDelay: 15,
	}),
	"claude-3-5-sonnet-20241022": ModelConfigSchema.parse({
		id: "claude-3-5-sonnet-20241022",
		provider: "anthropic",
		name: "claude-3-5-sonnet-20241022",
		displayName: "Claude 3.5 Sonnet",
		description: "Fast and capable model for most tasks",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false,
			pdfSupport: true,
		},
		streamingDelay: 15,
	}),
	"claude-3-5-sonnet-20240620": ModelConfigSchema.parse({
		id: "claude-3-5-sonnet-20240620",
		provider: "anthropic",
		name: "claude-3-5-sonnet-20240620",
		displayName: "Claude 3.5 Sonnet (2024-06-20)",
		description: "Previous version of Claude 3.5 Sonnet",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: false,
			pdfSupport: true,
		},
		streamingDelay: 15,
		active: false, // Older version
	}),
	"claude-3-5-haiku-20241022": ModelConfigSchema.parse({
		id: "claude-3-5-haiku-20241022",
		provider: "anthropic",
		name: "claude-3-5-haiku-20241022",
		displayName: "Claude 3.5 Haiku",
		description: "Ultra-fast model for lightweight tasks",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.0008, output: 0.004 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: false,
			thinking: false,
			pdfSupport: false,
		},
		streamingDelay: 22,
		active: false, // Specialized use case
	}),

	// ===== Thinking Mode Variants =====
	"claude-4-opus-20250514-thinking": ModelConfigSchema.parse({
		id: "claude-4-opus-20250514-thinking",
		provider: "anthropic",
		name: "claude-4-opus-20250514",
		displayName: "Claude 4 Opus (Thinking)",
		description: "Most powerful model with visible reasoning process",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.015, output: 0.075 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: true,
		},
		thinkingConfig: {
			enabled: true,
			defaultBudgetTokens: 20000,
		},
		streamingDelay: 18,
		active: false, // High cost
	}),
	"claude-4-sonnet-20250514-thinking": ModelConfigSchema.parse({
		id: "claude-4-sonnet-20250514-thinking",
		provider: "anthropic",
		name: "claude-4-sonnet-20250514",
		displayName: "Claude 4 Sonnet (Thinking)",
		description: "Balanced model with visible reasoning process",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: true,
		},
		thinkingConfig: {
			enabled: true,
			defaultBudgetTokens: 15000,
		},
		streamingDelay: 18,
	}),
	"claude-3-7-sonnet-20250219-thinking": ModelConfigSchema.parse({
		id: "claude-3-7-sonnet-20250219-thinking",
		provider: "anthropic",
		name: "claude-3-7-sonnet-20250219",
		displayName: "Claude 3.7 Sonnet (Thinking)",
		description: "Enhanced Claude 3.5 with visible reasoning process",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: true,
		},
		thinkingConfig: {
			enabled: true,
			defaultBudgetTokens: 12000,
		},
		streamingDelay: 20,
	}),
	"claude-3-5-sonnet-20241022-thinking": ModelConfigSchema.parse({
		id: "claude-3-5-sonnet-20241022-thinking",
		provider: "anthropic",
		name: "claude-3-5-sonnet-20241022",
		displayName: "Claude 3.5 Sonnet (Oct 2024) (Thinking)",
		description: "Latest Claude 3.5 with visible reasoning process",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: true,
		},
		streamingDelay: 20,
		active: false, // Reduce UI clutter
	}),
	"claude-3-5-sonnet-20240620-thinking": ModelConfigSchema.parse({
		id: "claude-3-5-sonnet-20240620-thinking",
		provider: "anthropic",
		name: "claude-3-5-sonnet-20240620",
		displayName: "Claude 3.5 Sonnet (Jun 2024) (Thinking)",
		description: "Original Claude 3.5 with visible reasoning process",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.003, output: 0.015 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: true,
		},
		streamingDelay: 20,
		active: false, // Older version
	}),
	"claude-3-5-haiku-20241022-thinking": ModelConfigSchema.parse({
		id: "claude-3-5-haiku-20241022-thinking",
		provider: "anthropic",
		name: "claude-3-5-haiku-20241022",
		displayName: "Claude 3.5 Haiku (Thinking)",
		description: "Ultra-fast model with visible reasoning process",
		maxTokens: 200000,
		costPer1KTokens: { input: 0.0008, output: 0.004 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: false,
			thinking: true,
			pdfSupport: false,
		},
		streamingDelay: 25,
		active: false, // Specialized use case
	}),

	// ===== OpenRouter Models (Beta/Preview) =====
	"x-ai/grok-3-beta": ModelConfigSchema.parse({
		id: "x-ai/grok-3-beta",
		provider: "openrouter",
		name: "x-ai/grok-3-beta",
		displayName: "Grok 3",
		description: "xAI's most powerful reasoning model for complex tasks",
		maxTokens: 131072,
		costPer1KTokens: { input: 3.0, output: 15.0 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: false, // Vision "coming soon" but not yet available
			thinking: true,
			pdfSupport: true,
		},
		streamingDelay: 10,
		active: false, // Disabled - Beta model
	}),
	"x-ai/grok-3-mini-beta": ModelConfigSchema.parse({
		id: "x-ai/grok-3-mini-beta",
		provider: "openrouter",
		name: "x-ai/grok-3-mini-beta",
		displayName: "Grok 3 Mini",
		description:
			"Fast and efficient reasoning model for math and quantitative tasks",
		maxTokens: 131072,
		costPer1KTokens: { input: 0.3, output: 0.5 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: false, // Vision "coming soon" but not yet available
			thinking: true,
			pdfSupport: true,
		},
		streamingDelay: 20,
		active: false, // Disabled
	}),
	"google/gemini-2.5-pro-preview": ModelConfigSchema.parse({
		id: "google/gemini-2.5-pro-preview",
		provider: "openrouter",
		name: "google/gemini-2.5-pro-preview",
		displayName: "Gemini 2.5 Pro",
		description:
			"Google's most advanced model for complex reasoning and coding",
		maxTokens: 1048576,
		costPer1KTokens: { input: 1.25, output: 10.0 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: false,
		},
		streamingDelay: 10,
		active: false, // Preview model
	}),
	"google/gemini-2.5-flash-preview": ModelConfigSchema.parse({
		id: "google/gemini-2.5-flash-preview",
		provider: "openrouter",
		name: "google/gemini-2.5-flash-preview",
		displayName: "Gemini 2.5 Flash",
		description:
			"Google's state-of-the-art workhorse model for reasoning and coding",
		maxTokens: 1048576,
		costPer1KTokens: { input: 0.15, output: 0.6 },
		features: {
			streaming: true,
			functionCalling: true,
			vision: true,
			thinking: true,
			pdfSupport: false,
		},
		streamingDelay: 15,
		active: false, // Disabled
	}),
} as const;