export const PITCH_SLIDES = [
  {
    id: "title",
    type: "title" as const,
    title: "LIGHTFAST",
    subtitle: "Pitch deck 2026 —",
    bgColor: "bg-[#8B3A3A]",
  },
  {
    id: "intro",
    type: "content" as const,
    title: "Hi, we are Lightfast.",
    leftText: "HERE'S HOW WE GOT FROM 0 TO 30",
    rightText: [
      "The memory layer for software teams.",
      "We help engineering teams search, discover, and trace context across their entire codebase and tooling.",
    ],
    bgColor: "bg-[#F5F5F0]",
    textColor: "text-foreground",
  },
  {
    id: "problem",
    type: "content" as const,
    title: "The Problem.",
    leftText: "CONTEXT IS SCATTERED",
    rightText: [
      "Engineers spend 30% of their time searching for context",
      "Knowledge lives in Slack, GitHub, Notion, Linear—disconnected",
      "When engineers leave, institutional knowledge walks out the door",
      "AI agents can't access the context they need to be effective",
    ],
    bgColor: "bg-[#F5F5F0]",
    textColor: "text-foreground",
  },
  {
    id: "solution",
    type: "content" as const,
    title: "Our Solution.",
    leftText: "A UNIFIED MEMORY LAYER",
    rightText: [
      "Connect all your engineering tools in minutes",
      "Semantic search across your entire knowledge base",
      "Trace any decision back to its source",
      "Give AI agents the context they need",
    ],
    bgColor: "bg-[#F5F5F0]",
    textColor: "text-foreground",
  },
  {
    id: "traction",
    type: "content" as const,
    title: "Early Traction.",
    leftText: "SIGNALS OF PRODUCT-MARKET FIT",
    rightText: [
      "500+ engineers on waitlist",
      "3 design partners in active pilots",
      "40% week-over-week search volume growth",
      "NPS of 72 from pilot users",
    ],
    bgColor: "bg-[#F5F5F0]",
    textColor: "text-foreground",
  },
  {
    id: "team",
    type: "content" as const,
    title: "The Team.",
    leftText: "FOUNDERS WITH DEEP EXPERIENCE",
    rightText: [
      "Previously built developer tools at scale",
      "Combined 15+ years in AI/ML infrastructure",
      "Deep technical background with product sensibility",
      "Network across Australian and global tech ecosystem",
    ],
    bgColor: "bg-[#F5F5F0]",
    textColor: "text-foreground",
  },
  {
    id: "ask",
    type: "content" as const,
    title: "The Ask.",
    leftText: "RAISING $1.5M SEED",
    rightText: [
      "12-18 months runway",
      "Expand engineering team (2 → 5)",
      "Launch public beta",
      "Reach $50K MRR milestone",
    ],
    bgColor: "bg-[#F5F5F0]",
    textColor: "text-foreground",
  },
  {
    id: "vision",
    type: "title" as const,
    title: "Every team deserves a perfect memory.",
    subtitle: "jp@jeevanpillay.com",
    bgColor: "bg-[#8B3A3A]",
  },
] as const;
