#!/usr/bin/env tsx

import { generateFiles } from "fumadocs-openapi";
import { openapi } from "../src/lib/openapi";
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

function findMdxFiles(dir: string): string[] {
	const files: string[] = [];
	const entries = readdirSync(dir);

	for (const entry of entries) {
		const fullPath = join(dir, entry);
		const stat = statSync(fullPath);

		if (stat.isDirectory()) {
			files.push(...findMdxFiles(fullPath));
		} else if (entry === "post.mdx") {
			files.push(fullPath);
		}
	}

	return files;
}

async function main() {
	console.log("Step 1: Generating OpenAPI spec from Zod schemas...");
	try {
		execSync("pnpm --filter @repo/console-types generate:openapi", {
			stdio: "inherit",
			cwd: process.cwd() + "/../..",
		});
	} catch (error) {
		console.error("❌ Failed to generate OpenAPI spec:", error);
		process.exit(1);
	}

	console.log("\nStep 2: Generating API documentation from OpenAPI spec...");
	try {
		await generateFiles({
			input: openapi,
			output: "./src/content/api/endpoints",
			includeDescription: true,
			groupBy: "tag",
			per: "operation",
			frontmatter: (title, description) => ({
				title,
				description,
				full: true,
			}),
		});

		console.log("\nStep 3: Adding AlphaBanner to generated endpoint pages...");
		const generatedFiles = findMdxFiles("./src/content/api/endpoints");

		for (const file of generatedFiles) {
			const content = readFileSync(file, "utf-8");

			// Check if AlphaBanner is already present
			if (content.includes("<AlphaBanner")) {
				continue;
			}

			// Find the end of frontmatter and add AlphaBanner after the auto-generated comment
			const lines = content.split("\n");
			const commentIndex = lines.findIndex(line =>
				line.includes("This file was generated by Fumadocs")
			);

			if (commentIndex !== -1) {
				// Insert AlphaBanner after the comment line and a blank line
				lines.splice(commentIndex + 2, 0, "<AlphaBanner />\n");
				writeFileSync(file, lines.join("\n"));
			}
		}

		console.log("✅ API documentation generated successfully!");
	} catch (error) {
		console.error("❌ Failed to generate API documentation:", error);
		process.exit(1);
	}
}

main();