/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as AuthenticatedSlugIndexRouteImport } from './routes/_authenticated/$slug/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiGithubSetupRouteImport } from './routes/api/github/setup'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account/settings'
import { Route as AuthenticatedAccountMcpRouteImport } from './routes/_authenticated/account/mcp'
import { Route as AuthenticatedSlugSkillsRouteImport } from './routes/_authenticated/$slug/skills'
import { Route as AuthenticatedSlugSignalsRouteImport } from './routes/_authenticated/$slug/signals'
import { Route as AuthenticatedSlugSettingsRouteImport } from './routes/_authenticated/$slug/settings'
import { Route as AuthenticatedSlugPeopleRouteImport } from './routes/_authenticated/$slug/people'
import { Route as AuthenticatedSlugDecisionsRouteImport } from './routes/_authenticated/$slug/decisions'
import { Route as AuthenticatedSlugConnectorsRouteImport } from './routes/_authenticated/$slug/connectors'
import { Route as AuthenticatedSlugChatRouteImport } from './routes/_authenticated/$slug/chat'
import { Route as AuthenticatedSlugAutomationsRouteImport } from './routes/_authenticated/$slug/automations'
import { Route as AuthenticatedAccountSettingsIndexRouteImport } from './routes/_authenticated/account/settings/index'
import { Route as ApiGithubOauthCallbackRouteImport } from './routes/api/github/oauth/callback'
import { Route as AuthenticatedAccountsTeamsNewRouteImport } from './routes/_authenticated/accounts/teams/new'
import { Route as AuthenticatedAccountTeamsNewRouteImport } from './routes/_authenticated/account/teams/new'
import { Route as AuthenticatedAccountTasksUsernameRouteImport } from './routes/_authenticated/account/tasks/username'
import { Route as AuthenticatedAccountTasksGithubRouteImport } from './routes/_authenticated/account/tasks/github'
import { Route as AuthenticatedAccountSettingsSourceControlRouteImport } from './routes/_authenticated/account/settings/source-control'
import { Route as AuthenticatedAccountSettingsGeneralRouteImport } from './routes/_authenticated/account/settings/general'
import { Route as AuthenticatedSlugTasksBindRouteImport } from './routes/_authenticated/$slug/tasks/bind'
import { Route as AuthenticatedSlugChatConversationIdRouteImport } from './routes/_authenticated/$slug/chat/$conversationId'
import { Route as ApiGithubUserOauthCallbackRouteImport } from './routes/api/github/user/oauth/callback'
import { Route as AuthenticatedAccountTasksGithubCompleteRouteImport } from './routes/_authenticated/account/tasks/github/complete'
import { Route as AuthenticatedSlugTasksGithubLightfastRepoRouteImport } from './routes/_authenticated/$slug/tasks/github/lightfast-repo'
import { Route as AuthenticatedSlugTasksBindGithubCompleteRouteImport } from './routes/_authenticated/$slug/tasks/bind/github/complete'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugIndexRoute = AuthenticatedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountMcpRoute = AuthenticatedAccountMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedAccountRoute,
} as any)
const AuthenticatedSlugSkillsRoute = AuthenticatedSlugSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugSignalsRoute =
  AuthenticatedSlugSignalsRouteImport.update({
    id: '/signals',
    path: '/signals',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsRoute =
  AuthenticatedSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugPeopleRoute = AuthenticatedSlugPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugDecisionsRoute =
  AuthenticatedSlugDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugConnectorsRoute =
  AuthenticatedSlugConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugChatRoute = AuthenticatedSlugChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugAutomationsRoute =
  AuthenticatedSlugAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedAccountSettingsIndexRoute =
  AuthenticatedAccountSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountSettingsRoute,
  } as any)
const ApiGithubOauthCallbackRoute = ApiGithubOauthCallbackRouteImport.update({
  id: '/api/github/oauth/callback',
  path: '/api/github/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsTeamsNewRoute =
  AuthenticatedAccountsTeamsNewRouteImport.update({
    id: '/accounts/teams/new',
    path: '/accounts/teams/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountTeamsNewRoute =
  AuthenticatedAccountTeamsNewRouteImport.update({
    id: '/teams/new',
    path: '/teams/new',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountTasksUsernameRoute =
  AuthenticatedAccountTasksUsernameRouteImport.update({
    id: '/tasks/username',
    path: '/tasks/username',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountTasksGithubRoute =
  AuthenticatedAccountTasksGithubRouteImport.update({
    id: '/tasks/github',
    path: '/tasks/github',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountSettingsSourceControlRoute =
  AuthenticatedAccountSettingsSourceControlRouteImport.update({
    id: '/source-control',
    path: '/source-control',
    getParentRoute: () => AuthenticatedAccountSettingsRoute,
  } as any)
const AuthenticatedAccountSettingsGeneralRoute =
  AuthenticatedAccountSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedAccountSettingsRoute,
  } as any)
const AuthenticatedSlugTasksBindRoute =
  AuthenticatedSlugTasksBindRouteImport.update({
    id: '/tasks/bind',
    path: '/tasks/bind',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugChatConversationIdRoute =
  AuthenticatedSlugChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedSlugChatRoute,
  } as any)
const ApiGithubUserOauthCallbackRoute =
  ApiGithubUserOauthCallbackRouteImport.update({
    id: '/api/github/user/oauth/callback',
    path: '/api/github/user/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountTasksGithubCompleteRoute =
  AuthenticatedAccountTasksGithubCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AuthenticatedAccountTasksGithubRoute,
  } as any)
const AuthenticatedSlugTasksGithubLightfastRepoRoute =
  AuthenticatedSlugTasksGithubLightfastRepoRouteImport.update({
    id: '/tasks/github/lightfast-repo',
    path: '/tasks/github/lightfast-repo',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTasksBindGithubCompleteRoute =
  AuthenticatedSlugTasksBindGithubCompleteRouteImport.update({
    id: '/github/complete',
    path: '/github/complete',
    getParentRoute: () => AuthenticatedSlugTasksBindRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/inngest': typeof ApiInngestRoute
  '/$slug/automations': typeof AuthenticatedSlugAutomationsRoute
  '/$slug/chat': typeof AuthenticatedSlugChatRouteWithChildren
  '/$slug/connectors': typeof AuthenticatedSlugConnectorsRoute
  '/$slug/decisions': typeof AuthenticatedSlugDecisionsRoute
  '/$slug/people': typeof AuthenticatedSlugPeopleRoute
  '/$slug/settings': typeof AuthenticatedSlugSettingsRoute
  '/$slug/signals': typeof AuthenticatedSlugSignalsRoute
  '/$slug/skills': typeof AuthenticatedSlugSkillsRoute
  '/account/mcp': typeof AuthenticatedAccountMcpRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRouteWithChildren
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$slug/': typeof AuthenticatedSlugIndexRoute
  '/$slug/chat/$conversationId': typeof AuthenticatedSlugChatConversationIdRoute
  '/$slug/tasks/bind': typeof AuthenticatedSlugTasksBindRouteWithChildren
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRoute
  '/account/settings/source-control': typeof AuthenticatedAccountSettingsSourceControlRoute
  '/account/tasks/github': typeof AuthenticatedAccountTasksGithubRouteWithChildren
  '/account/tasks/username': typeof AuthenticatedAccountTasksUsernameRoute
  '/account/teams/new': typeof AuthenticatedAccountTeamsNewRoute
  '/accounts/teams/new': typeof AuthenticatedAccountsTeamsNewRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/account/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/$slug/tasks/github/lightfast-repo': typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
  '/account/tasks/github/complete': typeof AuthenticatedAccountTasksGithubCompleteRoute
  '/api/github/user/oauth/callback': typeof ApiGithubUserOauthCallbackRoute
  '/$slug/tasks/bind/github/complete': typeof AuthenticatedSlugTasksBindGithubCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/inngest': typeof ApiInngestRoute
  '/$slug/automations': typeof AuthenticatedSlugAutomationsRoute
  '/$slug/chat': typeof AuthenticatedSlugChatRouteWithChildren
  '/$slug/connectors': typeof AuthenticatedSlugConnectorsRoute
  '/$slug/decisions': typeof AuthenticatedSlugDecisionsRoute
  '/$slug/people': typeof AuthenticatedSlugPeopleRoute
  '/$slug/settings': typeof AuthenticatedSlugSettingsRoute
  '/$slug/signals': typeof AuthenticatedSlugSignalsRoute
  '/$slug/skills': typeof AuthenticatedSlugSkillsRoute
  '/account/mcp': typeof AuthenticatedAccountMcpRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$slug': typeof AuthenticatedSlugIndexRoute
  '/$slug/chat/$conversationId': typeof AuthenticatedSlugChatConversationIdRoute
  '/$slug/tasks/bind': typeof AuthenticatedSlugTasksBindRouteWithChildren
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRoute
  '/account/settings/source-control': typeof AuthenticatedAccountSettingsSourceControlRoute
  '/account/tasks/github': typeof AuthenticatedAccountTasksGithubRouteWithChildren
  '/account/tasks/username': typeof AuthenticatedAccountTasksUsernameRoute
  '/account/teams/new': typeof AuthenticatedAccountTeamsNewRoute
  '/accounts/teams/new': typeof AuthenticatedAccountsTeamsNewRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/account/settings': typeof AuthenticatedAccountSettingsIndexRoute
  '/$slug/tasks/github/lightfast-repo': typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
  '/account/tasks/github/complete': typeof AuthenticatedAccountTasksGithubCompleteRoute
  '/api/github/user/oauth/callback': typeof ApiGithubUserOauthCallbackRoute
  '/$slug/tasks/bind/github/complete': typeof AuthenticatedSlugTasksBindGithubCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/inngest': typeof ApiInngestRoute
  '/_authenticated/$slug/automations': typeof AuthenticatedSlugAutomationsRoute
  '/_authenticated/$slug/chat': typeof AuthenticatedSlugChatRouteWithChildren
  '/_authenticated/$slug/connectors': typeof AuthenticatedSlugConnectorsRoute
  '/_authenticated/$slug/decisions': typeof AuthenticatedSlugDecisionsRoute
  '/_authenticated/$slug/people': typeof AuthenticatedSlugPeopleRoute
  '/_authenticated/$slug/settings': typeof AuthenticatedSlugSettingsRoute
  '/_authenticated/$slug/signals': typeof AuthenticatedSlugSignalsRoute
  '/_authenticated/$slug/skills': typeof AuthenticatedSlugSkillsRoute
  '/_authenticated/account/mcp': typeof AuthenticatedAccountMcpRoute
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRouteWithChildren
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/$slug/': typeof AuthenticatedSlugIndexRoute
  '/_authenticated/$slug/chat/$conversationId': typeof AuthenticatedSlugChatConversationIdRoute
  '/_authenticated/$slug/tasks/bind': typeof AuthenticatedSlugTasksBindRouteWithChildren
  '/_authenticated/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRoute
  '/_authenticated/account/settings/source-control': typeof AuthenticatedAccountSettingsSourceControlRoute
  '/_authenticated/account/tasks/github': typeof AuthenticatedAccountTasksGithubRouteWithChildren
  '/_authenticated/account/tasks/username': typeof AuthenticatedAccountTasksUsernameRoute
  '/_authenticated/account/teams/new': typeof AuthenticatedAccountTeamsNewRoute
  '/_authenticated/accounts/teams/new': typeof AuthenticatedAccountsTeamsNewRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/_authenticated/account/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/_authenticated/$slug/tasks/github/lightfast-repo': typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
  '/_authenticated/account/tasks/github/complete': typeof AuthenticatedAccountTasksGithubCompleteRoute
  '/api/github/user/oauth/callback': typeof ApiGithubUserOauthCallbackRoute
  '/_authenticated/$slug/tasks/bind/github/complete': typeof AuthenticatedSlugTasksBindGithubCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/$slug'
    | '/account'
    | '/api/health'
    | '/api/inngest'
    | '/$slug/automations'
    | '/$slug/chat'
    | '/$slug/connectors'
    | '/$slug/decisions'
    | '/$slug/people'
    | '/$slug/settings'
    | '/$slug/signals'
    | '/$slug/skills'
    | '/account/mcp'
    | '/account/settings'
    | '/api/github/setup'
    | '/api/trpc/$'
    | '/$slug/'
    | '/$slug/chat/$conversationId'
    | '/$slug/tasks/bind'
    | '/account/settings/general'
    | '/account/settings/source-control'
    | '/account/tasks/github'
    | '/account/tasks/username'
    | '/account/teams/new'
    | '/accounts/teams/new'
    | '/api/github/oauth/callback'
    | '/account/settings/'
    | '/$slug/tasks/github/lightfast-repo'
    | '/account/tasks/github/complete'
    | '/api/github/user/oauth/callback'
    | '/$slug/tasks/bind/github/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/api/health'
    | '/api/inngest'
    | '/$slug/automations'
    | '/$slug/chat'
    | '/$slug/connectors'
    | '/$slug/decisions'
    | '/$slug/people'
    | '/$slug/settings'
    | '/$slug/signals'
    | '/$slug/skills'
    | '/account/mcp'
    | '/api/github/setup'
    | '/api/trpc/$'
    | '/$slug'
    | '/$slug/chat/$conversationId'
    | '/$slug/tasks/bind'
    | '/account/settings/general'
    | '/account/settings/source-control'
    | '/account/tasks/github'
    | '/account/tasks/username'
    | '/account/teams/new'
    | '/accounts/teams/new'
    | '/api/github/oauth/callback'
    | '/account/settings'
    | '/$slug/tasks/github/lightfast-repo'
    | '/account/tasks/github/complete'
    | '/api/github/user/oauth/callback'
    | '/$slug/tasks/bind/github/complete'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/$slug'
    | '/_authenticated/account'
    | '/api/health'
    | '/api/inngest'
    | '/_authenticated/$slug/automations'
    | '/_authenticated/$slug/chat'
    | '/_authenticated/$slug/connectors'
    | '/_authenticated/$slug/decisions'
    | '/_authenticated/$slug/people'
    | '/_authenticated/$slug/settings'
    | '/_authenticated/$slug/signals'
    | '/_authenticated/$slug/skills'
    | '/_authenticated/account/mcp'
    | '/_authenticated/account/settings'
    | '/api/github/setup'
    | '/api/trpc/$'
    | '/_authenticated/$slug/'
    | '/_authenticated/$slug/chat/$conversationId'
    | '/_authenticated/$slug/tasks/bind'
    | '/_authenticated/account/settings/general'
    | '/_authenticated/account/settings/source-control'
    | '/_authenticated/account/tasks/github'
    | '/_authenticated/account/tasks/username'
    | '/_authenticated/account/teams/new'
    | '/_authenticated/accounts/teams/new'
    | '/api/github/oauth/callback'
    | '/_authenticated/account/settings/'
    | '/_authenticated/$slug/tasks/github/lightfast-repo'
    | '/_authenticated/account/tasks/github/complete'
    | '/api/github/user/oauth/callback'
    | '/_authenticated/$slug/tasks/bind/github/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiGithubOauthCallbackRoute: typeof ApiGithubOauthCallbackRoute
  ApiGithubUserOauthCallbackRoute: typeof ApiGithubUserOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug/': {
      id: '/_authenticated/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthenticatedSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/mcp': {
      id: '/_authenticated/account/mcp'
      path: '/mcp'
      fullPath: '/account/mcp'
      preLoaderRoute: typeof AuthenticatedAccountMcpRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/$slug/skills': {
      id: '/_authenticated/$slug/skills'
      path: '/skills'
      fullPath: '/$slug/skills'
      preLoaderRoute: typeof AuthenticatedSlugSkillsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/signals': {
      id: '/_authenticated/$slug/signals'
      path: '/signals'
      fullPath: '/$slug/signals'
      preLoaderRoute: typeof AuthenticatedSlugSignalsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings': {
      id: '/_authenticated/$slug/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof AuthenticatedSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/people': {
      id: '/_authenticated/$slug/people'
      path: '/people'
      fullPath: '/$slug/people'
      preLoaderRoute: typeof AuthenticatedSlugPeopleRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/decisions': {
      id: '/_authenticated/$slug/decisions'
      path: '/decisions'
      fullPath: '/$slug/decisions'
      preLoaderRoute: typeof AuthenticatedSlugDecisionsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/connectors': {
      id: '/_authenticated/$slug/connectors'
      path: '/connectors'
      fullPath: '/$slug/connectors'
      preLoaderRoute: typeof AuthenticatedSlugConnectorsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/chat': {
      id: '/_authenticated/$slug/chat'
      path: '/chat'
      fullPath: '/$slug/chat'
      preLoaderRoute: typeof AuthenticatedSlugChatRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/automations': {
      id: '/_authenticated/$slug/automations'
      path: '/automations'
      fullPath: '/$slug/automations'
      preLoaderRoute: typeof AuthenticatedSlugAutomationsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/account/settings/': {
      id: '/_authenticated/account/settings/'
      path: '/'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AuthenticatedAccountSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRoute
    }
    '/api/github/oauth/callback': {
      id: '/api/github/oauth/callback'
      path: '/api/github/oauth/callback'
      fullPath: '/api/github/oauth/callback'
      preLoaderRoute: typeof ApiGithubOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts/teams/new': {
      id: '/_authenticated/accounts/teams/new'
      path: '/accounts/teams/new'
      fullPath: '/accounts/teams/new'
      preLoaderRoute: typeof AuthenticatedAccountsTeamsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/teams/new': {
      id: '/_authenticated/account/teams/new'
      path: '/teams/new'
      fullPath: '/account/teams/new'
      preLoaderRoute: typeof AuthenticatedAccountTeamsNewRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/tasks/username': {
      id: '/_authenticated/account/tasks/username'
      path: '/tasks/username'
      fullPath: '/account/tasks/username'
      preLoaderRoute: typeof AuthenticatedAccountTasksUsernameRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/tasks/github': {
      id: '/_authenticated/account/tasks/github'
      path: '/tasks/github'
      fullPath: '/account/tasks/github'
      preLoaderRoute: typeof AuthenticatedAccountTasksGithubRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/settings/source-control': {
      id: '/_authenticated/account/settings/source-control'
      path: '/source-control'
      fullPath: '/account/settings/source-control'
      preLoaderRoute: typeof AuthenticatedAccountSettingsSourceControlRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRoute
    }
    '/_authenticated/account/settings/general': {
      id: '/_authenticated/account/settings/general'
      path: '/general'
      fullPath: '/account/settings/general'
      preLoaderRoute: typeof AuthenticatedAccountSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRoute
    }
    '/_authenticated/$slug/tasks/bind': {
      id: '/_authenticated/$slug/tasks/bind'
      path: '/tasks/bind'
      fullPath: '/$slug/tasks/bind'
      preLoaderRoute: typeof AuthenticatedSlugTasksBindRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/chat/$conversationId': {
      id: '/_authenticated/$slug/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/$slug/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedSlugChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedSlugChatRoute
    }
    '/api/github/user/oauth/callback': {
      id: '/api/github/user/oauth/callback'
      path: '/api/github/user/oauth/callback'
      fullPath: '/api/github/user/oauth/callback'
      preLoaderRoute: typeof ApiGithubUserOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/tasks/github/complete': {
      id: '/_authenticated/account/tasks/github/complete'
      path: '/complete'
      fullPath: '/account/tasks/github/complete'
      preLoaderRoute: typeof AuthenticatedAccountTasksGithubCompleteRouteImport
      parentRoute: typeof AuthenticatedAccountTasksGithubRoute
    }
    '/_authenticated/$slug/tasks/github/lightfast-repo': {
      id: '/_authenticated/$slug/tasks/github/lightfast-repo'
      path: '/tasks/github/lightfast-repo'
      fullPath: '/$slug/tasks/github/lightfast-repo'
      preLoaderRoute: typeof AuthenticatedSlugTasksGithubLightfastRepoRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/tasks/bind/github/complete': {
      id: '/_authenticated/$slug/tasks/bind/github/complete'
      path: '/github/complete'
      fullPath: '/$slug/tasks/bind/github/complete'
      preLoaderRoute: typeof AuthenticatedSlugTasksBindGithubCompleteRouteImport
      parentRoute: typeof AuthenticatedSlugTasksBindRoute
    }
  }
}

interface AuthenticatedSlugChatRouteChildren {
  AuthenticatedSlugChatConversationIdRoute: typeof AuthenticatedSlugChatConversationIdRoute
}

const AuthenticatedSlugChatRouteChildren: AuthenticatedSlugChatRouteChildren = {
  AuthenticatedSlugChatConversationIdRoute:
    AuthenticatedSlugChatConversationIdRoute,
}

const AuthenticatedSlugChatRouteWithChildren =
  AuthenticatedSlugChatRoute._addFileChildren(
    AuthenticatedSlugChatRouteChildren,
  )

interface AuthenticatedSlugTasksBindRouteChildren {
  AuthenticatedSlugTasksBindGithubCompleteRoute: typeof AuthenticatedSlugTasksBindGithubCompleteRoute
}

const AuthenticatedSlugTasksBindRouteChildren: AuthenticatedSlugTasksBindRouteChildren =
  {
    AuthenticatedSlugTasksBindGithubCompleteRoute:
      AuthenticatedSlugTasksBindGithubCompleteRoute,
  }

const AuthenticatedSlugTasksBindRouteWithChildren =
  AuthenticatedSlugTasksBindRoute._addFileChildren(
    AuthenticatedSlugTasksBindRouteChildren,
  )

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugAutomationsRoute: typeof AuthenticatedSlugAutomationsRoute
  AuthenticatedSlugChatRoute: typeof AuthenticatedSlugChatRouteWithChildren
  AuthenticatedSlugConnectorsRoute: typeof AuthenticatedSlugConnectorsRoute
  AuthenticatedSlugDecisionsRoute: typeof AuthenticatedSlugDecisionsRoute
  AuthenticatedSlugPeopleRoute: typeof AuthenticatedSlugPeopleRoute
  AuthenticatedSlugSettingsRoute: typeof AuthenticatedSlugSettingsRoute
  AuthenticatedSlugSignalsRoute: typeof AuthenticatedSlugSignalsRoute
  AuthenticatedSlugSkillsRoute: typeof AuthenticatedSlugSkillsRoute
  AuthenticatedSlugIndexRoute: typeof AuthenticatedSlugIndexRoute
  AuthenticatedSlugTasksBindRoute: typeof AuthenticatedSlugTasksBindRouteWithChildren
  AuthenticatedSlugTasksGithubLightfastRepoRoute: typeof AuthenticatedSlugTasksGithubLightfastRepoRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugAutomationsRoute: AuthenticatedSlugAutomationsRoute,
  AuthenticatedSlugChatRoute: AuthenticatedSlugChatRouteWithChildren,
  AuthenticatedSlugConnectorsRoute: AuthenticatedSlugConnectorsRoute,
  AuthenticatedSlugDecisionsRoute: AuthenticatedSlugDecisionsRoute,
  AuthenticatedSlugPeopleRoute: AuthenticatedSlugPeopleRoute,
  AuthenticatedSlugSettingsRoute: AuthenticatedSlugSettingsRoute,
  AuthenticatedSlugSignalsRoute: AuthenticatedSlugSignalsRoute,
  AuthenticatedSlugSkillsRoute: AuthenticatedSlugSkillsRoute,
  AuthenticatedSlugIndexRoute: AuthenticatedSlugIndexRoute,
  AuthenticatedSlugTasksBindRoute: AuthenticatedSlugTasksBindRouteWithChildren,
  AuthenticatedSlugTasksGithubLightfastRepoRoute:
    AuthenticatedSlugTasksGithubLightfastRepoRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedAccountSettingsRouteChildren {
  AuthenticatedAccountSettingsGeneralRoute: typeof AuthenticatedAccountSettingsGeneralRoute
  AuthenticatedAccountSettingsSourceControlRoute: typeof AuthenticatedAccountSettingsSourceControlRoute
  AuthenticatedAccountSettingsIndexRoute: typeof AuthenticatedAccountSettingsIndexRoute
}

const AuthenticatedAccountSettingsRouteChildren: AuthenticatedAccountSettingsRouteChildren =
  {
    AuthenticatedAccountSettingsGeneralRoute:
      AuthenticatedAccountSettingsGeneralRoute,
    AuthenticatedAccountSettingsSourceControlRoute:
      AuthenticatedAccountSettingsSourceControlRoute,
    AuthenticatedAccountSettingsIndexRoute:
      AuthenticatedAccountSettingsIndexRoute,
  }

const AuthenticatedAccountSettingsRouteWithChildren =
  AuthenticatedAccountSettingsRoute._addFileChildren(
    AuthenticatedAccountSettingsRouteChildren,
  )

interface AuthenticatedAccountTasksGithubRouteChildren {
  AuthenticatedAccountTasksGithubCompleteRoute: typeof AuthenticatedAccountTasksGithubCompleteRoute
}

const AuthenticatedAccountTasksGithubRouteChildren: AuthenticatedAccountTasksGithubRouteChildren =
  {
    AuthenticatedAccountTasksGithubCompleteRoute:
      AuthenticatedAccountTasksGithubCompleteRoute,
  }

const AuthenticatedAccountTasksGithubRouteWithChildren =
  AuthenticatedAccountTasksGithubRoute._addFileChildren(
    AuthenticatedAccountTasksGithubRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountMcpRoute: typeof AuthenticatedAccountMcpRoute
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRouteWithChildren
  AuthenticatedAccountTasksGithubRoute: typeof AuthenticatedAccountTasksGithubRouteWithChildren
  AuthenticatedAccountTasksUsernameRoute: typeof AuthenticatedAccountTasksUsernameRoute
  AuthenticatedAccountTeamsNewRoute: typeof AuthenticatedAccountTeamsNewRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountMcpRoute: AuthenticatedAccountMcpRoute,
  AuthenticatedAccountSettingsRoute:
    AuthenticatedAccountSettingsRouteWithChildren,
  AuthenticatedAccountTasksGithubRoute:
    AuthenticatedAccountTasksGithubRouteWithChildren,
  AuthenticatedAccountTasksUsernameRoute:
    AuthenticatedAccountTasksUsernameRoute,
  AuthenticatedAccountTeamsNewRoute: AuthenticatedAccountTeamsNewRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAccountsTeamsNewRoute: typeof AuthenticatedAccountsTeamsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAccountsTeamsNewRoute: AuthenticatedAccountsTeamsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiGithubOauthCallbackRoute: ApiGithubOauthCallbackRoute,
  ApiGithubUserOauthCallbackRoute: ApiGithubUserOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
