/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesTechnicalFoundersRouteImport } from './routes/use-cases/technical-founders'
import { Route as UseCasesPlatformEngineersRouteImport } from './routes/use-cases/platform-engineers'
import { Route as UseCasesEngineeringLeadersRouteImport } from './routes/use-cases/engineering-leaders'
import { Route as UseCasesAgentBuildersRouteImport } from './routes/use-cases/agent-builders'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ChangelogRssDotxmlRouteImport } from './routes/changelog/rss[.]xml'
import { Route as ChangelogFeedDotxmlRouteImport } from './routes/changelog/feed[.]xml'
import { Route as ChangelogAtomDotxmlRouteImport } from './routes/changelog/atom[.]xml'
import { Route as ChangelogSlugRouteImport } from './routes/changelog/$slug'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog/rss[.]xml'
import { Route as BlogFeedDotxmlRouteImport } from './routes/blog/feed[.]xml'
import { Route as BlogAtomDotxmlRouteImport } from './routes/blog/atom[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogTopicCategoryRouteImport } from './routes/blog/topic/$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesTechnicalFoundersRoute =
  UseCasesTechnicalFoundersRouteImport.update({
    id: '/use-cases/technical-founders',
    path: '/use-cases/technical-founders',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesPlatformEngineersRoute =
  UseCasesPlatformEngineersRouteImport.update({
    id: '/use-cases/platform-engineers',
    path: '/use-cases/platform-engineers',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesEngineeringLeadersRoute =
  UseCasesEngineeringLeadersRouteImport.update({
    id: '/use-cases/engineering-leaders',
    path: '/use-cases/engineering-leaders',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesAgentBuildersRoute = UseCasesAgentBuildersRouteImport.update({
  id: '/use-cases/agent-builders',
  path: '/use-cases/agent-builders',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRssDotxmlRoute = ChangelogRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => ChangelogRoute,
} as any)
const ChangelogFeedDotxmlRoute = ChangelogFeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => ChangelogRoute,
} as any)
const ChangelogAtomDotxmlRoute = ChangelogAtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => ChangelogRoute,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChangelogRoute,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => BlogRoute,
} as any)
const BlogFeedDotxmlRoute = BlogFeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAtomDotxmlRoute = BlogAtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogTopicCategoryRoute = BlogTopicCategoryRouteImport.update({
  id: '/topic/$category',
  path: '/topic/$category',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/company': typeof CompanyRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/changelog/atom.xml': typeof ChangelogAtomDotxmlRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/changelog/rss.xml': typeof ChangelogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/use-cases/agent-builders': typeof UseCasesAgentBuildersRoute
  '/use-cases/engineering-leaders': typeof UseCasesEngineeringLeadersRoute
  '/use-cases/platform-engineers': typeof UseCasesPlatformEngineersRoute
  '/use-cases/technical-founders': typeof UseCasesTechnicalFoundersRoute
  '/blog/topic/$category': typeof BlogTopicCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/company': typeof CompanyRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/changelog/atom.xml': typeof ChangelogAtomDotxmlRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/changelog/rss.xml': typeof ChangelogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/use-cases/agent-builders': typeof UseCasesAgentBuildersRoute
  '/use-cases/engineering-leaders': typeof UseCasesEngineeringLeadersRoute
  '/use-cases/platform-engineers': typeof UseCasesPlatformEngineersRoute
  '/use-cases/technical-founders': typeof UseCasesTechnicalFoundersRoute
  '/blog/topic/$category': typeof BlogTopicCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/company': typeof CompanyRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/changelog/atom.xml': typeof ChangelogAtomDotxmlRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/changelog/rss.xml': typeof ChangelogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/use-cases/agent-builders': typeof UseCasesAgentBuildersRoute
  '/use-cases/engineering-leaders': typeof UseCasesEngineeringLeadersRoute
  '/use-cases/platform-engineers': typeof UseCasesPlatformEngineersRoute
  '/use-cases/technical-founders': typeof UseCasesTechnicalFoundersRoute
  '/blog/topic/$category': typeof BlogTopicCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/company'
    | '/llms.txt'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/atom.xml'
    | '/blog/feed.xml'
    | '/blog/rss.xml'
    | '/changelog/$slug'
    | '/changelog/atom.xml'
    | '/changelog/feed.xml'
    | '/changelog/rss.xml'
    | '/docs/$'
    | '/legal/$slug'
    | '/use-cases/agent-builders'
    | '/use-cases/engineering-leaders'
    | '/use-cases/platform-engineers'
    | '/use-cases/technical-founders'
    | '/blog/topic/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/company'
    | '/llms.txt'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/atom.xml'
    | '/blog/feed.xml'
    | '/blog/rss.xml'
    | '/changelog/$slug'
    | '/changelog/atom.xml'
    | '/changelog/feed.xml'
    | '/changelog/rss.xml'
    | '/docs/$'
    | '/legal/$slug'
    | '/use-cases/agent-builders'
    | '/use-cases/engineering-leaders'
    | '/use-cases/platform-engineers'
    | '/use-cases/technical-founders'
    | '/blog/topic/$category'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/company'
    | '/llms.txt'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/atom.xml'
    | '/blog/feed.xml'
    | '/blog/rss.xml'
    | '/changelog/$slug'
    | '/changelog/atom.xml'
    | '/changelog/feed.xml'
    | '/changelog/rss.xml'
    | '/docs/$'
    | '/legal/$slug'
    | '/use-cases/agent-builders'
    | '/use-cases/engineering-leaders'
    | '/use-cases/platform-engineers'
    | '/use-cases/technical-founders'
    | '/blog/topic/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DocsSplatRoute: typeof DocsSplatRoute
  LegalSlugRoute: typeof LegalSlugRoute
  UseCasesAgentBuildersRoute: typeof UseCasesAgentBuildersRoute
  UseCasesEngineeringLeadersRoute: typeof UseCasesEngineeringLeadersRoute
  UseCasesPlatformEngineersRoute: typeof UseCasesPlatformEngineersRoute
  UseCasesTechnicalFoundersRoute: typeof UseCasesTechnicalFoundersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/technical-founders': {
      id: '/use-cases/technical-founders'
      path: '/use-cases/technical-founders'
      fullPath: '/use-cases/technical-founders'
      preLoaderRoute: typeof UseCasesTechnicalFoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/platform-engineers': {
      id: '/use-cases/platform-engineers'
      path: '/use-cases/platform-engineers'
      fullPath: '/use-cases/platform-engineers'
      preLoaderRoute: typeof UseCasesPlatformEngineersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/engineering-leaders': {
      id: '/use-cases/engineering-leaders'
      path: '/use-cases/engineering-leaders'
      fullPath: '/use-cases/engineering-leaders'
      preLoaderRoute: typeof UseCasesEngineeringLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/agent-builders': {
      id: '/use-cases/agent-builders'
      path: '/use-cases/agent-builders'
      fullPath: '/use-cases/agent-builders'
      preLoaderRoute: typeof UseCasesAgentBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/rss.xml': {
      id: '/changelog/rss.xml'
      path: '/rss.xml'
      fullPath: '/changelog/rss.xml'
      preLoaderRoute: typeof ChangelogRssDotxmlRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/changelog/feed.xml': {
      id: '/changelog/feed.xml'
      path: '/feed.xml'
      fullPath: '/changelog/feed.xml'
      preLoaderRoute: typeof ChangelogFeedDotxmlRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/changelog/atom.xml': {
      id: '/changelog/atom.xml'
      path: '/atom.xml'
      fullPath: '/changelog/atom.xml'
      preLoaderRoute: typeof ChangelogAtomDotxmlRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/feed.xml': {
      id: '/blog/feed.xml'
      path: '/feed.xml'
      fullPath: '/blog/feed.xml'
      preLoaderRoute: typeof BlogFeedDotxmlRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/atom.xml': {
      id: '/blog/atom.xml'
      path: '/atom.xml'
      fullPath: '/blog/atom.xml'
      preLoaderRoute: typeof BlogAtomDotxmlRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/topic/$category': {
      id: '/blog/topic/$category'
      path: '/topic/$category'
      fullPath: '/blog/topic/$category'
      preLoaderRoute: typeof BlogTopicCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAtomDotxmlRoute: typeof BlogAtomDotxmlRoute
  BlogFeedDotxmlRoute: typeof BlogFeedDotxmlRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  BlogTopicCategoryRoute: typeof BlogTopicCategoryRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogAtomDotxmlRoute: BlogAtomDotxmlRoute,
  BlogFeedDotxmlRoute: BlogFeedDotxmlRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  BlogTopicCategoryRoute: BlogTopicCategoryRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ChangelogRouteChildren {
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  ChangelogAtomDotxmlRoute: typeof ChangelogAtomDotxmlRoute
  ChangelogFeedDotxmlRoute: typeof ChangelogFeedDotxmlRoute
  ChangelogRssDotxmlRoute: typeof ChangelogRssDotxmlRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogSlugRoute: ChangelogSlugRoute,
  ChangelogAtomDotxmlRoute: ChangelogAtomDotxmlRoute,
  ChangelogFeedDotxmlRoute: ChangelogFeedDotxmlRoute,
  ChangelogRssDotxmlRoute: ChangelogRssDotxmlRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  CompanyRoute: CompanyRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DocsSplatRoute: DocsSplatRoute,
  LegalSlugRoute: LegalSlugRoute,
  UseCasesAgentBuildersRoute: UseCasesAgentBuildersRoute,
  UseCasesEngineeringLeadersRoute: UseCasesEngineeringLeadersRoute,
  UseCasesPlatformEngineersRoute: UseCasesPlatformEngineersRoute,
  UseCasesTechnicalFoundersRoute: UseCasesTechnicalFoundersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
