export const LIGHTFAST_AGENT_RUNTIME_BRAINTRUST_PROJECT =
  "lightfast-agent-runtime";

export const LIGHTFAST_AGENT_RUNTIME_BRAINTRUST_PARENT =
  `project_name:${LIGHTFAST_AGENT_RUNTIME_BRAINTRUST_PROJECT}`;
