// Schema exports

// Client
export { type Database, db, getClient } from "./client";

// Re-exported schema definitions
export {
  AUTOMATION_ID_PREFIX,
  AUTOMATION_RUN_ID_PREFIX,
  type Automation,
  type AutomationRun,
  type AutomationRunStatus,
  type AutomationRunTrigger,
  type AutomationScheduleConfig,
  type AutomationScheduleKind,
  type AutomationStatus,
  automationRuns,
  automations,
  createAutomationId,
  createAutomationRunId,
  createMcpOauthClientId,
  createMcpOauthGrantId,
  createMcpOauthRegistrationTokenId,
  createPeopleViewId,
  createPersonId,
  createSignalId,
  createSignalViewId,
  hashMcpOauthResource,
  type InsertAutomation,
  type InsertAutomationRun,
  type InsertMcpAuditEvent,
  type InsertMcpOauthAuthorizationCode,
  type InsertMcpOauthClient,
  type InsertMcpOauthClientRedirectUri,
  type InsertMcpOauthGrant,
  type InsertMcpOauthRefreshToken,
  type InsertMcpOauthRegistrationToken,
  type InsertOrgSourceControlBinding,
  type InsertPeopleView,
  type InsertPerson,
  type InsertSignal,
  type InsertSignalView,
  type InsertSkillIndexEntry,
  type InsertSkillIndexState,
  type InsertSourceControlRepository,
  type InsertSourceControlWebhookDelivery,
  type InsertUserSourceControlAccount,
  type McpAuditEvent,
  type McpAuditOutcome,
  type McpCodeChallengeMethod,
  type McpOauthAuthorizationCode,
  type McpOauthClient,
  type McpOauthClientRedirectUri,
  type McpOauthClientStatus,
  type McpOauthGrant,
  type McpOauthGrantStatus,
  type McpOauthMetadata,
  type McpOauthRefreshToken,
  type McpOauthRefreshTokenStatus,
  type McpOauthRegistrationToken,
  type McpOauthRegistrationTokenStatus,
  mcpAuditEvents,
  mcpOauthAuthorizationCodes,
  mcpOauthClientRedirectUris,
  mcpOauthClients,
  mcpOauthGrants,
  mcpOauthRefreshTokens,
  mcpOauthRegistrationTokens,
  type OrgSourceControlBinding,
  type OrgSourceControlBindingProvider,
  type OrgSourceControlBindingStatus,
  orgSourceControlBindings,
  PEOPLE_VIEW_ID_PREFIX,
  PERSON_DISPLAY_NAME_LENGTH,
  PERSON_ID_PREFIX,
  PERSON_NORMALIZED_IDENTITY_VALUE_LENGTH,
  type PeopleView,
  type PeopleViewConfig,
  type Person,
  type PersonIdentityProvider,
  type PersonIdentityType,
  people,
  peopleViews,
  type ResourcesTruncatedFlag,
  SIGNAL_VIEW_ID_PREFIX,
  type Signal,
  type SignalView,
  type SignalViewConfig,
  type SkillIndexEntry,
  type SkillIndexEntryMetadata,
  type SkillIndexState,
  type SourceControlRepository,
  type SourceControlWebhookDelivery,
  signals,
  signalViews,
  skillIndexEntries,
  skillIndexEntriesRelations,
  skillIndexStates,
  skillIndexStatesRelations,
  sourceControlRepositories,
  sourceControlRepositoriesRelations,
  sourceControlWebhookDeliveries,
  type UserSourceControlAccount,
  type UserSourceControlAccountProvider,
  type UserSourceControlAccountStatus,
  userSourceControlAccounts,
} from "./schema";
export {
  type ClaimedAutomationRun,
  type CreateAutomationInput,
  calculateNextRunAt,
  claimDueAutomationRuns,
  createAutomation,
  createAutomationRun,
  type GetAutomationByPublicIdInput,
  getAutomationByPublicId,
  getAutomationRunByIdempotencyKey,
  getAutomationRunByPublicId,
  listAutomationRuns,
  listAutomations,
  markAutomationRunCompleted,
  markAutomationRunFailed,
  markAutomationRunRunning,
  markAutomationRunSkipped,
  type NormalizedAutomationSchedule,
  normalizeAutomationSchedule,
  setAutomationStatus,
  type UpdateAutomationInput,
  updateAutomation,
} from "./utils/automations";
export {
  type CreateMcpAuthorizationCodeInput,
  type CreateMcpOauthClientInput,
  type CreateMcpOauthGrantInput,
  type CreateMcpRefreshTokenInput,
  consumeMcpAuthorizationCode,
  createMcpAuthorizationCode,
  createMcpOauthClient,
  createMcpOauthGrant,
  createMcpRefreshToken,
  getActiveMcpOauthGrant,
  getMcpOauthClientByClientId,
  getMcpOauthClientByRegistrationTokenHash,
  getMcpOauthGrantByPublicId,
  listMcpOauthGrantConnectionsForOrg,
  listMcpOauthGrantConnectionsForUser,
  type McpOauthClientWithRedirectUris,
  type McpOauthGrantConnection,
  type McpRefreshTokenStatusSummary,
  type RecordMcpAuditEventInput,
  type RotateMcpRefreshTokenInput,
  type RotateMcpRefreshTokenResult,
  recordMcpAuditEvent,
  redactAuditMetadata,
  revokeMcpOauthGrant,
  revokeMcpRefreshTokenByHash,
  rotateMcpRefreshToken,
} from "./utils/mcp-oauth";
export {
  deletePreClerkNamespaceReservation,
  failUnreservedNamespaceOperation,
  finalizeNamespaceOperation,
  getActiveNamespaceByHandle,
  getClaimedNamespaceForOwner,
  getNamespaceByHandle,
  getNamespaceOperationById,
  getNamespaceOperationByIdempotencyKey,
  markNamespaceOperationClerkApplied,
  type NamespaceConflictCode,
  NamespaceConflictError,
  NamespaceOperationConcurrencyError,
  NamespaceOperationTransitionError,
  reserveNamespaceForOperation,
  type StartNamespaceOperationInput,
  startNamespaceOperation,
  transitionNamespaceOperation,
} from "./utils/namespaces";
// Utilities
export { buildOrgNamespace } from "./utils/org";
// Org source-control binding repository helpers
export {
  type FinalizeActiveOrgProviderBindingInput,
  finalizeActiveOrgProviderBinding,
  type GetOrgBindingByProviderInstallationInput,
  getActiveOrgBinding,
  getOrgBindingByProviderInstallation,
  type MarkOrgBindingRevokedInput,
  markOrgBindingRevoked,
  type OrgSourceControlBindingConflictCode,
  OrgSourceControlBindingConflictError,
  type UpsertActiveOrgBindingInput,
  upsertActiveOrgBinding,
} from "./utils/org-binding";
export {
  getPersonByIdentityKey,
  getPersonByPublicId,
  type ListPeopleParams,
  listPeople,
  type UpsertPeopleCandidate,
  type UpsertPeopleFromCandidatesInput,
  upsertPeopleFromCandidates,
} from "./utils/people";
export {
  type CreatePeopleViewParams,
  createPeopleView,
  type DeletePeopleViewParams,
  deletePeopleView,
  type ListPeopleViewsParams,
  listPeopleViews,
} from "./utils/people-views";
export {
  type CreateSignalViewParams,
  createSignalView,
  type DeleteSignalViewParams,
  deleteSignalView,
  type ListSignalViewsParams,
  listSignalViews,
} from "./utils/signal-views";
export {
  type ClaimSignalForClassificationParams,
  type CreateSignalRecordInput,
  claimSignalForClassification,
  createSignal,
  type GetSignalByPublicIdParams,
  type GetVisibleSignalByPublicIdParams,
  getSignalByPublicId,
  getVisibleSignalByPublicId,
  type ListSignalsParams,
  type ListWorkspaceSignalsParams,
  listSignals,
  listWorkspaceSignals,
  type MarkSignalClassifiedParams,
  type MarkSignalFailedParams,
  markSignalClassified,
  markSignalFailed,
  type WorkspaceSignalListItem,
  type WorkspaceSignalsResult,
} from "./utils/signals";
export {
  acquireSkillIndexRefreshLock,
  createOrLoadSkillIndexState,
  getSkillIndexableSourceControlRepositoryCandidateById,
  getSkillIndexEntryBySlug,
  getSkillIndexStateBySourceControlRepositoryId,
  listSkillIndexableSourceControlRepositoryCandidates,
  listSkillIndexEntries,
  markSkillIndexKnownStale,
  markSkillIndexRefreshFailed,
  type ReplaceSkillIndexEntriesInput,
  type ReplaceSkillIndexEntryInput,
  releaseSkillIndexRefreshLock,
  replaceSkillIndexEntries,
  type SkillIndexableSourceControlRepositoryCandidate,
  SkillIndexRefreshLockLostError,
  updateSkillIndexRefCheck,
} from "./utils/skill-index";
export {
  type CompleteWatchedSourceControlRepositorySetupInput,
  completeWatchedSourceControlRepositorySetup,
  getSourceControlWebhookDeliveryByDeliveryId,
  getWatchedSourceControlRepository,
  getWatchedSourceControlRepositoryById,
  insertWatchedSourceControlRepository,
  listWatchedSourceControlRepositories,
  markSourceControlWebhookDeliveryStatus,
  type RecordSourceControlWebhookDeliveryReceivedResult,
  recordSourceControlWebhookDeliveryReceived,
  type UpsertWatchedSourceControlRepositoryInput,
  upsertWatchedSourceControlRepository,
} from "./utils/source-control-repositories";
export {
  activeProviderUserKey,
  type FinalizeActiveUserSourceControlAccountInput,
  finalizeActiveUserSourceControlAccount,
  type GetUserSourceControlAccountByProviderUserInput,
  getActiveUserSourceControlAccount,
  getUserSourceControlAccountByProviderUser,
  isUserSourceControlBound,
  type MarkUserSourceControlAccountExpiredInput,
  type MarkUserSourceControlAccountRevokedInput,
  markObservedUserSourceControlAccountExpired,
  markObservedUserSourceControlAccountRevoked,
  markUserSourceControlAccountExpired,
  markUserSourceControlAccountRevoked,
  type ObservedUserSourceControlAccountInput,
  type UpdateObservedUserSourceControlAccountTokensInput,
  type UserSourceControlAccountConflictCode,
  UserSourceControlAccountConflictError,
  updateObservedUserSourceControlAccountTokens,
} from "./utils/user-source-control-account";
