// Schema exports

// Client
export { type Database, db, getClient } from "./client";

// Re-exported schema definitions
export {
  AUTOMATION_ID_PREFIX,
  AUTOMATION_RUN_ID_PREFIX,
  type Automation,
  type AutomationRun,
  type AutomationRunStatus,
  type AutomationRunTrigger,
  type AutomationScheduleConfig,
  type AutomationScheduleKind,
  type AutomationStatus,
  automationRuns,
  automations,
  createAutomationId,
  createAutomationRunId,
  createPersonId,
  createSignalId,
  createSignalViewId,
  type InsertAutomation,
  type InsertAutomationRun,
  type InsertOrgSourceControlBinding,
  type InsertPerson,
  type InsertSignal,
  type InsertSignalView,
  type InsertSkillIndexEntry,
  type InsertSkillIndexState,
  type InsertSourceControlRepository,
  type InsertSourceControlWebhookDelivery,
  type InsertUserSourceControlAccount,
  type OrgSourceControlBinding,
  type OrgSourceControlBindingProvider,
  type OrgSourceControlBindingStatus,
  orgSourceControlBindings,
  PERSON_DISPLAY_NAME_LENGTH,
  PERSON_ID_PREFIX,
  PERSON_NORMALIZED_IDENTITY_VALUE_LENGTH,
  type Person,
  type PersonIdentityProvider,
  type PersonIdentityType,
  people,
  type ResourcesTruncatedFlag,
  SIGNAL_VIEW_ID_PREFIX,
  type Signal,
  type SignalView,
  type SignalViewConfig,
  type SignalViewLayout,
  type SkillIndexEntry,
  type SkillIndexEntryMetadata,
  skillIndexEntries,
  type SkillIndexState,
  skillIndexStates,
  skillIndexEntriesRelations,
  skillIndexStatesRelations,
  type SourceControlRepository,
  sourceControlRepositories,
  sourceControlRepositoriesRelations,
  type SourceControlWebhookDelivery,
  sourceControlWebhookDeliveries,
  signals,
  signalViews,
  type UserSourceControlAccount,
  type UserSourceControlAccountProvider,
  type UserSourceControlAccountStatus,
  userSourceControlAccounts,
} from "./schema";
export {
  type ClaimedAutomationRun,
  type CreateAutomationInput,
  calculateNextRunAt,
  claimDueAutomationRuns,
  createAutomation,
  createAutomationRun,
  type GetAutomationByPublicIdInput,
  getAutomationByPublicId,
  getAutomationRunByIdempotencyKey,
  getAutomationRunByPublicId,
  listAutomationRuns,
  listAutomations,
  markAutomationRunCompleted,
  markAutomationRunFailed,
  markAutomationRunRunning,
  markAutomationRunSkipped,
  type NormalizedAutomationSchedule,
  normalizeAutomationSchedule,
  setAutomationStatus,
  type UpdateAutomationInput,
  updateAutomation,
} from "./utils/automations";
// Utilities
export { buildOrgNamespace } from "./utils/org";
// Org source-control binding repository helpers
export {
  type FinalizeActiveOrgProviderBindingInput,
  finalizeActiveOrgProviderBinding,
  type GetOrgBindingByProviderInstallationInput,
  getActiveOrgBinding,
  getOrgBindingByProviderInstallation,
  type MarkOrgBindingRevokedInput,
  markOrgBindingRevoked,
  type OrgSourceControlBindingConflictCode,
  OrgSourceControlBindingConflictError,
  type UpsertActiveOrgBindingInput,
  upsertActiveOrgBinding,
} from "./utils/org-binding";
export {
  getPersonByIdentityKey,
  getPersonByPublicId,
  type ListPeopleParams,
  listPeople,
  type UpsertPeopleCandidate,
  type UpsertPeopleFromCandidatesInput,
  upsertPeopleFromCandidates,
} from "./utils/people";
export {
  type CreateSignalViewParams,
  createSignalView,
  type DeleteSignalViewParams,
  deleteSignalView,
  type ListSignalViewsParams,
  listSignalViews,
} from "./utils/signal-views";
export {
  acquireSkillIndexRefreshLock,
  createOrLoadSkillIndexState,
  getSkillIndexableSourceControlRepositoryCandidateById,
  getSkillIndexEntryBySlug,
  getSkillIndexStateBySourceControlRepositoryId,
  listSkillIndexableSourceControlRepositoryCandidates,
  type SkillIndexableSourceControlRepositoryCandidate,
  listSkillIndexEntries,
  markSkillIndexKnownStale,
  markSkillIndexRefreshFailed,
  releaseSkillIndexRefreshLock,
  type ReplaceSkillIndexEntriesInput,
  type ReplaceSkillIndexEntryInput,
  replaceSkillIndexEntries,
  SkillIndexRefreshLockLostError,
  updateSkillIndexRefCheck,
} from "./utils/skill-index";
export {
  type ClaimSignalForClassificationParams,
  type CreateSignalRecordInput,
  claimSignalForClassification,
  createSignal,
  type GetSignalByPublicIdParams,
  type GetVisibleSignalByPublicIdParams,
  getSignalByPublicId,
  getVisibleSignalByPublicId,
  type ListSignalsParams,
  type ListWorkspaceSignalsParams,
  listSignals,
  listWorkspaceSignals,
  type MarkSignalClassifiedParams,
  type MarkSignalFailedParams,
  markSignalClassified,
  markSignalFailed,
  type WorkspaceSignalListItem,
  type WorkspaceSignalsResult,
} from "./utils/signals";
export {
  type CompleteWatchedSourceControlRepositorySetupInput,
  completeWatchedSourceControlRepositorySetup,
  getSourceControlWebhookDeliveryByDeliveryId,
  getWatchedSourceControlRepository,
  getWatchedSourceControlRepositoryById,
  markSourceControlWebhookDeliveryStatus,
  type RecordSourceControlWebhookDeliveryReceivedResult,
  recordSourceControlWebhookDeliveryReceived,
  type UpsertWatchedSourceControlRepositoryInput,
  upsertWatchedSourceControlRepository,
} from "./utils/source-control-repositories";
export {
  activeProviderUserKey,
  type FinalizeActiveUserSourceControlAccountInput,
  finalizeActiveUserSourceControlAccount,
  type GetUserSourceControlAccountByProviderUserInput,
  getActiveUserSourceControlAccount,
  getUserSourceControlAccountByProviderUser,
  isUserSourceControlBound,
  type MarkUserSourceControlAccountExpiredInput,
  type MarkUserSourceControlAccountRevokedInput,
  markObservedUserSourceControlAccountExpired,
  markObservedUserSourceControlAccountRevoked,
  markUserSourceControlAccountExpired,
  markUserSourceControlAccountRevoked,
  type ObservedUserSourceControlAccountInput,
  type UpdateObservedUserSourceControlAccountTokensInput,
  type UserSourceControlAccountConflictCode,
  UserSourceControlAccountConflictError,
  updateObservedUserSourceControlAccountTokens,
} from "./utils/user-source-control-account";
