// Schema exports

// Client
export { type Database, db, getClient } from "./client";
export {
  AUTOMATION_ID_PREFIX,
  AUTOMATION_RUN_ID_PREFIX,
  type Automation,
  type AutomationRun,
  type AutomationRunStatus,
  type AutomationRunTrigger,
  type AutomationScheduleConfig,
  type AutomationScheduleKind,
  type AutomationStatus,
  createAutomationId,
  createAutomationRunId,
  createDecisionViewId,
  createMcpOauthClientId,
  createMcpOauthGrantId,
  createMcpOauthRegistrationTokenId,
  createPeopleViewId,
  createPersonId,
  createSignalId,
  createSignalViewId,
  createUserConnectorToolCallId,
  createWorkspaceAssistantContextItemId,
  createWorkspaceAssistantConversationId,
  createWorkspaceAssistantGenerationId,
  createWorkspaceAssistantMessageId,
  createWorkspaceAssistantStreamId,
  createWorkspaceAssistantToolCallId,
  DECISION_VIEW_ID_PREFIX,
  type DecisionView,
  type DecisionViewConfig,
  hashMcpOauthResource,
  type IdentityIndexFile,
  type IdentityIndexState,
  type InsertAutomation,
  type InsertAutomationRun,
  type InsertDecisionView,
  type InsertIdentityIndexFile,
  type InsertIdentityIndexState,
  type InsertOrgSourceControlBinding,
  type InsertPeopleView,
  type InsertPerson,
  type InsertSignal,
  type InsertSignalView,
  type InsertSkillIndexEntry,
  type InsertSkillIndexState,
  type InsertSourceControlPrWebhookDelivery,
  type InsertSourceControlRepository,
  type InsertSourceControlWebhookDelivery,
  type InsertUserConnectorConnection,
  type InsertUserConnectorToolCall,
  type InsertUserSourceControlAccount,
  type InsertWorkspaceAssistantContextItem,
  type InsertWorkspaceAssistantConversation,
  type InsertWorkspaceAssistantGeneration,
  type InsertWorkspaceAssistantMessage,
  type InsertWorkspaceAssistantToolCall,
  identityIndexFilesRelations,
  identityIndexStatesRelations,
  type McpAuditEvent,
  type McpAuditOutcome,
  type McpCodeChallengeMethod,
  type McpOauthAuthorizationCode,
  type McpOauthClient,
  type McpOauthClientRedirectUri,
  type McpOauthClientStatus,
  type McpOauthGrant,
  type McpOauthGrantStatus,
  type McpOauthMetadata,
  type McpOauthRefreshToken,
  type McpOauthRefreshTokenStatus,
  type McpOauthRegistrationToken,
  type McpOauthRegistrationTokenStatus,
  type OrgConnectorConnection,
  type OrgSourceControlBinding,
  type OrgSourceControlBindingProvider,
  type OrgSourceControlBindingStatus,
  orgAutomationRuns,
  orgAutomations,
  orgDecisionViews,
  orgIdentityIndexFiles,
  orgIdentityIndexStates,
  orgPeople,
  orgPeopleViews,
  orgSignals,
  orgSignalViews,
  orgSkillIndexEntries,
  orgSkillIndexStates,
  orgSourceControlBindings,
  orgSourceControlPrWebhookDeliveries,
  orgSourceControlRepositories,
  orgSourceControlWebhookDeliveries,
  orgWorkspaceAssistantContextItems,
  orgWorkspaceAssistantConversations,
  orgWorkspaceAssistantGenerations,
  orgWorkspaceAssistantMessages,
  orgWorkspaceAssistantToolCalls,
  PEOPLE_VIEW_ID_PREFIX,
  PERSON_DISPLAY_NAME_LENGTH,
  PERSON_ID_PREFIX,
  PERSON_NORMALIZED_IDENTITY_VALUE_LENGTH,
  type PeopleView,
  type PeopleViewConfig,
  type Person,
  type PersonIdentityProvider,
  type PersonIdentityType,
  type PersonMemberStatus,
  type PersonSource,
  type ProviderRoutineCall,
  type ProviderRoutineCallPayload,
  type ProviderRoutineCallSourceSurface,
  type ResourcesTruncatedFlag,
  SIGNAL_VIEW_ID_PREFIX,
  type Signal,
  type SignalView,
  type SignalViewConfig,
  type SkillIndexEntry,
  type SkillIndexEntryMetadata,
  type SkillIndexState,
  type SourceControlPrWebhookDelivery,
  type SourceControlRepository,
  type SourceControlWebhookDelivery,
  skillIndexEntriesRelations,
  skillIndexStatesRelations,
  sourceControlRepositoriesRelations,
  USER_CONNECTOR_TOOL_CALL_ID_PREFIX,
  type UserConnectorConnection,
  type UserConnectorToolCall,
  type UserConnectorToolCallRedactedPayload,
  type UserConnectorToolCallSourceSurface,
  type UserConnectorToolCallStatus,
  type UserSourceControlAccount,
  type UserSourceControlAccountProvider,
  type UserSourceControlAccountStatus,
  userConnectorConnections,
  userConnectorToolCalls,
  userSourceControlAccounts,
  WORKSPACE_ASSISTANT_CONTEXT_ITEM_ID_PREFIX,
  WORKSPACE_ASSISTANT_CONVERSATION_ID_PREFIX,
  WORKSPACE_ASSISTANT_GENERATION_ID_PREFIX,
  WORKSPACE_ASSISTANT_MESSAGE_ID_PREFIX,
  WORKSPACE_ASSISTANT_STREAM_ID_PREFIX,
  WORKSPACE_ASSISTANT_TOOL_CALL_ID_PREFIX,
  type WorkspaceAssistantContextItem,
  type WorkspaceAssistantContextItemKind,
  type WorkspaceAssistantContextSnapshot,
  type WorkspaceAssistantConversation,
  type WorkspaceAssistantConversationStatus,
  type WorkspaceAssistantGeneration,
  type WorkspaceAssistantGenerationStatus,
  type WorkspaceAssistantGenerationUsage,
  type WorkspaceAssistantMessage,
  type WorkspaceAssistantMessagePart,
  type WorkspaceAssistantMessageRole,
  type WorkspaceAssistantMessageStatus,
  type WorkspaceAssistantRecordMetadata,
  type WorkspaceAssistantToolCall,
  type WorkspaceAssistantToolCallStatus,
  type WorkspaceAssistantToolPayload,
} from "./schema";
// Re-exported schema definitions
export * from "./schema/tables/org-entity-graph";
export {
  type ClaimedAutomationRun,
  type CreateAutomationInput,
  calculateNextRunAt,
  claimDueAutomationRuns,
  createAutomation,
  createAutomationRun,
  deleteAutomation,
  type GetAutomationByPublicIdInput,
  getAutomationByPublicId,
  getAutomationRunByIdempotencyKey,
  getAutomationRunByPublicId,
  listAutomationRuns,
  listAutomations,
  markAutomationRunCompleted,
  markAutomationRunFailed,
  markAutomationRunRunning,
  markAutomationRunSkipped,
  type NormalizedAutomationSchedule,
  normalizeAutomationSchedule,
  setAutomationStatus,
  type UpdateAutomationInput,
  updateAutomation,
} from "./utils/automations";
export {
  type CreateDecisionViewParams,
  createDecisionView,
  type DeleteDecisionViewParams,
  deleteDecisionView,
  type ListDecisionViewsParams,
  listDecisionViews,
} from "./utils/decision-views";
export { isDuplicateKeyError } from "./utils/drizzle-results";
export {
  type AppendEntityObservationInput,
  type AppendResolutionCandidateVersionInput,
  type AppendResolutionCandidateVersionResult,
  appendEntityObservation,
  appendResolutionCandidateVersionIfChanged,
  type EntityAccountEvidenceTrail,
  type EntityPersonEvidenceTrail,
  type EntityResolutionPersistenceBatchInput,
  type EntityResolutionPersistenceCandidateGroupInput,
  type EntityResolutionPersistenceSourceIdentityInput,
  type GetEntityAccountEvidenceTrailInput,
  type GetEntityPersonEvidenceTrailInput,
  getEntityAccountByPublicId,
  getEntityAccountEvidenceTrail,
  getEntityPersonByPublicId,
  getEntityPersonEvidenceTrail,
  type IngestEntityObservationsInput,
  type IngestEntityObservationsResult,
  ingestEntityObservations,
  type ListEntityAccountsInput,
  type ListEntityPeopleInput,
  type ListEntityPersonAccountAffiliationsInput,
  listEntityAccounts,
  listEntityPeople,
  listEntityPersonAccountAffiliations,
  type PersistEntityResolutionBatchInput,
  type PersistEntityResolutionBatchResult,
  persistEntityResolutionBatch,
  type UpsertEntityAccountInput,
  type UpsertEntityPersonInput,
  type UpsertPersonAccountAffiliationInput,
  type UpsertResolutionCandidateGroupInput,
  type UpsertSourceIdentityInput,
  upsertEntityAccount,
  upsertEntityPerson,
  upsertPersonAccountAffiliation,
  upsertResolutionCandidateGroup,
  upsertSourceIdentity,
} from "./utils/entity-graph";
export {
  acquireIdentityIndexRefreshLock,
  createOrLoadIdentityIndexState,
  getIdentityIndexRefreshCandidateById,
  getIdentityIndexStateBySourceControlRepositoryId,
  type IdentityIndexRefreshCandidate,
  IdentityIndexRefreshLockLostError,
  listIdentityIndexFiles,
  listIdentityIndexRefreshCandidates,
  markIdentityIndexKnownStale,
  markIdentityIndexRefreshFailed,
  type ReplaceIdentityIndexFileInput,
  type ReplaceIdentityIndexFilesInput,
  releaseIdentityIndexRefreshLock,
  replaceIdentityIndexFiles,
  updateIdentityIndexRefCheck,
} from "./utils/identity-index";
// MCP OAuth, connector, and provider-routine DB helpers
export * from "./utils/mcp-oauth";
export {
  type ActiveOrgNamespaceClerkOrgId,
  deletePreClerkNamespaceReservation,
  failUnreservedNamespaceOperation,
  finalizeNamespaceOperation,
  getActiveNamespaceByHandle,
  getClaimedNamespaceForOwner,
  getNamespaceByHandle,
  getNamespaceOperationById,
  getNamespaceOperationByIdempotencyKey,
  type ListActiveOrgNamespaceClerkOrgIdsInput,
  listActiveOrgNamespaceClerkOrgIds,
  markNamespaceOperationClerkApplied,
  type NamespaceConflictCode,
  NamespaceConflictError,
  NamespaceOperationConcurrencyError,
  NamespaceOperationTransitionError,
  reserveNamespaceForOperation,
  type StartNamespaceOperationInput,
  startNamespaceOperation,
  transitionNamespaceOperation,
} from "./utils/namespaces";
// Utilities
export { buildOrgNamespace } from "./utils/org";
// Org source-control binding repository helpers
export {
  type FinalizeActiveOrgProviderBindingInput,
  finalizeActiveOrgProviderBinding,
  type GetOrgBindingByProviderInstallationInput,
  getActiveOrgBinding,
  getOrgBindingByProviderInstallation,
  type MarkOrgBindingRevokedInput,
  markOrgBindingRevoked,
  type OrgSourceControlBindingConflictCode,
  OrgSourceControlBindingConflictError,
  type UpsertActiveOrgBindingInput,
  upsertActiveOrgBinding,
} from "./utils/org-binding";
export {
  currentOrgProviderKey,
  type FinalizeCurrentOrgConnectorConnectionInput,
  finalizeCurrentOrgConnectorConnection,
  type GetCurrentOrgConnectorConnectionInput,
  getCurrentOrgConnectorConnection,
  listCurrentOrgConnectorConnections,
  markCurrentOrgConnectorConnectionError,
  markCurrentOrgConnectorConnectionRevoked,
  type ObservedCurrentOrgConnectorConnectionInput,
  type RecordConnectorToolRefreshErrorInput,
  recordConnectorToolRefreshError,
  setConnectorAgentEnabled,
  setConnectorAutomationEnabled,
  type UpdateConnectorToolManifestAndAutomationStateInput,
  type UpdateConnectorToolManifestInput,
  type UpdateObservedConnectorTokensInput,
  updateConnectorToolManifest,
  updateConnectorToolManifestAndAutomationState,
  updateObservedConnectorTokens,
} from "./utils/org-connector-connections";
export {
  getPersonByIdentityKey,
  getPersonByPublicId,
  type ListPeopleParams,
  listPeople,
  type ProjectEntityGraphPeopleToOrgPeopleInput,
  projectEntityGraphPeopleToOrgPeople,
  type UpsertPeopleCandidate,
  type UpsertPeopleFromCandidatesInput,
  upsertPeopleFromCandidates,
} from "./utils/people";
export {
  markFormerTeamMembersMissingFromSync,
  type SyncOrgTeamMemberPeopleInput,
  type SyncOrgTeamMemberPeopleResult,
  syncOrgTeamMemberPeople,
  type TeamMemberPeopleCandidate,
} from "./utils/people-team-members";
export {
  type CreatePeopleViewParams,
  createPeopleView,
  type DeletePeopleViewParams,
  deletePeopleView,
  type ListPeopleViewsParams,
  listPeopleViews,
} from "./utils/people-views";
export * from "./utils/provider-routine-calls";
export {
  buildSignalEntityLinkResolutionHints,
  listSignalEntityEnrichmentTargets,
  listSignalEntityLinksForSignal,
  type ReplaceSignalEntityLinksInput,
  type ReplaceSignalEntityLinksResult,
  reconcileSignalEntityLinksForPeople,
  replaceSignalEntityLinks,
  type SignalEntityEnrichmentSkippedTarget,
  type SignalEntityEnrichmentTarget,
  type SignalEntityEnrichmentTargetsResult,
  type SignalEntityLinkDetail,
  type SignalEntityLinkReconciliationPerson,
  type SignalEntityLinkResolutionHints,
  type SignalEntityLinkResolvedPerson,
} from "./utils/signal-entity-links";
export {
  type CreateSignalViewParams,
  createSignalView,
  type DeleteSignalViewParams,
  deleteSignalView,
  type ListSignalViewsParams,
  listSignalViews,
} from "./utils/signal-views";
export {
  type ClaimSignalForClassificationParams,
  type CreateSignalRecordInput,
  claimSignalForClassification,
  createSignal,
  type GetSignalByPublicIdParams,
  type GetVisibleSignalByPublicIdParams,
  getSignalByPublicId,
  getVisibleSignalByPublicId,
  type ListSignalEntityIndexBackfillCandidatesParams,
  type ListSignalEntityIndexBackfillCandidatesResult,
  type ListSignalsParams,
  type ListWorkspaceSignalsParams,
  listSignalEntityIndexBackfillCandidates,
  listSignals,
  listWorkspaceSignals,
  type MarkSignalClassifiedParams,
  type MarkSignalFailedParams,
  markSignalClassified,
  markSignalFailed,
  type SignalEntityIndexBackfillCandidate,
  type WorkspaceSignalListItem,
  type WorkspaceSignalsResult,
} from "./utils/signals";
export {
  acquireSkillIndexRefreshLock,
  createOrLoadSkillIndexState,
  getSkillIndexableSourceControlRepositoryCandidateById,
  getSkillIndexEntryBySlug,
  getSkillIndexStateBySourceControlRepositoryId,
  listSkillIndexableSourceControlRepositoryCandidates,
  listSkillIndexEntries,
  markSkillIndexKnownStale,
  markSkillIndexRefreshFailed,
  markSkillIndexRefreshFresh,
  markSkillIndexRefreshStale,
  type ReplaceSkillIndexEntriesInput,
  type ReplaceSkillIndexEntryInput,
  releaseSkillIndexRefreshLock,
  replaceSkillIndexEntries,
  type SkillIndexableSourceControlRepositoryCandidate,
  SkillIndexRefreshLockLostError,
  updateSkillIndexRefCheck,
} from "./utils/skill-index";
export {
  type CompleteWatchedSourceControlRepositorySetupInput,
  completeWatchedSourceControlRepositorySetup,
  getSourceControlPrWebhookDeliveryByDeliveryId,
  getSourceControlWebhookDeliveryByDeliveryId,
  getWatchedSourceControlRepository,
  getWatchedSourceControlRepositoryById,
  insertWatchedSourceControlRepository,
  listWatchedSourceControlRepositories,
  markSourceControlWebhookDeliveryStatus,
  type RecordSourceControlPrWebhookDeliveryInput,
  type RecordSourceControlPrWebhookDeliveryResult,
  type RecordSourceControlWebhookDeliveryReceivedResult,
  recordSourceControlPrWebhookDelivery,
  recordSourceControlWebhookDeliveryReceived,
  type UpsertWatchedSourceControlRepositoryInput,
  upsertWatchedSourceControlRepository,
} from "./utils/source-control-repositories";
export {
  currentUserProviderKey,
  type FinalizeCurrentUserConnectorConnectionInput,
  finalizeCurrentUserConnectorConnection,
  type GetCurrentUserConnectorConnectionInput,
  getCurrentUserConnectorConnection,
  listCurrentUserConnectorConnections,
  markCurrentUserConnectorConnectionError,
  markCurrentUserConnectorConnectionRevoked,
  type ObservedCurrentUserConnectorConnectionInput,
  type RecordUserConnectorToolRefreshErrorInput,
  recordUserConnectorToolRefreshError,
  type UpdateObservedUserConnectorTokensInput,
  type UpdateUserConnectorToolManifestInput,
  updateObservedUserConnectorTokens,
  updateUserConnectorToolManifest,
} from "./utils/user-connector-connections";
export * from "./utils/user-connector-tool-calls";
export {
  activeProviderUserKey,
  type FinalizeActiveUserSourceControlAccountInput,
  finalizeActiveUserSourceControlAccount,
  type GetUserSourceControlAccountByProviderUserInput,
  getActiveUserSourceControlAccount,
  getUserSourceControlAccountByProviderUser,
  isUserSourceControlBound,
  type MarkUserSourceControlAccountExpiredInput,
  type MarkUserSourceControlAccountRevokedInput,
  markObservedUserSourceControlAccountExpired,
  markObservedUserSourceControlAccountRevoked,
  markUserSourceControlAccountExpired,
  markUserSourceControlAccountRevoked,
  type ObservedUserSourceControlAccountInput,
  type UpdateObservedUserSourceControlAccountTokensInput,
  type UserSourceControlAccountConflictCode,
  UserSourceControlAccountConflictError,
  updateObservedUserSourceControlAccountTokens,
} from "./utils/user-source-control-account";
export {
  type AppendWorkspaceAssistantMessageInput,
  appendWorkspaceAssistantMessage,
  type CreateWorkspaceAssistantConversationInput,
  type CreateWorkspaceAssistantGenerationInput,
  createWorkspaceAssistantConversation,
  createWorkspaceAssistantGeneration,
  type GetWorkspaceAssistantConversationByPublicIdInput,
  type GetWorkspaceAssistantGenerationByPublicIdInput,
  type GetWorkspaceAssistantMessageByIdempotencyKeyInput,
  type GetWorkspaceAssistantMessageByPublicIdInput,
  getWorkspaceAssistantConversationByPublicId,
  getWorkspaceAssistantGenerationByPublicId,
  getWorkspaceAssistantMessageByIdempotencyKey,
  getWorkspaceAssistantMessageByPublicId,
  type ListWorkspaceAssistantConversationsInput,
  type ListWorkspaceAssistantMessagesInput,
  listWorkspaceAssistantConversations,
  listWorkspaceAssistantMessages,
  type MarkWorkspaceAssistantGenerationCompletedInput,
  type MarkWorkspaceAssistantGenerationFailedInput,
  type MarkWorkspaceAssistantMessageCompletedInput,
  type MarkWorkspaceAssistantMessageFailedInput,
  markWorkspaceAssistantGenerationCompleted,
  markWorkspaceAssistantGenerationFailed,
  markWorkspaceAssistantMessageCompleted,
  markWorkspaceAssistantMessageFailed,
  type SetWorkspaceAssistantConversationActiveStreamInput,
  setWorkspaceAssistantConversationActiveStream,
  type WorkspaceAssistantConversationCursor,
  type WorkspaceAssistantListResult,
} from "./utils/workspace-assistant";
