// Table schemas
export {
  AUTOMATION_ID_PREFIX,
  AUTOMATION_RUN_ID_PREFIX,
  type Automation,
  type AutomationRun,
  type AutomationRunStatus,
  type AutomationRunTrigger,
  type AutomationScheduleConfig,
  type AutomationScheduleKind,
  type AutomationStatus,
  automationRuns,
  automations,
  createAutomationId,
  createAutomationRunId,
  createPersonId,
  createSignalId,
  createSignalViewId,
  type InsertAutomation,
  type InsertAutomationRun,
  type InsertOrgSourceControlBinding,
  type InsertPerson,
  type InsertSignal,
  type InsertSignalView,
  type OrgSourceControlBinding,
  type OrgSourceControlBindingProvider,
  type OrgSourceControlBindingStatus,
  orgSourceControlBindings,
  PERSON_DISPLAY_NAME_LENGTH,
  PERSON_ID_PREFIX,
  PERSON_NORMALIZED_IDENTITY_VALUE_LENGTH,
  type Person,
  type PersonIdentityProvider,
  type PersonIdentityType,
  people,
  type Signal,
  SIGNAL_VIEW_ID_PREFIX,
  signals,
  type SignalView,
  type SignalViewConfig,
  type SignalViewLayout,
  signalViews,
} from "./tables";
