// Table schemas
export {
  skillIndexEntriesRelations,
  skillIndexStatesRelations,
  sourceControlRepositoriesRelations,
} from "./relations";
export {
  AUTOMATION_ID_PREFIX,
  AUTOMATION_RUN_ID_PREFIX,
  type Automation,
  type AutomationRun,
  type AutomationRunStatus,
  type AutomationRunTrigger,
  type AutomationScheduleConfig,
  type AutomationScheduleKind,
  type AutomationStatus,
  automationRuns,
  automations,
  createAutomationId,
  createAutomationRunId,
  createMcpOauthClientId,
  createMcpOauthGrantId,
  createMcpOauthRegistrationTokenId,
  createPeopleViewId,
  createPersonId,
  createSignalId,
  createSignalViewId,
  hashMcpOauthResource,
  type InsertAutomation,
  type InsertAutomationRun,
  type InsertMcpAuditEvent,
  type InsertMcpOauthAuthorizationCode,
  type InsertMcpOauthClient,
  type InsertMcpOauthClientRedirectUri,
  type InsertMcpOauthGrant,
  type InsertMcpOauthRefreshToken,
  type InsertMcpOauthRegistrationToken,
  type InsertNamespace,
  type InsertNamespaceOperation,
  type InsertOrgSourceControlBinding,
  type InsertPeopleView,
  type InsertPerson,
  type InsertSignal,
  type InsertSignalView,
  type InsertSkillIndexEntry,
  type InsertSkillIndexState,
  type InsertSourceControlRepository,
  type InsertSourceControlWebhookDelivery,
  type InsertUserSourceControlAccount,
  type McpAuditEvent,
  type McpAuditOutcome,
  type McpCodeChallengeMethod,
  type McpOauthAuthorizationCode,
  type McpOauthClient,
  type McpOauthClientRedirectUri,
  type McpOauthClientStatus,
  type McpOauthGrant,
  type McpOauthGrantStatus,
  type McpOauthMetadata,
  type McpOauthRefreshToken,
  type McpOauthRefreshTokenStatus,
  type McpOauthRegistrationToken,
  type McpOauthRegistrationTokenStatus,
  mcpAuditEvents,
  mcpOauthAuthorizationCodes,
  mcpOauthClientRedirectUris,
  mcpOauthClients,
  mcpOauthGrants,
  mcpOauthRefreshTokens,
  mcpOauthRegistrationTokens,
  type Namespace,
  type NamespaceKind,
  type NamespaceOperation,
  type NamespaceOperationStatus,
  type NamespaceOperationType,
  type NamespaceStatus,
  namespaceOperations,
  namespaces,
  type OrgSourceControlBinding,
  type OrgSourceControlBindingProvider,
  type OrgSourceControlBindingStatus,
  orgSourceControlBindings,
  PEOPLE_VIEW_ID_PREFIX,
  PERSON_DISPLAY_NAME_LENGTH,
  PERSON_ID_PREFIX,
  PERSON_NORMALIZED_IDENTITY_VALUE_LENGTH,
  type PeopleView,
  type PeopleViewConfig,
  type Person,
  type PersonIdentityProvider,
  type PersonIdentityType,
  people,
  peopleViews,
  type ResourcesTruncatedFlag,
  SIGNAL_VIEW_ID_PREFIX,
  type Signal,
  type SignalView,
  type SignalViewConfig,
  type SkillIndexEntry,
  type SkillIndexEntryMetadata,
  type SkillIndexState,
  type SourceControlRepository,
  type SourceControlWebhookDelivery,
  signals,
  signalViews,
  skillIndexEntries,
  skillIndexStates,
  sourceControlRepositories,
  sourceControlWebhookDeliveries,
  type UserSourceControlAccount,
  type UserSourceControlAccountProvider,
  type UserSourceControlAccountStatus,
  userSourceControlAccounts,
} from "./tables";
